### ISSUE TITLE
Prematurely out of memory

### ISSUE THREAD

**Issue by rparini** [cupy/cupy#1392]
Hi, I'm having trouble with memory management.  I am on OSX Sierra using cupy 4.1.0 from pip with CUDA 9.1 on an Nvidia GTX 970 which has 4095 MB memory.  I can create a 1.6GB array without a problem:
```Python
import cupy
result = cupy.random.normal(size=[4*10**8], dtype=cupy.float32)
```
But when I repeatedly allocate arrays of increasing size:
```Python
import cupy
for i in range(4*10**8):
	result = cupy.random.normal(size=[i], dtype=cupy.float32)
	del result
```
I soon get an OutOfMemoryError:
```
Traceback (most recent call last):
  File "TestCupy.py", line 5, in <module>
    result = cupy.random.normal(size=[i], dtype=cupy.float32)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cupy/random/distributions.py", line 93, in normal
    x = rs.normal(0, 1, size, dtype)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cupy/random/generator.py", line 116, in normal
    return self._generate_normal(func, size, dtype, loc, scale)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cupy/random/generator.py", line 82, in _generate_normal
    out = cupy.empty((element_size + 1,), dtype=dtype)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cupy/creation/basic.py", line 19, in empty
    return cupy.ndarray(shape, dtype=dtype, order=order)
  File "cupy/core/core.pyx", line 96, in cupy.core.core.ndarray.__init__
  File "cupy/cuda/memory.pyx", line 468, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 964, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 985, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 765, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 828, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
cupy.cuda.memory.OutOfMemoryError: out of memory to allocate 1411072 bytes (total 1411072 bytes)
```
I don't understand why it can't allocate 1.4MB, there should be more than enough memory.  Is there something I need to do to free the memory taken up by the previous arrays?

**Comment by fiarabbit** [comment]
In short, that is because you cannot manage the order of constructor call and destructor in GPU.

`del result` does NOT immediately free GPU memory, but the signal is stacked in the GPU queue.
Therefore, in an extreme case, your code works like the code below.

```actual_order.py
import cupy

for i in range(4*10**8):
    result = cupy.random.normal(size=[i], dtype=cupy.float32)

for i in range(4*10**8):
    del result
```
Because sum(1, 2, ..., N) increases at N^2 order, when i ==  1.4 * 10^6, the consumed memory is 2 * 10^12, which is far from the memory limitation.

**Comment by rparini** [comment]
Ok, thank you, that makes sense.  Is there a way to get how much memory is waiting to be freed or if there are any destructor calls issued by cupy waiting to be implemented?  I suppose I want to do something like
```Python
import cupy

for i in range(4*10**8):
    while True:
        try:
            result = cupy.random.normal(size=[i], dtype=cupy.float32)
            break
        except cupy.cuda.memory.OutOfMemoryError as e:
            if WAITING_FOR_DESTRUCTOR:
                continue
            raise e
    del result
```
By the way, I realise this is quite a contrived example.  However, in reality I'm working with data that is usually a fixed size but sometimes needs to be extended during runtime and have been running into this problem.

**Comment by okuta** [comment]
I expect that this issue solved by #1511 and #1597.
Cloud you try CuPy master branch?

**Comment by rparini** [comment]
Yes, I'm no longer seeing the OutOfMemoryError when using the master branch, thanks!

**Comment by okuta** [comment]
Thanks too!
