### ISSUE TITLE
Probably memory leak in the cp.dot()

### ISSUE THREAD

**Issue by alkalinin** [cupy/cupy#1484]
The following code works perfect:
```python
import numpy as np
import cupy as cp

mp = cp.get_default_memory_pool()

n = 12000
A_cpu = np.random.rand(n, n).astype(np.float32)
B_cpu = np.random.rand(n, n).astype(np.float32)

max_iter = 5
for i in range(max_iter):
    A_gpu = cp.asarray(A_cpu)
    B_gpu = cp.asarray(B_cpu)
    C_gpu = cp.zeros((n, n), dtype=np.float32)
    #cp.dot(A_gpu, B_gpu, out=C_gpu)
    print('iter {:d}/{:d}, memory: {:.2f} G'.format(i, max_iter - 1 , mp.used_bytes() / (2**30)))
```
Output is:
```
iter 0/9, memory: 1.61 G
iter 1/9, memory: 1.61 G
iter 2/9, memory: 1.61 G
iter 3/9, memory: 1.61 G
iter 4/9, memory: 1.61 G
```

However, code with cp.dot() produces exception 'cupy.cuda.runtime.hostAlloc':
 ```python
import numpy as np
import cupy as cp

mp = cp.get_default_memory_pool()

n = 12000
A_cpu = np.random.rand(n, n).astype(np.float32)
B_cpu = np.random.rand(n, n).astype(np.float32)

max_iter = 5
for i in range(max_iter):
    A_gpu = cp.asarray(A_cpu)
    B_gpu = cp.asarray(B_cpu)
    C_gpu = cp.zeros((n, n), dtype=np.float32)
    cp.dot(A_gpu, B_gpu, out=C_gpu)
    print('iter {:d}/{:d}, memory: {:.2f} G'.format(i, max_iter - 1 , mp.used_bytes() / (2**30)))
```
Output is:
```
iter 0/4, memory: 1.61 G
iter 1/4, memory: 1.61 G
iter 2/4, memory: 1.61 G
iter 3/4, memory: 1.61 G
Traceback (most recent call last):
  File "D:/WST/projects/nuance/src-py/nuance/playground.py", line 13, in <module>
    B_gpu = cp.asarray(B_cpu)
  File "C:\Dev\Python\python-3.6\Lib\site-packages\cupy\creation\from_data.py", line 60, in asarray
    return core.array(a, dtype, False)
  File "cupy\core\core.pyx", line 2117, in cupy.core.core.array
  File "cupy\core\core.pyx", line 2157, in cupy.core.core.array
  File "cupy\cuda\pinned_memory.pyx", line 212, in cupy.cuda.pinned_memory.alloc_pinned_memory
  File "cupy\cuda\pinned_memory.pyx", line 286, in cupy.cuda.pinned_memory.PinnedMemoryPool.malloc
  File "cupy\cuda\pinned_memory.pyx", line 306, in cupy.cuda.pinned_memory.PinnedMemoryPool.malloc
  File "cupy\cuda\pinned_memory.pyx", line 303, in cupy.cuda.pinned_memory.PinnedMemoryPool.malloc
  File "cupy\cuda\pinned_memory.pyx", line 177, in cupy.cuda.pinned_memory._malloc
  File "cupy\cuda\pinned_memory.pyx", line 178, in cupy.cuda.pinned_memory._malloc
  File "cupy\cuda\pinned_memory.pyx", line 29, in cupy.cuda.pinned_memory.PinnedMemory.__init__
  File "cupy\cuda\runtime.pyx", line 229, in cupy.cuda.runtime.hostAlloc
  File "cupy\cuda\runtime.pyx", line 135, in cupy.cuda.runtime.check_status
cupy.cuda.runtime.CUDARuntimeError: cudaErrorLaunchTimeout: the launch timed out and was terminated
```

My environment is:
- Windows 10
- python 3.6.5
- cupy-cuda92 5.0.0b3

**Comment by kmaehashi** [comment]
Are you using GPU attached to display?
Please refer to https://developer.nvidia.com/cuda-faq#Programming
> Q: What is the maximum kernel execution time?

**Comment by alkalinin** [comment]
Answers are:
- I am using laptop with two graphics card: 'Intel Integrated' and 'NVidia GeForce GTX 960M (4 G)'. By default for displaying the 'Intel Integrated' is used. Probably 'GeForce' are using only for calculations.
- The new script is
```python
import numpy as np
import cupy as cp
import time

mp = cp.get_default_memory_pool()

n = 12000
A_cpu = np.random.rand(n, n).astype(np.float32)
B_cpu = np.random.rand(n, n).astype(np.float32)

max_iter = 5
for i in range(max_iter):
    t0 = time.time()
    A_gpu = cp.asarray(A_cpu)
    B_gpu = cp.asarray(B_cpu)
    C_gpu = cp.zeros((n, n), dtype=np.float32)
    cp.dot(A_gpu, B_gpu, out=C_gpu)
    t1 = time.time()

    print('iter {:d}/{:d}, memory: {:.2f} G, time: {:.3f} s'.format(i, max_iter - 1 , mp.used_bytes() / (2**30), t1 - t0))
```
The output is
```
C:\Dev\Python\python-3.6\python.exe D:/WST/projects/nuance/src-py/nuance/playground.py
iter 0/4, memory: 1.61 G, time: 1.827 s
iter 1/4, memory: 1.61 G, time: 0.186 s
iter 2/4, memory: 1.61 G, time: 0.670 s
iter 3/4, memory: 1.61 G, time: 0.654 s
Traceback (most recent call last):
  File "D:/WST/projects/nuance/src-py/nuance/playground.py", line 15, in <module>
    B_gpu = cp.asarray(B_cpu)
  File "C:\Dev\Python\python-3.6\Lib\site-packages\cupy\creation\from_data.py", line 60, in asarray
    return core.array(a, dtype, False)
```
The execution time is not more then 2 s < 5 s noted in the FAQ. 

Also we have exception in the 'B_gpu = cp.asarray(B_cpu)' line, not in the dot. Probably it is related not to the execution time.

**Comment by alkalinin** [comment]
I tried to debug situation with 'nvidia-smi'. I reduced the number of allocated memory for the array (N=12000 --> 8000). After that I can successfully run about 30 iteration (approximately after 30 iteration I have the same exception).

I found some strange behavior **only with 'dot' procedure**, see picture in the attachment. After all iteration script does not exist and is in waiting something. The memory load still about 60%. After approximately 5 s, the memory load becomes 0% and script is exiting.

It seems that there are some internal memory allocations during the dot procedure. But memory free procedure comes with big delay.

![image](https://user-images.githubusercontent.com/1408589/43311961-384c7166-918c-11e8-9fe4-c164a19d30f2.png)

**Comment by alkalinin** [comment]
And another finding, when I tried to run each iteration in individual process, everything works good:
```python
import numpy as np
import cupy as cp
import time
from multiprocessing import Process

def run():
    t0 = time.time()
    n = 12000
    A_cpu = np.random.rand(n, n).astype(np.float32)
    B_cpu = np.random.rand(n, n).astype(np.float32)

    A_gpu = cp.asarray(A_cpu)
    B_gpu = cp.asarray(B_cpu)
    C_gpu = cp.zeros((n, n), dtype=np.float32)
    cp.dot(A_gpu, B_gpu, out=C_gpu)
    t1 = time.time()
    print('    dot time: {:.3f} s'.format(t1 - t0))


def main():
    max_iter = 10
    for i in range(max_iter):
        print('iter {:d}/{:d}'.format(i, max_iter - 1))
        t0 = time.time()
        p = Process(target=run)
        p.start()
        p.join()
        t1 = time.time()
        print('    process time: {:.3f} s'.format(t1 - t0))


if __name__ == '__main__':
    main()
```
Output is:
```
iter 0/9
    dot time: 5.249 s
    process time: 8.613 s
iter 1/9
    dot time: 5.721 s
    process time: 9.002 s
iter 2/9
    dot time: 5.539 s
    process time: 8.864 s
iter 3/9
    dot time: 5.564 s
    process time: 8.952 s
iter 4/9
    dot time: 5.592 s
    process time: 9.150 s
iter 5/9
    dot time: 5.288 s
    process time: 10.719 s
iter 6/9
    dot time: 5.553 s
    process time: 9.526 s
iter 7/9
    dot time: 5.634 s
    process time: 9.247 s
iter 8/9
    dot time: 5.315 s
    process time: 8.834 s
iter 9/9
    dot time: 5.325 s
    process time: 8.588 s
```

Works good! Bur very slow. And we need to wait 3 s the end of process after dot procedure.

**Comment by alkalinin** [comment]
And finally I did try different functions, problems only in cp.dot:

Function | N | Results | Iterations
--- | --- | --- | ---
`cp.dot(A_gpu, B_gpu, out=C_gpu)` | 12000 | ERROR | 3/100
`cp.multiply(A_gpu, B_gpu, out=C_gpu)` | 12000 | SUCCESS | 100/100
`C_gpu = cp.linalg.inv(A_gpu)` | 12000 | SUCCESS | 100/100
`C_gpu = cp.sin(A_gpu * cp.cos(B_gpu))` | 12000 | SUCCESS | 100/100

(Sorry for large number of comments from my side tody, but I tried to debug the situation)

**Comment by w-m** [comment]
I believe your issue comes from asynchronous execution, not from a memory leak.

In every iteration, pinned host memory is allocated for a quick copy of A and B to the GPU. The dot computation is scheduled, but nothing is forcing the execution to finish. The next iteration starts before the GPU computations of the previous iteration finish. Copies of A_gpu and B_gpu on the host pile up until you run out of host memory.

See how the issue goes away if you either

- move the `A_gpu` and `B_gpu` copies out of the loop or
- force a synchronization at the end of the loop, e.g. by doing a `C_gpu[0, 0].get()`.

**Comment by kmaehashi** [comment]
> cupy.cuda.runtime.CUDARuntimeError: cudaErrorLaunchTimeout: the launch timed out and was terminated

Note that this error is not related to the memory pool at all, even if the stacktrace points to the memory pool. As the CUDA API reference says, CUDA runs asynchronously, and any API call may report error for the previous API calls.

https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY.html#group__CUDART__MEMORY_1gb65da58f444e7230d3322b6126bb4902
> Note:
> Note that this function may also return error codes from previous, asynchronous launches.

**Comment by alkalinin** [comment]
I agree, the error probably related to the asynchronous calls. But what how to wait until API call will be ready?

**Comment by kmaehashi** [comment]
> I am using laptop with two graphics card: 'Intel Integrated' and 'NVidia GeForce GTX 960M (4 G)'. By default for displaying the 'Intel Integrated' is used. Probably 'GeForce' are using only for calculations.

I still suspect this is a watchdog issue. In https://devtalk.nvidia.com/default/topic/991849/-solved-run-cuda-on-dedicated-nvidia-gpu-while-connecting-monitors-to-intel-hd-graphics-is-this-possible-/ NVIDIA says: `For optimus laptops, the situation is more complicated, and it may not be possible to use the devices separately, depending on the laptop design.`

> But what is right method to wait until API call will be ready?

You may try some of workarounds presented in https://stackoverflow.com/questions/27944441/how-to-avoid-cuda-error-6-launch-timeout-with-consecutive-asynchronous-kernel .

**Comment by alkalinin** [comment]
I little bit reduced `n` (size of array from 12000 down to 10000) and now workaround with `C_gpu[0, 0].get()`  is working!

So the problem is definitely with asynchronous calls and `C_gpu[0, 0].get()` line really allows to wait until API finished.

Thank you very much for the support!

**Comment by w-m** [comment]
> I still suspect this is a watchdog issue

Ah indeed, I missed that the error in the original report is a `cudaErrorLaunchTimeout`. Tried it locally and for some `n` and `max_iter`, my machine actually ran out of host memory, instead of throwing the error. I guess they're different effects, but have somewhat the same underlying cause (too many async unfinished operations).

**Comment by alkalinin** [comment]
My latest statistics with `n = 10000`. With `C_gpu[0, 0].get()` line I have 500 successful iterations
```
...
iter 494/499, memory: 1.12 G
iter 495/499, memory: 1.12 G
iter 496/499, memory: 1.12 G
iter 497/499, memory: 1.12 G
iter 498/499, memory: 1.12 G
iter 499/499, memory: 1.12 G

Process finished with exit code 0
```

For my practical tasks it is really works, for me problem is SOLVED!!!
