### ISSUE TITLE
ImportError with correctly installed CuPy

### ISSUE THREAD

**Issue by jo7ueb** [cupy/cupy#1790]
Hi, when I trying to import CuPy I got following error message.

```
[chainer-chemistry] [s1830001@vpcc] 380 % python -c 'import cupy'
Traceback (most recent call last):
  File "/home/s1830001/works/chainer-chemistry/lib/python3.7/site-packages/cupy/__init__.py", line 11, in <module>
    from cupy import core  # NOQA
  File "/home/s1830001/works/chainer-chemistry/lib/python3.7/site-packages/cupy/core/__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/s1830001/works/chainer-chemistry/lib/python3.7/site-packages/cupy/__init__.py", line 32, in <module>
    six.reraise(ImportError, ImportError(msg), exc_info[2])
  File "/home/s1830001/works/chainer-chemistry/lib/python3.7/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/home/s1830001/works/chainer-chemistry/lib/python3.7/site-packages/cupy/__init__.py", line 11, in <module>
    from cupy import core  # NOQA
  File "/home/s1830001/works/chainer-chemistry/lib/python3.7/site-packages/cupy/core/__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
ImportError: CuPy is not correctly installed.

If you are using wheel distribution (cupy-cudaXX), make sure that the version of CuPy you installed matches with the version of CUDA on your host.
Also, confirm that only one CuPy package is installed:
  $ pip freeze

If you are building CuPy from source, please check your environment, uninstall CuPy and reinstall it with:
  $ pip install cupy --no-cache-dir -vvvv

Check the Installation Guide for details:
  https://docs-cupy.chainer.org/en/latest/install.html

original error: libcuda.so.1: cannot open shared object file: No such file or directory
```

I installed cupy with `pip install cupy`.
`libcuda.so` lives in `/opt/cuda/9.1/lib64/stubs`
So I set `LD_LIBRARY_PATH` as follows
```
/home/s1830001/local/lib:/opt/cuda/9.1/lib64/stubs/:/home/s1830001/local/lib:/opt/cuda/9.1/lib64:/usr/local/lib:/opt/intel/itac/2018.1.017/intel64/slib:/opt/intel/compilers_and_libraries_2018.1.163/linux/compiler/lib/intel64:/opt/intel/compilers_and_libraries_2018.1.163/linux/mpi/intel64/lib:/opt/intel/compilers_and_libraries_2018.1.163/linux/mpi/mic/lib:/opt/intel/compilers_and_libraries_2018.1.163/linux/ipp/lib/intel64:/opt/intel/compilers_and_libraries_2018.1.163/linux/compiler/lib/intel64_lin:/opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64_lin:/opt/intel/compilers_and_libraries_2018.1.163/linux/tbb/lib/intel64/gcc4.7:/opt/intel/debugger_2018/iga/lib:/opt/intel/debugger_2018/libipt/intel64/lib:/opt/intel/compilers_and_libraries_2018.1.163/linux/daal/lib/intel64_lin
```

There's existing `libcuda.so` but chainer searches `libcuda.so.1`, causing this problem.
Why non-existing `libcuda.so.1` is linked to CuPy?
How to fix this problem?

Thanks.

**Comment by jo7ueb** [comment]
`ln -s /opt/cuda/9.1/lib64/stubs/libcuda.so $HOME/local/lib/libcuda.so.1` fixes this problem, but it's not smart solution.

**Comment by kmaehashi** [comment]
These three things are orthogonal:

1. Have CUDA GPU hardware on host
2. Have CUDA Driver software installed
3. Have CUDA Runtime software installed

Currently CuPy requires 2 and 3. #1781 tries to mitigate it to only require 3.

I'm interested in the use-case of @jo7ueb's environment that don't have 2.

**Comment by fiarabbit** [comment]
@kmaehashi 
Thanks for the reply. OK, I now understood that @jo7ueb 's `libcuda.so` is just a stub, not the valid driver software.
I'm very sorry over the trouble, and appreciate your kind reply. Thanks!

**Comment by kmaehashi** [comment]
@jo7ueb As this is not a bug but an environment problem, I'll close this issue. Please use the Forum ([en](https://groups.google.com/forum/#!forum/cupy), [ja](https://groups.google.com/forum/#!forum/cupy-ja)) if you need further assistance.

**Comment by dweemx** [comment]
Got it solved by installing the NVIDIA GPU Driver. For Ubuntu 18.04 and CUDA 11.1:

```
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-ubuntu1804.pin
mv cuda-ubuntu1804.pin /etc/apt/preferences.d/cuda-repository-pin-600
wget https://developer.download.nvidia.com/compute/cuda/11.1.1/local_installers/cuda-repo-ubuntu1804-11-1-local_11.1.1-455.32.00-1_amd64.deb
dpkg -i cuda-repo-ubuntu1804-11-1-local_11.1.1-455.32.00-1_amd64.deb
apt-key add /var/cuda-repo-ubuntu1804-11-1-local/7fa2af80.pub
apt-get update
apt-get -y install nvidia-driver-450
```
