### ISSUE TITLE
cupy.cuda.memory.OutOfMemoryError: out of memory to allocate

### ISSUE THREAD

**Issue by agangzz** [cupy/cupy#1912]
when I use chainer, I run into the problem, such as 
"cupy.cuda.memory.OutOfMemoryError: out of memory to allocate 1073741824 bytes (total 12373894656 bytes)"

PS: my GPU has 12G memory, and the allocated memory is only 1G

**Comment by PeterHuang2015** [comment]
Bro, could u please see the GPU usage by `nvidia-smi` to see how much has been occupied already? BTW, you manually malloc or was loading a model by chainer?

**Comment by okuta** [comment]
I fixed. Chainer and CuPy memory leak bug. Could you try latest master or v5 branch? 
 chainer/chainer#5621

**Comment by okuta** [comment]
@agangzz Is the problem solved?

**Comment by kpespinosa** [comment]
Hi, I encountered the same problem:
cupy.cuda.memory.OutOfMemoryError: out of memory to allocate 250092544 bytes (total 10824923136 bytes)

My RAM is 31gb.

Chainer and cupy versions are:
Name: chainer
Version: 5.3.0
Summary: A flexible framework of neural networks
Home-page: https://chainer.org/
Author: Seiya Tokui
Author-email: tokui@preferred.jp
License: MIT License
Location: /usr/local/lib/python3.6/dist-packages
Requires: protobuf, cupy-cuda91, numpy, six, filelock
Required-by:

Name: cupy-cuda91
Version: 5.3.0
Summary: CuPy: NumPy-like API accelerated with CUDA
Home-page: https://docs-cupy.chainer.org/
Author: Seiya Tokui
Author-email: tokui@preferred.jp
License: MIT License
Location: /home/sunhil/.local/lib/python3.6/site-packages
Requires: fastrlock, numpy, six
Required-by: chainer

Does anyone know how to resolve this?

Cheers, 
Kurt

**Comment by cc20002002** [comment]
No, It is not solve. I am using cupy with cuda 10.0 
Run a code in spyder,
    t1=time.time()
    NN = x.size
    x = cp.asarray(x/h)
    y = cp.asarray(y)
    XX=cp.broadcast_to(x,(NN,NN))
    XXT=cp.broadcast_to(x.T,(NN,NN))
    xx = cp.absolute(XX-XXT)
    xx2 = cp.copy(xx)
    xx[xx2<1] = 70/81*(1-xx[xx<1]**3)**3
    xx[xx2>=1] = 0
    del xx2

    
    yy = y<=y.T
    
    kk = xx*cp.asarray(uniquexy[0].values)
    weight = kk/kk.sum(0,keepdims =True)
    cdf = (weight*yy).sum(0,keepdims =True).T

I can run the code line by line interactively.
Running the the code in a chunk produce this error
Traceback (most recent call last):

  File "<ipython-input-312-a9ef027e2a7b>", line 7, in <module>
    xx = cp.absolute(XX-XXT)

  File "cupy/core/_kernel.pyx", line 831, in cupy.core._kernel.ufunc.__call__

  File "cupy/core/_kernel.pyx", line 339, in cupy.core._kernel._get_out_args

  File "cupy/core/core.pyx", line 134, in cupy.core.core.ndarray.__init__

  File "cupy/cuda/memory.pyx", line 518, in cupy.cuda.memory.alloc

  File "cupy/cuda/memory.pyx", line 1085, in cupy.cuda.memory.MemoryPool.malloc

  File "cupy/cuda/memory.pyx", line 1106, in cupy.cuda.memory.MemoryPool.malloc

  File "cupy/cuda/memory.pyx", line 934, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc

  File "cupy/cuda/memory.pyx", line 949, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc

  File "cupy/cuda/memory.pyx", line 697, in cupy.cuda.memory._try_malloc

OutOfMemoryError: out of memory to allocate 5878749696 bytes (total 30164646912 bytes)

**Comment by anonymouslycn** [comment]
So do I...out of memory to allocate 75497472 bytes (total 1280286720 bytes)

**Comment by okuta** [comment]
@cc20002002 Could you share whole code?

And, you can know memory usage by following code. I think it's useful for debugging.

`cupy.get_default_memory_pool().used_bytes()`

**Comment by mrgransky** [comment]
```
import cupy as cp
pool = cp.cuda.MemoryPool(cp.cuda.malloc_managed)
cp.cuda.set_allocator(pool.malloc)

def dist_gpu(Ref, Query):
	d = cp.linalg.norm(Ref[:, None, :] - Query[None, :,  :], axis=2)
	d = cp.transpose(d)
	sorted_d = cp.sort(d)
	sorted_ind = cp.argsort(d)
	return sorted_d, sorted_ind

def compare_dist_methods():
	r,c = 1000, 320
	rnd_t = time.time()
	qu = cp.random.rand(r, c)
	rf = cp.random.rand(r, c)
	print('RND time: {} [s]\t'.format(time.time()-rnd_t))

	gpu_t = time.time()
	d_gpu, ix_gpu = dist_gpu(rf, qu)
	print('GPU time: {:.4f} s'.format(time.time()-gpu_t))
	
	print ('-'*90)
	print ('\n{:^90}\n'.format('GPU-L2 NORM')) 
	print ('dist:\n{}\nidx:\n{}\n'.format(d_gpu[:5,:5], ix_gpu[:5,:5]))
	
if __name__ == "__main__":
	print('Default Memory: {}'.format(cp.get_default_memory_pool().used_bytes()))
	compare_dist_methods()
```

My result:

```
Default Memory: 0
RND time: 0.394953966141 [s]
Traceback (most recent call last):
  File "prc.py", line 159, in <module>
    compare_dist_methods()
  File "prc.py", line 148, in compare_dist_methods
    d_gpu, ix_gpu = dist_gpu(rf, qu)
  File "prc.py", line 61, in dist_gpu
    d = cp.linalg.norm(Ref[:, None, :] - Query[None, :,  :], axis=2)
  File "/usr/local/lib/python2.7/dist-packages/cupy/linalg/norms.py", line 79, in norm
    s = (x.conj() * x).real
  File "cupy/core/core.pyx", line 940, in cupy.core.core.ndarray.__mul__
  File "cupy/core/_kernel.pyx", line 849, in cupy.core._kernel.ufunc.__call__
  File "cupy/core/_kernel.pyx", line 339, in cupy.core._kernel._get_out_args
  File "cupy/core/core.pyx", line 134, in cupy.core.core.ndarray.__init__
  File "cupy/cuda/memory.pyx", line 528, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1095, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1116, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 944, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 959, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 707, in cupy.cuda.memory._try_malloc
cupy.cuda.memory.OutOfMemoryError: out of memory to allocate 2560000000 bytes (total 5125120000 bytes)
```
and `$ nvidia-smi` :
```
Mon Mar 30 14:22:39 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro M1200        Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   38C    P0    N/A /  N/A |    376MiB /  4042MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1337      G   /usr/lib/xorg/Xorg                           168MiB |
|    0      2508      G   compiz                                       126MiB |
|    0      2910      G   ...uest-channel-token=12478664420534817039    26MiB |
|    0      4030      G   ...uest-channel-token=15166485567368656981    50MiB |
+-----------------------------------------------------------------------------+
```

**Comment by okuta** [comment]
I tested your code @mrgransky. It requires 5GB GPU memory.
Maybe your GPU doesn't support Unified Memory.

BTW, I will try to reduce memory consumption in `cupy.norm` function.

**Comment by mrgransky** [comment]
which command shows memory consumption of GPU memory?
How to realize if GPU support unified memory or not?

**Comment by asi1024** [comment]
@mrgransky The shape of temporary float64 ndarray `Ref[:, None, :] - Query[None, :,  :]` is `(1000, 1000, 320)`, so it requires 2.56GB. We can avoid it by using [ReductionKernel](https://docs-cupy.chainer.org/en/stable/tutorial/kernel.html#reduction-kernels) for `norm(x1 - x2)` as follows:
```py
subtract_norm = cp.ReductionKernel(
    'T x1, T x2', 'T y',
    '(x1 - x2) * (x1 - x2)',  # pre-reduction map
    'a + b',  # reduce
    'y = sqrt(a)',  # post-reduction map
    '0',  # identity value
)


def dist_gpu(Ref, Query):
    d = subtract_norm(Ref[:, None, :], Query[None, :,  :], axis=2)
    d = cp.transpose(d)
    sorted_d = cp.sort(d)
    sorted_ind = cp.argsort(d)
    return sorted_d, sorted_ind
```
Could you try it?

**Comment by mrgransky** [comment]
The problem, as @asi1024 mentioned, is `float64` cuz when I changed  `dtype='float32'`, it works with my 4GB GPU memory!

A second alternative `cp.ReductionKernel` also does the trick with `float64`, tnx dude! :+1: 

```
import cupy as cp
def dist_gpu(Ref, Query):
	d = cp.linalg.norm(Ref[:, None, :] - Query[None, :,  :], axis=2)
	d = cp.transpose(d)
	sorted_d = cp.sort(d)
	sorted_ind = cp.argsort(d)
	return sorted_d, sorted_ind

def dist_method():
	r,c = 1000, 320
	rnd_t = time.time()
	#rf, qu = cp.random.rand(r, c), cp.random.rand(r, c) # Memory Error!
	rf, qu = cp.random.rand(r, c, dtype='float32'), cp.random.rand(r, c, dtype='float32') # Works!
	
	print('RND time: {} [s]\t'.format(time.time()-rnd_t))
	print('Expecting {} GB of GPU memory!'.format(rf.nbytes*1e-6)) #2.56 GB required!!
	gpu_t = time.time()
	d_gpu, ix_gpu = dist_gpu(rf, qu)
	print('GPU time: {:.4f} s'.format(time.time()-gpu_t))
	
	print ('-'*90)
	print ('\n{:^90}\n'.format('GPU-L2 NORM')) 
	print ('dist:\n{}\nidx:\n{}\n'.format(d_gpu[:5,:5], ix_gpu[:5,:5]))

if __name__ == "__main__":
	clear_terminal()
	dist_method()
```
**Question:**
1. is `print('Expecting {} GB of GPU memory!'.format(rf.nbytes*1e-6))` always a correct way to obtain how much my ndarray demands to execute ? shouldn't it be rather `rf.nbytes*1e-9` ?

**Comment by mrgransky** [comment]
If I increase `r,c = 3450, 100000`, then this time `rf, qu = cp.random.rand(r, c), cp.random.rand(r, c)` gives me memory error:

```
Traceback (most recent call last):
  File "prc.py", line 175, in <module>
    dist_method()
  File "prc.py", line 122, in dist_method
    rf, qu = cp.random.rand(r, c), cp.random.rand(r, c)
  File "/usr/local/lib/python2.7/dist-packages/cupy/random/sample.py", line 47, in rand
    return random_sample(size=size, dtype=dtype)
  File "/usr/local/lib/python2.7/dist-packages/cupy/random/sample.py", line 161, in random_sample
    return rs.random_sample(size=size, dtype=dtype)
  File "/usr/local/lib/python2.7/dist-packages/cupy/random/generator.py", line 542, in random_sample
    out = self._random_sample_raw(size, dtype)
  File "/usr/local/lib/python2.7/dist-packages/cupy/random/generator.py", line 525, in _random_sample_raw
    out = cupy.empty(size, dtype=dtype)
  File "/usr/local/lib/python2.7/dist-packages/cupy/creation/basic.py", line 22, in empty
    return cupy.ndarray(shape, dtype, order=order)
  File "cupy/core/core.pyx", line 134, in cupy.core.core.ndarray.__init__
  File "cupy/cuda/memory.pyx", line 528, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1095, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1116, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 944, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 959, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 707, in cupy.cuda.memory._try_malloc
cupy.cuda.memory.OutOfMemoryError: out of memory to allocate 2760000000 bytes (total 5520000000 bytes)
```
But `rf, qu = cp.random.rand(r, c, dtype='float32'), cp.random.rand(r, c, dtype='float32')` works well!

**Comment by asi1024** [comment]
@mrgransky 
1. `rf.nbytes*1e-9` is correct. The shape of `rf` is `(1000, 320)`, so it costs only 320MB. It is not critical for your memory limits.
2. If you increase `r,c = 3450, 100000`, the total size of `rf` and `qu` is 5.52GB. So this `OutOfMemoryError` is expected behavior.

**Comment by mrgransky** [comment]
how do u get `5.52 GB`?
My calculation is as follows:
for `float64`: `3450 x 100000 x 8 x 1e-9 = 2.76 GB`  
and 
for `float32`: `3450 x 100000 x 4 x 1e-9 = 1.38 GB` 
or am I making a mistake somewhere? even `numpy.ndarray.nbytes` verifies my result!

**Comment by asi1024** [comment]
The _total_ size of `rf` and `qu` is 5.52GB.

**Comment by mrgransky** [comment]
aaahhh u're right! sorry mate for asking such ridiculous questions! 

Is there anyway to release the memory after assigning each individual array?
```
rf = cp.random.rand(r, c)
print('rf done ') # kinda release memory!????
qu = cp.random.rand(r, c)
print('qu done ') # kinda release memory!????
```

**Comment by asi1024** [comment]
`del rf` releases its memory to the memory pool.

**Comment by asi1024** [comment]
Let's close this, feel free to reopen it if needed.
