### ISSUE TITLE
Representation of size-0 arrays in __cuda_array_interface__

### ISSUE THREAD

**Issue by TomAugspurger** [cupy/cupy#2104]
I have a design question about `__cuda_array_interface__`. How (if at all) should size-0 arrays be represented? In cupy, the data field currently uses `0` as the `int_ptr`.

```python
In [7]: import cupy

In [8]: arr = cupy.random.random(0)

In [9]: arr.__cuda_array_interface__
Out[9]:
{'shape': (0,),
 'typestr': '<f8',
 'descr': [('', '<f8')],
 'data': (0, False),
 'version': 0}
```

Compare with numba, which uses `None`

```python
In [10]: import numba.cuda

In [11]: numba.cuda.device_array(0).__cuda_array_interface__
Out[11]:
{'shape': (0,),
 'strides': (8,),
 'data': (None, False),
 'typestr': '<f8',
 'version': 0}
```

Currently, cupy doesn't round-trip a size-0 array

```python
In [12]: class Dummy:
    ...:     def __init__(self, descr):
    ...:         self.__cuda_array_interface__ = descr
    ...:

In [13]: obj = Dummy(arr.__cuda_array_interface__)

In [14]: cupy.asarray(obj)
```
```pytb
---------------------------------------------------------------------------
CUDARuntimeError                          Traceback (most recent call last)
<ipython-input-14-306044f096f0> in <module>
----> 1 cupy.asarray(obj)

~/miniconda3/lib/python3.6/site-packages/cupy/creation/from_data.py in asarray(a, dtype, order)
     84     """
     85     if not isinstance(a, ndarray) and hasattr(a, '__cuda_array_interface__'):
---> 86         return _convert_object_with_cuda_array_interface(a)
     87     return core.array(a, dtype, False, order)
     88

~/miniconda3/lib/python3.6/site-packages/cupy/creation/from_data.py in _convert_object_with_cuda_array_interface(a)
     56         strides = None
     57         nbytes = numpy.prod(shape) * dtype.itemsize
---> 58     mem = memory.UnownedMemory(desc['data'][0], nbytes, a)
     59     memptr = memory.MemoryPointer(mem, 0)
     60     return ndarray(shape, dtype=dtype, memptr=memptr, strides=strides)

cupy/cuda/memory.pyx in cupy.cuda.memory.UnownedMemory.__init__()

cupy/cuda/runtime.pyx in cupy.cuda.runtime.pointerGetAttributes()

cupy/cuda/runtime.pyx in cupy.cuda.runtime.check_status()

CUDARuntimeError: cudaErrorInvalidValue: invalid argument
```

Info:

```
In [6]:  cupy.show_config()
CuPy Version          : 6.0.0b3
CUDA Root             : /usr/local/cuda-10.0
CUDA Build Version    : 9020
CUDA Driver Version   : 9020
CUDA Runtime Version  : 9020
cuDNN Build Version   : 7402
cuDNN Version         : 7402
NCCL Build Version    : 2307
NCCL Runtime Version  : 2307
```

cc @sklam @seibert for the numba side of things.

**Comment by TomAugspurger** [comment]
For reference, NumPy's behavior (not that it necessarily makes sense for cupy or numba)

```python
In [9]: np.random.random(0).__array_interface__
Out[9]:
{'data': (93898734676736, False),
 'strides': None,
 'descr': [('', '<f8')],
 'typestr': '<f8',
 'shape': (0,),
 'version': 3}
```

**Comment by kmaehashi** [comment]
Currently CuPy automatically determines which device the memory (pointed by `data`) resides. However if the pointer is NULL, it cannot be determined and raises an error you mentioned.
I think it's better to use the current device if the pointer is NULL.
https://github.com/cupy/cupy/blob/9d8a0d2ad90ad1cc50eebec754452d55c692072b/cupy/cuda/memory.pyx#L103-L105

**Comment by jakirkham** [comment]
cc @seibert

**Comment by RemiLehe** [comment]
As mentioned [here](https://github.com/cupy/cupy/issues/2104), the above question on the representation of size-0 arrays does have an impact on interoperability between `numba` and `cupy`: currently, passing a size-0 `cupy` array to a `numba` GPU kernel will result in a raised exception.

**Comment by leofang** [comment]
Just trying to follow up: as I raised in numba/numba#4175, Numba's way of representing a 0-size array with `__cuda_array_interface__['data'][0] = None` is not complying with the standard they proposed, which requires an `int`. This should be considered a bug on the Numba side, not CuPy.

**Comment by leofang** [comment]
This issue is resolved by #2491. The new v2 protocol specifies that the pointer to 0-size arrays should be `0`.

**Comment by jakirkham** [comment]
Indeed. Thanks for doing that @leofang! 😄

@TomAugspurger, happy to close?

**Comment by TomAugspurger** [comment]
Yep, I think so. Thanks!
