### ISSUE TITLE
cupy in conda reports ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by we-taper** [cupy/cupy#2110]
Cupy installed from anaconda (`conda install cupy`) is reporting that it could not load the correct cuda library. It happens when I `import cupy`.

**Comment by epifanio** [comment]
can't replicate this. I just installed a fresh Anaconda3 on linux, then `conda install cudatoolkit` and `conda install cupy`. then `import cupy` doesn't give errors

**Comment by we-taper** [comment]
@epifanio That is interesting. I encountered this on my home machine with a freshly installed Ubuntu. I have previously install CUDA 10 to `/usr/local/`, which is required to compile some other applications. Then I installed cupy via conda, and I found this error. 

I figured out that I could solve this problem by simply installing an additional CUDA 9 to `/usr/local` and explicitly `export PATH` and `export LD_LIBRARY_PATH` to this new CUDA 9. I thought that Conda managed its own version of Cuda but here it seems that it is not the case.

**Comment by we-taper** [comment]
I have found a solution but I am not sure why it is working. 

I found that `conda` installed `cudatoolkit=9.2` because I did `conda install tensorflow-gpu` previously. However, if I downgrade cudatoolkit to 9.0 (`conda install cudatoolkit=9.0`), and then install cupy by `conda install cupy`, it worked!

**Comment by kmaehashi** [comment]
Dependency declaration of [CuPy packages on Anaconda](https://anaconda.org/anaconda/cupy/files) seems broken. I'll contact Anaconda team to address this issue.

When you install `cudatoolkit=9.2`, CuPy built for CUDA 9.0 will be installed instead of CuPy built for CUDA 9.2. This will cause the error you mentioned in the issue title.

* Dependency of `cupy-5.1.0-py37h062aff8_0` (for CUDA 8.0):
`"cudatoolkit >=8.0,<9.0a0"` (correct)

* Dependency of `cupy-5.1.0-py37h686fdb1_0` (for CUDA 9.0):
`"cudatoolkit >=9.0,<10.0a0"` (**incorrect**; should be `"cudatoolkit >=9.0,<9.1a0"`)

* Dependency of `cupy-5.1.0-py37hc15394e_0` (for CUDA 9.2):
`"cudatoolkit >=9.2,<10.0a0"` (correct)

* Dependency of `cupy-5.1.0-py37hc0ce245_0` (for CUDA 10.0):
`"cudatoolkit >=10.0.130,<11.0a0"` (**incorrect**; should be `"cudatoolkit >=10.0.130,<10.1a0"`)
(Currently it is working because Anaconda does not provide CUDA 10.1 package yet.)

**Comment by jjhelmus** [comment]
I have modified the dependency information of the cupy packages to correct the cudatoolkit maximum version.  New installs with conda should get the corrected information.

**Comment by kmaehashi** [comment]
@jjhelmus Thank you for your support!

**Comment by kmaehashi** [comment]
Closing as I confirmed that the issue has resolved.

**Comment by PovelikinRostislav** [comment]
I met the same issue.
`conda install -c anaconda cupy` produces 

> ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory

during `import cupy`

The command installed `cudatoolkit-10.1.168` and `cupy-6.0.0`

**Comment by PovelikinRostislav** [comment]
`conda install cudatoolkit=9.0` helped me too.
thanks @we-taper

**Comment by kmaehashi** [comment]
@jjhelmus It seems the above error is happening again. Could you fix the dependency information?

**Comment by jjhelmus** [comment]
Please do not use the `anaconda` channel to install these (or any) packages.  The same packages are available with corrected dependencies via the `defaults` channel.

**Comment by PovelikinRostislav** [comment]
@jjhelmus, could you explain why it 's not relevant to use `anaconda` channel for 

> these (or any) packages

?

Thanks in advance

**Comment by jjhelmus** [comment]
Packages from Anaconda, Inc are provided at repo.anaconda.com.  In conda these are available through the `defaults` channel.  Occasionally we find error in the dependency information in these packages and update them. 

These packages are mirrored into the `anaconda` channel on Anaconda cloud, anaconda.org.  The packages in the `anaconda` channel are not updated with these corrections to the dependency information.  Therefore if you install from the `anaconda` channel conda will use incorrect dependency information.  This is why I recommend against installing from the `anaconda` channel.

In the case of your error the missing file was `libcudart.so.10.0`.  This library comes from NVIDIA driver and must be provided by your system.  The `cudatoolkit` package does not provide this.  If you updated your driver to the latest release you should be able to use `cudatoolkit` 10.

**Comment by kmaehashi** [comment]
@jjhelmus Thanks for the detailed explanation! I confirmed that the dependency information is correct in CuPy packages on the `default` channel; it instead raises an  `UnsatisfiableError` because `cupy` (and `nccl`) package for CUDA 10.1 is not yet available in anaconda.

> In the case of your error the missing file was `libcudart.so.10.0`.  This library comes from NVIDIA driver and must be provided by your system.  The `cudatoolkit` package does not provide this.  If you updated your driver to the latest release you should be able to use `cudatoolkit` 10.

`cudatoolkit` package provides `libcudart.so.10.0` (files listed below), as it is a part of CUDA Toolkit;  (NVIDIA driver provides `libcuda.so.*`, which is not available through the package).
```
libcudart.so -> libcudart.so.10.0.130 (symlink)
libcudart.so.10.0 -> libcudart.so.10.0.130 (symlink)
libcudart.so.10.0.130
```

@PovelikinRostislav Please use `conda install cupy`  (without `-c anaconda`) and CUDA 10.0 or earlier for now.
