### ISSUE TITLE
TypeError for OutOfMemoryError

### ISSUE THREAD

**Issue by kcghost** [cupy/cupy#2301]
Seen while using chainer while multiprocessing and using the GPU:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 463, in _handle_results
    task = get()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
  File "cupy/cuda/memory.pyx", line 37, in cupy.cuda.memory.OutOfMemoryError.__init__
TypeError: __init__() takes exactly 3 positional arguments (2 given)
```
Seems like it tried to raise an OutOfMemoryError but failed to do so.

```
CuPy Version          : 6.1.0
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 10010
CUDA Driver Version   : 10010
CUDA Runtime Version  : 10010
cuDNN Build Version   : 7500
cuDNN Version         : 7500
NCCL Build Version    : 2402
NCCL Runtime Version  : 2402
```

**Comment by kmaehashi** [comment]
Thanks for raising the issue! We recently received the similar report and looking into it. https://stackoverflow.com/questions/56753355/in-windows-envs-cupy-get-error-in-multithread-pool-if-gpu-already-used-even-if

* What platform are you on? (Ubuntu, Windows, etc)
* Did you installed CuPy using wheel (cupy-cudaXXX), or built from source? In the latter case, what is your Cython version?

**Comment by kcghost** [comment]
Ubuntu 18.04, installed using wheel (cupy-cuda101). NVIDIA GTX 1060 with 3GB memory. Like the stackoverflow issue, I am using 'spawn' launch method, though I think I saw the same error when using fork; I thought using spawn would help resolve it.

Output of `nvidia-smi`:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  On   | 00000000:01:00.0 Off |                  N/A |
|  0%   43C    P2    27W / 120W |   1401MiB /  3018MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0       896      G   /usr/lib/xorg/Xorg                           120MiB |
|    0     25629      C   /usr/bin/python3                             531MiB |
|    0     25631      C   /usr/bin/python3                             745MiB |
+-----------------------------------------------------------------------------+
```
That is *not* while running the reproduction case, and therefore I just noticed that somehow some python processes stuck around claiming memory after the fact. Soooo, huh. Just gonna `killall python3` real quick.

If it helps, I am calling into [waifu2x-chainer](https://github.com/tsurumeso/waifu2x-chainer) and doing a lot of image scaling and processing.

I don't have a *minimized* reproduction case, but I can reproduce the error pretty consistently; and it is code that I planned on making public soon. So if you need a reproduction case let me know and I can push it up. That is if you don't mind dealing with some specific project upscaling Doom sprites.

I also saw that if you catch the exception in the process and print it, it seems fine, insofar as it prints the right exception anyway:
`out of memory to allocate 50466816 bytes (total 223895040 bytes)`
The exception problem only occurs if you let it bubble up out of the process.

There are really two issues:
1. An out of memory exception occurs at all. But that might just be because I am flying too close to the sun trying to batch process too many things at once. Even so I had hoped it would block until there was memory available or something.
2. The exception itself is not handled well when multiprocessing.

**Comment by kmaehashi** [comment]
@kcghost Thanks for the information! I could reproduce the error; the root cause was that some exceptions defined in CuPy does not support pickle protocol and thus exceptions raised in a subprocess (which is pickled in the subprocess) fail to be un-pickled in the parent process.
