### ISSUE TITLE
cupy.cuda.memory.OutOfMemoryError

### ISSUE THREAD

**Issue by hassanrazakhalid** [cupy/cupy#2537]
Thank you for using and contributing to CuPy!

If your issue is a **request for support in using CuPy**, please post it on [Stack Overflow](https://stackoverflow.com/questions/tagged/cupy) or Google Groups ([en](https://groups.google.com/forum/#!forum/cupy) / [ja](https://groups.google.com/forum/#!forum/cupy-ja)).
Developer team members are monitoring questions on these channels.

If it is a bug report, please include the following information:

* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
  - CuPy version 7.0.0b4
  - OS/Platform ubuntu 18
  - CUDA version 10.0
  - cuDNN/NCCL version (if applicable)
* Code to reproduce
while using chainer 7.0.0b4. i'm getting following exception. it seems to be reappeared agaun
* Error messages, stack traces, or logs
Exception in main training loop: Out of memory allocating 25,600,000 bytes (allocated so far: 3,635,267,072 bytes).
Traceback (most recent call last):
  File "/home/hassan/miniconda3/envs/potrait_matting/lib/python3.5/site-packages/chainer/training/trainer.py", line 343, in run
    update()
  File "/home/hassan/miniconda3/envs/potrait_matting/lib/python3.5/site-packages/chainer/training/updaters/standard_updater.py", line 235, in update
    self.update_core()
  File "/home/hassan/miniconda3/envs/potrait_matting/lib/python3.5/site-packages/chainer/training/updaters/standard_updater.py", line 248, in update_core
    optimizer.update(loss_func, *in_arrays)
  File "/home/hassan/miniconda3/envs/potrait_matting/lib/python3.5/site-packages/chainer/optimizer.py", line 864, in update
    loss = lossfun(*args, **kwds)
  File "/home/hassan/python-workspace/portrait_matting/scripts/models/fcn8s.py", line 79, in __call__
    score = self.forward(x)
  File "/home/hassan/python-workspace/portrait_matting/scripts/models/fcn8s.py", line 127, in forward
    h = F.relu(self.conv4_3(h))
  File "/home/hassan/miniconda3/envs/potrait_matting/lib/python3.5/site-packages/chainer/functions/activation/relu.py", line 162, in relu
    y, = ReLU().apply((x,))
  File "/home/hassan/miniconda3/envs/potrait_matting/lib/python3.5/site-packages/chainer/function_node.py", line 325, in apply
    outputs = self.forward(in_data)
  File "/home/hassan/miniconda3/envs/potrait_matting/lib/python3.5/site-packages/chainer/function_node.py", line 518, in forward
    return self.forward_gpu(inputs)
  File "/home/hassan/miniconda3/envs/potrait_matting/lib/python3.5/site-packages/chainer/functions/activation/relu.py", line 55, in forward_gpu
    y = cudnn.activation_forward(x, _mode)
  File "cupy/cudnn.pyx", line 618, in cupy.cudnn.activation_forward
  File "cupy/core/core.pyx", line 134, in cupy.core.core.ndarray.__init__
  File "cupy/cuda/memory.pyx", line 540, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1186, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1207, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 994, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1009, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 743, in cupy.cuda.memory._try_malloc
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "scripts/train.py", line 270, in <module>
    main(sys.argv[1:])
  File "scripts/train.py", line 266, in main
    trainer.run()
  File "/home/hassan/miniconda3/envs/potrait_matting/lib/python3.5/site-packages/chainer/training/trainer.py", line 376, in run
    six.reraise(*exc_info)
  File "/home/hassan/miniconda3/envs/potrait_matting/lib/python3.5/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/hassan/miniconda3/envs/potrait_matting/lib/python3.5/site-packages/chainer/training/trainer.py", line 343, in run
    update()
  File "/home/hassan/miniconda3/envs/potrait_matting/lib/python3.5/site-packages/chainer/training/updaters/standard_updater.py", line 235, in update
    self.update_core()
  File "/home/hassan/miniconda3/envs/potrait_matting/lib/python3.5/site-packages/chainer/training/updaters/standard_updater.py", line 248, in update_core
    optimizer.update(loss_func, *in_arrays)
  File "/home/hassan/miniconda3/envs/potrait_matting/lib/python3.5/site-packages/chainer/optimizer.py", line 864, in update
    loss = lossfun(*args, **kwds)
  File "/home/hassan/python-workspace/portrait_matting/scripts/models/fcn8s.py", line 79, in __call__
    score = self.forward(x)
  File "/home/hassan/python-workspace/portrait_matting/scripts/models/fcn8s.py", line 127, in forward
    h = F.relu(self.conv4_3(h))
  File "/home/hassan/miniconda3/envs/potrait_matting/lib/python3.5/site-packages/chainer/functions/activation/relu.py", line 162, in relu
    y, = ReLU().apply((x,))
  File "/home/hassan/miniconda3/envs/potrait_matting/lib/python3.5/site-packages/chainer/function_node.py", line 325, in apply
    outputs = self.forward(in_data)
  File "/home/hassan/miniconda3/envs/potrait_matting/lib/python3.5/site-packages/chainer/function_node.py", line 518, in forward
    return self.forward_gpu(inputs)
  File "/home/hassan/miniconda3/envs/potrait_matting/lib/python3.5/site-packages/chainer/functions/activation/relu.py", line 55, in forward_gpu
    y = cudnn.activation_forward(x, _mode)
  File "cupy/cudnn.pyx", line 618, in cupy.cudnn.activation_forward
  File "cupy/core/core.pyx", line 134, in cupy.core.core.ndarray.__init__
  File "cupy/cuda/memory.pyx", line 540, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1186, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1207, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 994, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1009, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 743, in cupy.cuda.memory._try_malloc
cupy.cuda.memory.OutOfMemoryError: Out of memory allocating 25,600,000 bytes (allocated so far: 3,635,267,072 bytes).

**Comment by emcastillo** [comment]
Hello, thank you for the report.

Have you tried with the stable version?
If the error persist could it be related to the size of your training data?

**Comment by hassanrazakhalid** [comment]
yes i tried with version 6.4.0 of cupy and chainer and same issue, i'm not sure that it could be size of training data. Its works fine when using without GPU but training takes so much time approx 9 days.

**Comment by niboshi** [comment]
Did you check the actual memory consumption with nvidia-smi?
CUDA can internally occupy about 500MiB of GPU memory by just initializing a CUDA context.
It's possible that GPU memory was actually just exhausted.

**Comment by niboshi** [comment]
Thanks. Apparently GPU memory is actually full.

CuPy won't "automagically" swap-out unused data on GPU memory so that you could allocate more than physical GPU memory size.
It doesn't matter how calculation is done. Once memory is allocated, it occupies physical GPU memory, even while unused.
I don't know how you are handling the data, but most likely you would have to delay the data transfer (or GPU memory allocation) until actually used.

It's beyond the scope of CuPy issues. I suggest asking at stackoverflow.com.

**Comment by hassanrazakhalid** [comment]
right i was trying to run the following code with GPU by running train.py,
https://github.com/takiyu/portrait_matting

**Comment by niboshi** [comment]
As it is apparently not CuPy's problem, please ask at either StackOverflow or Chainer slack community.
For slack, you can follow a link in chainer README: https://github.com/chainer/chainer

Please reopen once it turns out to be a CuPy issue.
Thanks!
