### ISSUE TITLE
cudaErrorSystemNotReady: system not yet initialized

### ISSUE THREAD

**Issue by berceanu** [cupy/cupy#2845]
output of `python -c 'import cupy; cupy.show_config()'`:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/berceanu/miniconda3/envs/fbpic/lib/python3.7/site-packages/cupy/__init__.py", line 812, in show_config
    sys.stdout.write(str(_cupyx.get_runtime_info()))
  File "/home/berceanu/miniconda3/envs/fbpic/lib/python3.7/site-packages/cupyx/runtime.py", line 174, in get_runtime_info
    return _RuntimeInfo()
  File "/home/berceanu/miniconda3/envs/fbpic/lib/python3.7/site-packages/cupyx/runtime.py", line 107, in __init__
    cupy.cuda.cublas.CUBLASError)
  File "/home/berceanu/miniconda3/envs/fbpic/lib/python3.7/site-packages/cupyx/runtime.py", line 23, in _eval_or_error
    return func()
  File "/home/berceanu/miniconda3/envs/fbpic/lib/python3.7/site-packages/cupyx/runtime.py", line 106, in <lambda>
    cupy.cuda.device.get_cublas_handle()),
  File "cupy/cuda/device.pyx", line 44, in cupy.cuda.device.get_cublas_handle
  File "cupy/cuda/device.pyx", line 45, in cupy.cuda.device.get_cublas_handle
  File "cupy/cuda/device.pyx", line 27, in cupy.cuda.device._get_device
  File "cupy/cuda/runtime.pyx", line 229, in cupy.cuda.runtime.getDevice
  File "cupy/cuda/runtime.pyx", line 201, in cupy.cuda.runtime.check_status
cupy.cuda.runtime.CUDARuntimeError: cudaErrorSystemNotReady: system not yet initialized
```

* Conditions
  - OS/Platform: Ubuntu 16.04.6 LTS
  - CUDA version: 10.0, installed via `conda install cudatoolkit=10.0`
  - CuPy version: 7.0.0, installed via `pip install cupy-cuda100` in my conda env

`nvidia-smi` works properly, and shows ` NVIDIA-SMI 430.64       Driver Version: 430.64       CUDA Version: 10.1`

**Comment by emcastillo** [comment]
please install `cupy-cuda101`

**Comment by berceanu** [comment]
But then I also need to install cudatoolkit=10.1?

**Comment by emcastillo** [comment]
Sorry, I looked at the cuda version the driver supports instead the one you have installed.
your setup seems right.

Do you have the CUDA libraries in the LD_LIBRARY_PATH?
Also which GPU are you using?

Sorry again and thanks

**Comment by berceanu** [comment]
I didn't touch `LD_LIBRARY_PATH`, since I installed the cuda Toolkit via conda. I have gotten this setul to work on other systems, but this is a HGX-II node with 16 V100 GPUs. I dont know if its connected, but nvidia-smi takes about 30 seconds to display its output.

**Comment by emcastillo** [comment]
If nvidia-smi takes that long probably the driver may not be running in persistence mode.
I am unsure if it may be related but try to enable it if possible.

https://docs.nvidia.com/deploy/driver-persistence/index.html

**Comment by berceanu** [comment]
You're right, the driver was not running in persistence mode. That is now fixed, and nvidia-smi starts very quickly. Unfortunately the main problem still persists.

**Comment by emcastillo** [comment]
Can you try to set the `CUDA_PATH` environment var and reinstall cupy? cuda seems to be correctly working but maybe cupy is not detecting it somehow

**Comment by JordanCheney** [comment]
@berceanu I have the same problem, also on an HGX-II, were you able to find a solution?

**Comment by berceanu** [comment]
Unfortunately no solution yet.

**Comment by leofang** [comment]
Did you both install `cudatoolkit` from conda? Can you remove it and do `pip install cupy-cudaXXX` (which uses your local CUDA installation)? CuPy installed by `pip` is not compatible with `cudatoolkit`.

**Comment by JordanCheney** [comment]
@leofang I think there is a deeper issue with the GPU setup on my machine. I compiled the CUDA samples that come with the 10.2 installation and got the same error running those. I'll post back here if I find a solution

**Comment by berceanu** [comment]
Did you try https://www.supermicro.com/support/faqs/faq.cfm?faq=31029

**Comment by JordanCheney** [comment]
@berceanu I did, that changed the return code from an 802 to an 83 on my machine. 83 is not documented in the CUDA API so I'm not sure what that means. I opened an issue on the [developer forum](https://forums.developer.nvidia.com/t/system-not-initialized-returncodes-802-and-83/117818) that details everything I've tried.
