### ISSUE TITLE
Printing result from `.max()` errors

### ISSUE THREAD

**Issue by jakirkham** [cupy/cupy#3092]
Ran the following Python script using CuPy 7.2.0 and got an error. Note the `print` is what causes the error.

```python
import cupy

a = cupy.arange(5)
r = a.max()
print(r)
```

Exception:

```python
Traceback (most recent call last):
  File "test_cupy_repr.py", line 5, in <module>
    print(r)
  File "cupy/core/core.pyx", line 1366, in cupy.core.core.ndarray.__str__
  File "cupy/core/core.pyx", line 1456, in cupy.core.core.ndarray.get
  File "cupy/core/core.pyx", line 1462, in cupy.core.core.ndarray.get
  File "cupy/cuda/memory.pyx", line 449, in cupy.cuda.memory.MemoryPointer.copy_to_host
  File "cupy/cuda/runtime.pyx", line 378, in cupy.cuda.runtime.memcpy
  File "cupy/cuda/runtime.pyx", line 201, in cupy.cuda.runtime.check_status
cupy.cuda.runtime.CUDARuntimeError: cudaErrorIllegalAddress: an illegal memory access was encountered
```

Additional exception (during cleanup):

```python
Traceback (most recent call last):
  File "cupy/cuda/driver.pyx", line 247, in cupy.cuda.driver.moduleUnload
  File "cupy/cuda/driver.pyx", line 118, in cupy.cuda.driver.check_status
TypeError: 'NoneType' object is not callable
Exception ignored in: 'cupy.cuda.function.Module.__dealloc__'
Traceback (most recent call last):
  File "cupy/cuda/driver.pyx", line 247, in cupy.cuda.driver.moduleUnload
  File "cupy/cuda/driver.pyx", line 118, in cupy.cuda.driver.check_status
TypeError: 'NoneType' object is not callable
```

If it is a bug report, please include the following information:

* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
  - CuPy version: 7.2.0
  - OS/Platform: Ubuntu 16.04.5 LTS (Xenial)
  - CUDA version: 10.1.243
  - cuDNN/NCCL version (if applicable): 7.6.5/2.5.7.1
* Code to reproduce: (see above)
* Error messages, stack traces, or logs: (see above)

**Comment by jakirkham** [comment]
cc @JohnZed

**Comment by JohnZed** [comment]
@jakirkham note that if I build from source, I cannot repro this. It happens when I use the conda-forge conda package though.

**Comment by jakirkham** [comment]
Can you please share how you built it from source?

**Comment by JohnZed** [comment]
```
(cuml_dev) [jzedlewski-dt:~/anaconda3/envs/cuml_dev]$ python -c 'import cupy; cupy.show_config()'
CuPy Version          : 7.2.0
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 10000
CUDA Driver Version   : 10000
CUDA Runtime Version  : 10000
cuBLAS Version        : 10000
cuFFT Version         : 10000
cuRAND Version        : 10000
cuSOLVER Version      : (10, 0, 0)
cuSPARSE Version      : 10000
NVRTC Version         : (10, 0)
cuDNN Build Version   : 7005
cuDNN Version         : 7005
NCCL Build Version    : None
NCCL Runtime Version  : None

(cuml_dev) [jzedlewski-dt:~/anaconda3/envs/cuml_dev]$ python -c 'import cupy as cp; cp.arange(10).max()'
```

Numpy 1.18.1
Ubuntu 16.04 running on a Quadro P6000

**Comment by JohnZed** [comment]
I'd also say that this has to be a packaging incompatibility, because the brokenness is so extensive that no unit tests would pass with this issue in place.

**Comment by leofang** [comment]
1. Could you set `cupy.cuda.cub_enabled = False` and see if the error persists?
2. What is your `cudatoolkit` version (the one installed by conda, not from the system if any)

**Comment by leofang** [comment]
3. Could you try other reduction routines (sum, min, etc)?

**Comment by JohnZed** [comment]
Setting `cupy.cuda.cub_enabled = False` removes the issue!
Other reductions have the same behavior as max - failing on the conda build if cub_enabled == True but passing on the conda build if cub_enabled == False, while working on the from-source build.

CUDA toolkit here is 10.0, but a colleague with CUDA 10.2 has seen apparently the same issue.

**Comment by leofang** [comment]
What is the CUDA driver version installed on your system (outside the Fonda’s control)? You can copy and paste the output from nvidia-smi.

**Comment by JohnZed** [comment]
Driver 440.33.01

**Comment by leofang** [comment]
Could you uninstall CuPy from your conda env, do `conda install -c conda-forge cupy cudatoolkit=10.2`, and test again?

**Comment by JohnZed** [comment]
With that reinstall with cudatoolkit=10.2, the same issue occurs (crash when printing after reduction)

**Comment by leofang** [comment]
Thanks, John! I’ll look into this later tonight.

**Comment by leofang** [comment]
I can reproduce this with `conda install python=3.7 cupy=7.2.0 cudatoolkit=9.2`. Downgrading from 7.2.0 to 7.1.1 makes the error go away. I will try building from source tomorrow (it's 2:54am local time...)

@JohnZed For your information: 
> I'd also say that this has to be a packaging incompatibility, because the brokenness is so extensive that no unit tests would pass with this issue in place.

For now I am not sure. It's because the CUB module is not tested in CuPy's CIs. So, it could be either the v7 branch was contaminated between 7.1.1 and 7.2.0, or we (by which I mean I 😅) messed up in cupy-feedstock. 

As for why you didn't see this error when building from source: You need to set an env var `CUB_PATH` and point it to the CUB folder, otherwise the `cupy.cuda.cub` module would not be built. This is what I'm gonna test against the v7 branch tomorrow. 

@kmaehashi: This could be another CUB bug...

**Comment by leofang** [comment]
@jakirkham @JohnZed Sorry for my silence. Didn't have the expected bandwidth until today...I compiled from source and confirmed that something has changed between v7.1.1 and v7.2.0. This is not just a packaging bug in cupy-feedstock. However, by inspecting the diff I can't find any thing suspicious that would lead to a memory corruption. 

@kmaehashi @emcastillo Could you help investigate?

**Comment by leofang** [comment]
Proposed to disable the CUB support and rebuild the package on cupy-feedstock: conda-forge/cupy-feedstock#38.

**Comment by jakirkham** [comment]
@JohnZed, when you built this locally, did you build with CUB support? If not, could you please try that as well? We're curious to know if that is the issue or if it is something else 🙂

**Comment by JohnZed** [comment]
I did not build with cub. Also, when I disabled cub in the conda build, things started working again. I'll be able to try a no-cub build on Monday, but unfortunately I don't think I'll get a chance by this afternoon.

**Comment by leofang** [comment]
@JohnZed What you should try is to build CuPy with CUB support. This can be done by pointing the env var `CUB_PATH` to the CUB source. When you set `cupy.cuda.cub_enabled=False` you simply fall back to a  "no-CUB build", so there's no need to do this.

**Comment by leofang** [comment]
...that being said, I am 100% sure @JohnZed would just reproduce what I saw in https://github.com/cupy/cupy/issues/3092#issuecomment-589738668. 

@jakirkham I think it's best to consider conda-forge/cupy-feedstock#38 and disable CUB support for now. We really don't have the resource to chase after CUB bugs in conda-forge...

**Comment by jakirkham** [comment]
Do the Python wheels include CUB?

**Comment by leofang** [comment]
No.

**Comment by jakirkham** [comment]
Ah ok. Didn’t expect that. Sounds like CUB is the issue then (or something related to it)

**Comment by leofang** [comment]
Confirmed this is fixed on conda-forge (we just pushed conda-forge/cupy-feedstock#39).

**Comment by leofang** [comment]
Starting from v7.1.0 and building CuPy [along the history](https://github.com/cupy/cupy/compare/v7.1.0...v7.2.0), I was able to pinpoint the offending commit that leads to `cudaErrorIllegalAddress` is e2cce91 (from the backport PR #3000), but I haven't figured out why.

**Comment by leofang** [comment]
It seems the CUB function signatures in v7 and master are different....

**Comment by jakirkham** [comment]
It looks like `cdef ndarray y` was dropped in that commit. Could that be it?

**Comment by leofang** [comment]
@jakirkham You have keen eyes! I verified this missing `cdef` is the cause. Running tests locally to ensure no other errors happen. (CI is not yet set up to test CUB.) Would you like to create a PR targeting v7?

But I don't fully understand what's wrong, though. Is it because `ndarray` is `cimport`'ed instead of being `import`'ed, so Cython couldn't recognize/deduce the type of `y`? Sounds weird...

**Comment by jakirkham** [comment]
That's what my doctors tell me 😂 Sure 🙂

Honestly it's a wild guess. So it could be totally unrelated 😅

**Comment by jakirkham** [comment]
PR ( https://github.com/cupy/cupy/pull/3152 ) adds the type back.

Were you able to get CUB to work with `master`?

**Comment by leofang** [comment]
Oh yes, CUB on master always works. It's just that features and bug fixes are not always backported, so often the backport PRs break things.

**Comment by jakirkham** [comment]
Ah ok. Yeah I think between that and your testing it looks like PR ( https://github.com/cupy/cupy/pull/3152 ) does indeed fix it then. Glad we are getting some confirmation here. Thanks for doing all of that legwork 😄

**Comment by leofang** [comment]
Weird...#3152 is merged but it didn't automatically close this issue?

**Comment by jakirkham** [comment]
I think automatic closing only works for the default branch. So `master` in our case.

**Comment by leofang** [comment]
Ah, didn't know about this. Thanks!
