### ISSUE TITLE
cuslover causes memory overrun while calling syevjBatched

### ISSUE THREAD

**Issue by mor2code** [cupy/cupy#4440]
cuslover.py causes memory overrun while calling syevjBatched,

according to NVidia documentation https://docs.nvidia.com/cuda/cusolver/index.html#cuSolverDN-lt-t-gt-syevjbatch

"an integer array of dimension batchSize. If CUSOLVER_STATUS_INVALID_VALUE is returned, info[0] = -i (less than zero) indicates i-th parameter is wrong (not counting handle). Otherwise, if info[i] = 0, the operation is successful. if info[i] = n+1, syevjBatched dose not converge on i-th matrix under given tolerance and maximum sweeps."

dev_info must be defined otherwise cuda overruns memory not allocated to it (in my case it zeroed a cupy array not related to the call, it actually wrote the results of dev_info on unrelated neighbouring in memory cupy array).

To resolve line 432 of cusolver.py need to be changed from:

dev_info = _cupy.empty((), _numpy.int32)

to:

dev_info = _cupy.empty((int(batch_size)), _cupy.int32)

attached patch

cusolver.py.patch.txt
[cusolver.py.patch.txt](https://github.com/cupy/cupy/files/5693616/cusolver.py.patch.txt)

**Comment by takagi** [comment]
Thanks for reporting! It looks as the code of the non-batched version was copied there. If possible, would you post a pull request with the attached patch?

**Comment by asi1024** [comment]
This issue is resolved by #4491.
