### ISSUE TITLE
CuPy memory leak? (Outstanding consumption.)

### ISSUE THREAD

**Issue by willemavjc** [cupy/cupy#4821]
Hello.

I am wondering how is managed the memory through CuPy and if there could be an issue in the way it is handled.
Let me explain:

I was curious about CuPy and decided to compare it against NumPy via a very simple code that can be find below.
While it works like a charm on NumPy - so on CPU and standard RAM - it totally crashes with CuPy: `cupy.cuda.memory.OutOfMemoryError` is thrown.

```
import numpy as np
import  cupy as cp
import  time

# Reminder: The ** operator means a square operation i.e. 10^9 = 1,000,000,000.
P = 9
N = 10**P

print(f"Scenario 1: Summing ranges of {N} random integers between 0 and 9.")
print("")

Lx = np.random.randint(0, 10, size=N)
print(Lx.nbytes/1024/1024)

T0 = time.perf_counter()
np.sum(Lx)
T1 = time.perf_counter()

del Lx

print("CPU computation done in {:5,.0f} ms.".format((T1-T0)*1000))

Lx = cp.random.randint(0, 10, size=N)
print(Lx.nbytes/1024/1024)

T0 = time.perf_counter()
cp.sum(Lx)
T1 = time.perf_counter()

del Lx

print("GPU computation done in {:5,.0f} ms.".format((T1-T0)*1000))
```

This small code gives the following output:

```
Scenario 1: Summing ranges of 1000000000 random integers between 0 and 1.

3814.697265625
CPU computation done in   585 ms.
Traceback (most recent call last):
  File "C:\APPLIS\nvidia\samples\operations.py", line 23, in <module>
    Lx = cp.random.randint(0, 10, size=N)
  File "C:\APPLIS\python\lib\site-packages\cupy\random\_sample.py", line 110, in randint
    return rs.randint(low, high, size, dtype)
  File "C:\APPLIS\python\lib\site-packages\cupy\random\_generator.py", line 1161, in randint
    x = self._interval(diff, size).astype(dtype, copy=False)
  File "C:\APPLIS\python\lib\site-packages\cupy\random\_generator.py", line 709, in _interval
    ret[n - n_rem:n - n_rem + n_succ] = sample[success][:n_succ]
  File "cupy\core\core.pyx", line 1228, in cupy.core.core.ndarray.__getitem__
  File "cupy\core\_routines_indexing.pyx", line 39, in cupy.core._routines_indexing._ndarray_getitem
  File "cupy\core\_routines_indexing.pyx", line 669, in cupy.core._routines_indexing._getitem_mask_single
  File "cupy\core\_routines_indexing.pyx", line 636, in cupy.core._routines_indexing._prepare_mask_indexing_single
  File "cupy\core\_routines_math.pyx", line 420, in cupy.core._routines_math.scan
  File "cupy\core\core.pyx", line 2392, in cupy.core.core._ndarray_init
  File "cupy\core\core.pyx", line 151, in cupy.core.core.ndarray._init_fast
  File "cupy\cuda\memory.pyx", line 578, in cupy.cuda.memory.alloc
  File "cupy\cuda\memory.pyx", line 1250, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy\cuda\memory.pyx", line 1271, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy\cuda\memory.pyx", line 939, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy\cuda\memory.pyx", line 959, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy\cuda\memory.pyx", line 1210, in cupy.cuda.memory.SingleDeviceMemoryPool._try_malloc
cupy.cuda.memory.OutOfMemoryError: Out of memory allocating 4,000,000,000 bytes (allocated so far: 9,000,001,024 bytes).
```

What that means is that the program failed during `cp.random.randint(0, 10, size=N)` because it missed memory.

Re-running it and keeping an eye on the CPU/RAM/GPU/RAM consumptions raised a weird thing:

- NumPy consumes ~4GB as stated; nothing less, nothing more
- CuPy consumes ~4GB over 4GB available on dedicated RAM ...then starts consuming shared RAM up to 8GB which ends up in crashing as I have no more than 8GB standard RAM free for anything

That means CuPy's RAM consumption requirements for a simple `randint` is more than 3X than NumPy.

Interestingly, I then restrained `randint` to `cp.random.randint(0, 2, size=N)` to see CuPy at least achieve something.

This gave:
```
Scenario 1: Summing ranges of 1000000000 random integers between 0 and 1.

3814.697265625
CPU computation done in   577 ms.
3814.697265625
GPU computation done in   398 ms.
```

Something's fishy. Any clue?

Configuration:

```
OS                           : Windows-10-10.0.17134-SP0
CuPy Version                 : 8.5.0
NumPy Version                : 1.20.1
SciPy Version                : None
Cython Build Version         : 0.29.22
CUDA Root                    : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2
CUDA Build Version           : 11020
CUDA Driver Version          : 11030
CUDA Runtime Version         : 11020
cuBLAS Version               : 11401
cuFFT Version                : 10400
cuRAND Version               : 10203
cuSOLVER Version             : (11, 1, 0)
cuSPARSE Version             : 11400
NVRTC Version                : (11, 2)
Thrust Version               : 101000
CUB Build Version            : 101000
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
Device 0 Name                : Quadro P620
Device 0 Compute Capability  : 61
```

**Comment by emcastillo** [comment]
Hi.
Unfortunately, that is not Host memory but GPU memory. Also, the GPU you use has only 2GB of available memory.
Your array is ~1GB, but there are intermediate memory allocations, the random generator state, and more stuff going on. Moreover, the use of the windows graphic server also consumes device RAM. I am afraid there is no other solution to this than to either use small arrays or a gpu with more RAM. The GPU memory is not paged or does not behave in the same way as the host memory. You can find more about this reading about CUDA.

https://www.nvidia.com/content/dam/en-zz/Solutions/design-visualization/quadro-product-literature/quadro-pascal-p620-data-sheet-593981-us-nv-r3-web.pdf

Also for measuring time, please use cupyx.time.repeat.
You need to synchronize the device, otherwise the time measurements you get will not be correct.

**Comment by willemavjc** [comment]
@emcastillo First, thanks for your reply. There is still things that are not clear to me though.

> Also, the GPU you use has only 2GB of available memory.

I was surprised too from the official specs but Windows states I have 4GB. The way I use to see the specs are: `Task Manager > GPU 1: NVIDIA Quadro P620`.

From there I can see the following:

1. `GPU dedicated memory: 4GB`
2. `GPU shared memory: 8GB`
3. `GPU memory: 12GB`

Is the way I'm getting these specs wrong?

> Moreover, the use of the windows graphic server also consumes device RAM

In fact, it does not as in my case I have a `GPU 0: Intel UHD Graphics 630` which handles the dual screen for example. I can confirm this from the `Task Manager` once again as I see the GPU 0 consuming up to 5% while the GPU 1 stays at 0% forever. (Observation made with no ongoing Python computation.)

> Your array is ~1GB, but there are intermediate memory allocations, the random generator state, and more stuff going on.

Again, this does not make sense to me because I can clearly see a failure after all the RAM I have available **everywhere** is consumed.

Let me precise what I am observing:

1. CPU computation starts (NumPy)
2. `randint` occurs: RAM goes up to 3.8GB
3. Sum computation can proceed

1. GPU computation starts (CuPy)
2. `randint occurs: 
  - GPU dedicated RAM goes up to 4GB
  - GPU shared RAM goes up to 8GB
  - Crash: No more RAM available anywhere
3. Exit

That is the thing which is not clear to me: On one side I have an up to 4GB consumption while on the other side, it asks for more than 12GB in the end.

There may seem something obvious but I'm totally lost about the logic happening here.
Thanks for your time and further explanations.

> Also for measuring time, please use cupyx.time.repeat. You need to synchronize the device, otherwise the time measurements you get will not be correct.

Oh thanks for pointing that. I'll go have a look. Did not know this even exist.

**Comment by emcastillo** [comment]
For the `cupyx.time.repeat` you can take a look at this comment:
https://github.com/cupy/cupy/issues/4767#issuecomment-789127812

Randint is not currently very efficient due to curand limitations in the old random generator API.
If you install CuPy v9 you can use the new numpy random API where randint is much more memory efficient and faster.

https://docs.cupy.dev/en/latest/reference/random.html
https://docs.cupy.dev/en/latest/reference/generated/cupy.random.Generator.html#cupy.random.Generator.integers

**Comment by nizamov** [comment]
Judging that np.sum() gives the same value for a random array:  3814.697265625 for numpy and 3814.697265625 on cupy, I guess that you were operating on the same array - created in numpy, then transferred it to cupy. The script you posted seems to be not the script that failed, but rather the script that succeeded (reason for that is below).

I haven't looked exactly what is going on under the hood, but it seems that array copy from host to GPU occurs through its copy in pinned memory buffer. So, taking just 40 MB arrays and transferring it to GPU repeatedly, I end up with total memory consumption over many GBs: https://github.com/cupy/cupy/issues/4775

Your case might be a little bit different - assuming you allocate 4GB array in host memory and wanting to copy it to GPU memory you end up with 4GB (original array) + 4 GB (array copy in pinned memory) = 8 GB in main memory. And 4 GB in GPU memory. 

Whereas when you create random array directly in GPU memory (using cupy function), you avoid that 4GB transient copy of array. This is what your posted script does (as I see, I haven't run it). 

Why things work this way in CuPy - I have no idea, probably there is some reason why developers decided to do so. I have shortly tried Numba - there host-gpu memory copy occurs through pageable memory (as reported by nvprof), I guess that they copy numpy arrays directly. In CuPy there seems to be an additional array copy (in locked/pinned memory) implicitly involved.

**Comment by leofang** [comment]
The line
```
Lx = cp.random.randint(0, 10, size=N)
```
causes OOM error since N=10^9, meaning you are allocating an array (excluding all intermediate buffers etc) of size ~4GB (on Windows, the default of `randint()` is to use 32-bit int). Your GPU only has 4GB ram. If you did not set the memory allocator to use managed memory, there's no way for either CUDA or CuPy (which builds on top of CUDA) to do the smart memory management and spread the data to host memory for you, if it's what's confusing you.

**Comment by willemavjc** [comment]
> For the `cupyx.time.repeat` you can take a look at this comment:
> [#4767 (comment)](https://github.com/cupy/cupy/issues/4767#issuecomment-789127812)

Thanks for the shortlink. Just read it. The remark made there does not apply in this context from my understanding: I am only measuring `cp.sum()` time operation and not the array initialization so that timing should be guaranteed to be fairly evaluated between numpy and cupy.

> Randint is not currently very efficient due to curand limitations in the old random generator API. It's just a python loop that retries creating arrays, so memory consumption can go pretty high at some point.
>
> If you install CuPy v9 you can use the new numpy random API where randint is much more memory efficient and faster.

Hmm... This does not explain why NumPy is more efficient. Does your explanation implies that Numpy mapped a new random generator onto their old one? If so, why not doing too?

> causes OOM error since N=10^9, meaning you are allocating an array (excluding all intermediate buffers etc) of size ~4GB (on Windows, the default of randint() is to use 32-bit int). Your GPU only has 4GB ram. 

Okay, got it this far :)

> If you did not set the memory allocator to use managed memory, there's no way for either CUDA or CuPy (which builds on top of CUDA) to do any smart memory management and spread the data to host memory for you, if it's what's confusing you.

Err... I got lost there. I did not set any memory allocator, true. (Nor I do know how even though I sense there is part of the answer in the documentation [here](https://docs.cupy.dev/en/stable/reference/cuda.html#memory-management). Some examples in the documentation would probably be welcome.)

But again, if the CUDA/CuPy were limited to their own GPU memory ...how can I end up with +8GB CPU RAM consumption once 4GB GDDR has been consumed?

**Comment by emcastillo** [comment]
> Thanks for the shortlink. Just read it. The remark made there does not apply in this context from my understanding: I am only measuring cp.sum() time operation and not the array initialization so that timing should be guaranteed to be fairly evaluated between numpy and cupy.

Yes, it does apply. When you run a CuPy call, most of the time, the call returns immediately and the operation is done in the background in the GPU. So if you don't synchronize the device, you won't get the total time of the operation. 
measuring only cupy.sum() without doing device synchronization is only measuring the `sum` kernel time launch.
CuPy does manage all this asynchronous stuff automatically.

> Hmm... This does not explain why NumPy is more efficient. Does your explanation implies that Numpy mapped their old random generator onto a new one? If so, why not doing too?

This is about CuPy. The old random API which is what you are using, and is compatible with the old numpy random API, has some issues in the CuPy implementation due to limitations with curand (a cuda library for random numbers). Here there will be lots of memory allocations inside CuPy randint that will cause a peak usage of memory. We know this and we have solved this in the new API, the old one will be deprecated.
The new random API mimics the new random API introduced in NumPy since version 1.17 and solves these issues. So I suggest you install CuPy v9 and try this new random API. Maybe the issue will be gone.
https://numpy.org/doc/stable/reference/random/index.html?highlight=random#module-numpy.random

> But again, if the CUDA/CuPy were limited to their own GPU memory ...how can I end up with +8GB CPU RAM consumption once 4GB GDDR has been consumed?

This may be the NumPy memory is not released immediately in your above script, sometimes when you call del memory is not released at that time, del just marks it to be collected by the garbage collector.

If you do something like
```python
import gc
Lx = np.random....
del Lx
gc.collect()
```
Maybe your host memory usage will decrease when you use CuPy. 
In order to avoid distortions, you can measure CuPy in its own script instead of together with NumPy, this will help to diagnose if CuPy is eating that amount of Host memory due to some strange bug.
I just tried it and did not see any host memory increase, but I am running a Ubuntu system, it may be different in windows.

Host memory is not used unless we are copying an existing array to the GPU or we are moving a GPU result back to the host. If this is happening then we have a bad issue somewhere in the code.

**Comment by leofang** [comment]
> Err... I got lost there. I did not set any memory allocator, true. (Nor I do know how even though I sense there is part of the answer in the documentation [here](https://docs.cupy.dev/en/stable/reference/cuda.html#memory-management). Some examples in the documentation would probably be welcome.)

@emcastillo's reply seems pretty clear at least to me, so I'll just add one more thing: This part of doc that you linked is recently restructured to become a tutorial, see https://docs.cupy.dev/en/latest/tutorial/memory.html. It was buried somewhere in the old version, but it was there.

Another thing I forgot to ask: You mentioned CuPy saturates 8GB CPU memory -- How did you monitor it? Almost all CuPy array creation routines create arrays directly on device (GPU) without going through host (CPU) at all, meaning there's no device-host transfer, so perhaps this is where we are confused.

**Comment by emcastillo** [comment]
yes, but you can easily install it with `pip install cupy-cudaXXX==9.0.0b3`

**Comment by willemavjc** [comment]
> yes, but you can easily install it with `pip install cupy-cudaXXX==9.0.0b3`

It seems not:
```
[root@a197ea26a441 build]# pip install cupy-cuda112==9.0.0b3
ERROR: Could not find a version that satisfies the requirement cupy-cuda112==9.0.0b3
ERROR: No matching distribution found for cupy-cuda112==9.0.0b3
```

Was able to build it from source though:
```
[root@a197ea26a441 /]# pip install cupy==9.0.0b3
Collecting cupy==9.0.0b3
  Using cached cupy-9.0.0b3.tar.gz (1.6 MB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.8/site-packages (from cupy==9.0.0b3) (1.19.5)
Requirement already satisfied: fastrlock>=0.5 in /usr/local/lib/python3.8/site-packages (from cupy==9.0.0b3) (0.5)
Building wheels for collected packages: cupy
  Building wheel for cupy (setup.py) ... /
                                                                                                                                                                   done
  Created wheel for cupy: filename=cupy-9.0.0b3-cp38-cp38-linux_x86_64.whl size=79810023 sha256=57288edd13ecdf068a219c77f5a2020c6700431b0118a4fae893c3ac7d32ffa3
  Stored in directory: /root/.cache/pip/wheels/fd/12/fe/739ff67ff647d2c350eb14ac8f5f5f2415171b7f050ae3ddbc
Successfully built cupy
Installing collected packages: cupy
Successfully installed cupy-9.0.0b3
```

Should be testing it shortly.

**Comment by willemavjc** [comment]
Figured out the increasing memory consumption for NumPy: The new integer generator is giving `int64` by default while the old was giving `int` meaning `int32`.

Adding `dtype=np.int32` put things in order for NumPy.

For CuPy though, this did not help.

**Comment by jobs-git** [comment]
you did not have enough VRAM or your code is using a different data type that results to illegal memory access. You could try:

````
mem_pool = cp.cuda.MemoryPool (cp.cuda.malloc_managed)
cp.cuda.set_allocator (mem_pool.malloc)

#the rest of the code
mem_pool.free_all_blocks ()
````

**Comment by kmaehashi** [comment]
I'm closing this one as it's inactive for a while. Feel free to request reopening if necessary.
