### ISSUE TITLE
CUDA_ERROR_INVALID_HANDLE if activating the stream

### ISSUE THREAD

**Issue by mfoglio** [cupy/cupy#4899]
I am running two tensorRT engines and doing preprocessing using cupy.

A thread uploads numpy array to gpu using the following code:

```
    def _upload_to_gpu(batch: List[np.array]):
        return [cp.array(np_array) for np_array in batch]
```

The results of above function is then passed to another thread, an the array is merged:
```
        stream.use()
        # Copy cupy array to the buffer
        input_images = cp.array(batch_input_image)
```
On the second line I have the following error:

```
    input_images = cp.array(batch_input_image)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/cupy/_creation/from_data.py", line 41, in array
    return core.array(obj, dtype, copy, order, subok, ndmin)
  File "cupy/core/core.pyx", line 1984, in cupy.core.core.array
  File "cupy/core/core.pyx", line 2049, in cupy.core.core.array
  File "cupy/core/_routines_manipulation.pyx", line 596, in cupy.core._routines_manipulation.concatenate_method
  File "cupy/core/_routines_manipulation.pyx", line 633, in cupy.core._routines_manipulation._concatenate
  File "cupy/core/_kernel.pyx", line 1086, in cupy.core._kernel.ufunc.__call__
  File "cupy/cuda/function.pyx", line 196, in cupy.cuda.function.Function.linear_launch
  File "cupy/cuda/function.pyx", line 164, in cupy.cuda.function._launch
  File "cupy_backends/cuda/api/driver.pyx", line 299, in cupy_backends.cuda.api.driver.launchKernel
  File "cupy_backends/cuda/api/driver.pyx", line 124, in cupy_backends.cuda.api.driver.check_status
cupy_backends.cuda.api.driver.CUDADriverError: CUDA_ERROR_INVALID_HANDLE: invalid resource handle
```

I don't have this error if I do not use the stream, but I am not sure why. 

Is there a way I can check what is the current context? I should have just one but it could be useful to check that not more have been allocated.

Thank you :) 

EDIT: while debugging, I noticed that the stream in the function _upload_to_gpu is `0` while the stream in the other piece of code seems to be a real pointer (e.g. `100895600`) even *before* activating the stream using `stream.use()` (the stream was initialized in the `__init__` of the class, but that piece of code is executed in another function. Could this possibly be a problem? I checked the streams using `print(cp.cuda.get_current_stream().ptr)`

EDIT2: I believe this always in the class relative to the second engine model started. So possibly there is something wrong with contexts.

**Comment by mfoglio** [comment]
It was probably a problem with contexts created by `import pycuda.autoinit`.

**Comment by leofang** [comment]
@mfoglio It's worth noting that CuPy's "current" streams are thread-local, in the sense that if you do
```python 
s = cp.cuda.Stream()
s.use()
```
or
```python
s = cp.cuda.Stream()
with s:
    ...
```
only the current thread sees the anticipated stream `s` and uses it for kernel launching, copying, etc. 

Taking this as an example:
```python
>>> import threading                                                                                                                                                   
>>> import cupy as cp           
>>>                                                                                                                                                                                                                                                                                                           
>>> s = cp.cuda.Stream()                                                                                                                                               
>>> s.use()                                                                                                                                                            
<Stream 93917855534288>
>>> s.ptr                                                                                                                                                              
93917855534288 
>>>                                                                                                                                                
>>> def get_current_s():                                                                                                                                               
...     s = cp.cuda.get_current_stream()                                                                                                                               
...     print(s.ptr)                                                                                                                                                   
...                                                                                                                                                                    
>>> thread = threading.Thread(target=get_current_s)                                                                                                                    
>>> thread.start()                                                                                                                                                     
0                                                                                                                                                                      
>>> thread.join()                                                                                                                                                      
>>>
```
you can see the new thread does not get the stream you anticipated (pointer address 93917855534288).

**Comment by mfoglio** [comment]
Thank you @leofang . I think it was probably an issue with pycuda's contexts.

Can you confirm the following cupy operations will be executed before the functions return? I am still having some other issues and I am not sure whether they might be related to these pieces of code.

```
    @staticmethod
    def _download_from_gpu(batch: List[cp.array]):
        return [cp_array.get() for cp_array in batch]
```

```
    @staticmethod
    def _download_from_gpu(batch: List[cp.array]):
        with cp.cuda.Stream():
            return [cp_array.get() for cp_array in batch]

```

Thanks

**Comment by mfoglio** [comment]
Thank you @leofang . The issue was caused by pycuda contexts. I was using cupy but an `import pycuda.autoinit` was initializing a contexts that leads to the crash.
