### ISSUE TITLE
WSL cuda 11.2: CUDARuntimeError: cudaErrorInvalidValue: invalid argument

### ISSUE THREAD

**Issue by danlkv** [cupy/cupy#5074]
I installed cupy on WSL, and get a runtime error when trying to use cupy.

1. Kernel
```
» uname -a
Linux DESKTOP-1OG5J92 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
» cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
```

2. Cupy
```
» python -c 'import cupy; cupy.show_config()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/plate/.local/lib/python3.8/site-packages/cupy/__init__.py", line 866, in show_config
    _sys.stdout.write(str(_cupyx.get_runtime_info()))
  File "/home/plate/.local/lib/python3.8/site-packages/cupyx/_runtime.py", line 240, in get_runtime_info
    return _RuntimeInfo()
  File "/home/plate/.local/lib/python3.8/site-packages/cupyx/_runtime.py", line 138, in __init__
    self.cublas_version = _eval_or_error(
  File "/home/plate/.local/lib/python3.8/site-packages/cupyx/_runtime.py", line 49, in _eval_or_error
    return func()
  File "/home/plate/.local/lib/python3.8/site-packages/cupyx/_runtime.py", line 140, in <lambda>
    cupy.cuda.device.get_cublas_handle()),
  File "cupy/cuda/device.pyx", line 46, in cupy.cuda.device.get_cublas_handle
  File "cupy/cuda/device.pyx", line 47, in cupy.cuda.device.get_cublas_handle
  File "cupy/cuda/device.pyx", line 29, in cupy.cuda.device._get_device
  File "cupy_backends/cuda/api/runtime.pyx", line 275, in cupy_backends.cuda.api.runtime.getDevice
  File "cupy_backends/cuda/api/runtime.pyx", line 247, in cupy_backends.cuda.api.runtime.check_status
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorInvalidValue: invalid argument
```

3. CUDA
```
» nvidia-smi.exe
Fri Apr  9 13:13:07 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.12       Driver Version: 465.12       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 165... WDDM  | 00000000:02:00.0 Off |                  N/A |
| N/A   40C    P8     3W /  N/A |    132MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+


+-----------------------------------------------------------------------------+
| Processes:
 |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found
 |
 
 » apt list --installed | grep cuda

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

cuda-command-line-tools-11-2/unknown,unknown,now 11.2.2-1 amd64 [installed,automatic]
cuda-compiler-11-2/unknown,unknown,now 11.2.2-1 amd64 [installed,automatic]
cuda-cudart-11-2/unknown,unknown,now 11.2.152-1 amd64 [installed,automatic]
cuda-cudart-dev-11-2/unknown,unknown,now 11.2.152-1 amd64 [installed,automatic]
cuda-cuobjdump-11-2/unknown,unknown,now 11.2.152-1 amd64 [installed,automatic]
cuda-cupti-11-2/unknown,unknown,now 11.2.152-1 amd64 [installed,automatic]
cuda-cupti-dev-11-2/unknown,unknown,now 11.2.152-1 amd64 [installed,automatic]
cuda-cuxxfilt-11-2/unknown,unknown,now 11.2.152-1 amd64 [installed,automatic]
cuda-documentation-11-2/unknown,unknown,now 11.2.154-1 amd64 [installed,automatic]
cuda-driver-dev-11-2/unknown,unknown,now 11.2.152-1 amd64 [installed,automatic]
cuda-gdb-11-2/unknown,unknown,now 11.2.152-1 amd64 [installed,automatic]
cuda-libraries-11-2/unknown,unknown,now 11.2.2-1 amd64 [installed,automatic]
cuda-libraries-dev-11-2/unknown,unknown,now 11.2.2-1 amd64 [installed,automatic]
cuda-memcheck-11-2/unknown,unknown,now 11.2.152-1 amd64 [installed,automatic]
cuda-nsight-11-2/unknown,unknown,now 11.2.152-1 amd64 [installed,automatic]
cuda-nsight-compute-11-2/unknown,unknown,now 11.2.2-1 amd64 [installed,automatic]
cuda-nsight-systems-11-2/unknown,unknown,now 11.2.2-1 amd64 [installed,automatic]
cuda-nvcc-11-2/unknown,unknown,now 11.2.152-1 amd64 [installed,automatic]
cuda-nvdisasm-11-2/unknown,unknown,now 11.2.152-1 amd64 [installed,automatic]
cuda-nvml-dev-11-2/unknown,unknown,now 11.2.152-1 amd64 [installed,automatic]
cuda-nvprof-11-2/unknown,unknown,now 11.2.152-1 amd64 [installed,automatic]
cuda-nvprune-11-2/unknown,unknown,now 11.2.152-1 amd64 [installed,automatic]
cuda-nvrtc-11-2/unknown,unknown,now 11.2.152-1 amd64 [installed,automatic]
cuda-nvrtc-dev-11-2/unknown,unknown,now 11.2.152-1 amd64 [installed,automatic]
cuda-nvtx-11-2/unknown,unknown,now 11.2.152-1 amd64 [installed,automatic]
cuda-nvvp-11-2/unknown,unknown,now 11.2.152-1 amd64 [installed,automatic]
cuda-samples-11-2/unknown,unknown,now 11.2.152-1 amd64 [installed,automatic]
cuda-sanitizer-11-2/unknown,unknown,now 11.2.152-1 amd64 [installed,automatic]
cuda-toolkit-11-2/unknown,unknown,now 11.2.2-1 amd64 [installed]
cuda-tools-11-2/unknown,unknown,now 11.2.2-1 amd64 [installed,automatic]
cuda-visual-tools-11-2/unknown,unknown,now 11.2.2-1 amd64 [installed,automatic]
```

I also verified my environment using pytorch, and it looks like it's working, `torch.cuda.is_available()` is `True`

**Comment by leofang** [comment]
This is interesting as this is the 1st time we receive a WSL report AFAIK 😄 I know cuSignal people have tested it on WSL so it should just work. May I ask how did you install CuPy?

**Comment by danlkv** [comment]
I just did `pip install cupy-cuda112`

**Comment by leofang** [comment]
And the CUDA on WSL is set up according NVIDIA's instruction, right?
https://docs.nvidia.com/cuda/wsl-user-guide/index.html

**Comment by leofang** [comment]
Do you get any error if you try to run some simple operations? For example
```python
import cupy as cp

a = cp.empty((10,))
a[:] = 3
print(a)
```

**Comment by danlkv** [comment]
Yes, I used that link to install cuda.

```» ipython
Python 3.8.2 (default, Mar 13 2020, 10:14:16)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import cupy as cp

In [2]:

In [2]: a = cp.empty((10,))
---------------------------------------------------------------------------
CUDARuntimeError                          Traceback (most recent call last)
<ipython-input-2-f2a5c64d4455> in <module>
----> 1 a = cp.empty((10,))

~/.local/lib/python3.8/site-packages/cupy/_creation/basic.py in empty(shape, dtype, order)
     20
     21     """
---> 22     return cupy.ndarray(shape, dtype, order=order)
     23
     24

cupy/core/core.pyx in cupy.core.core.ndarray.__init__()

cupy/cuda/memory.pyx in cupy.cuda.memory.alloc()

cupy/cuda/memory.pyx in cupy.cuda.memory.MemoryPool.malloc()

cupy/cuda/memory.pyx in cupy.cuda.memory.MemoryPool.malloc()

cupy/cuda/device.pyx in cupy.cuda.device.get_device_id()

cupy_backends/cuda/api/runtime.pyx in cupy_backends.cuda.api.runtime.getDevice()

cupy_backends/cuda/api/runtime.pyx in cupy_backends.cuda.api.runtime.check_status()

CUDARuntimeError: cudaErrorInvalidValue: invalid argument

```

**Comment by danlkv** [comment]
In the cuSignal instractions you linked there's a comment  "See the CuPy Documentation for information on getting **Windows** wheels for other versions of CUDA." Does this mean they actually installed cupy into windows, not WSL? What I did is just `pip install` in the WSL terminal, not Windows/anaconda shell. I don't even have python on the Windows system.

**Comment by leofang** [comment]
Could you uninstall your CuPy (`pip uninstall cupy-cuda112`), and then install it directly from PyPI:
```
pip install https://files.pythonhosted.org/packages/98/55/5785866af86c873196a23ee0e55cc6d1991e934bcae2ffb20d4a12295bca/cupy_cuda112-8.6.0-cp38-cp38-win_amd64.whl
```
(I am assuming you're on Python 3.8, if not please choose an appropriate link [here](https://pypi.org/project/cupy-cuda112/#files).)

My best guess is `pip` mistakenly thinks you're on Linux so it installed the Linux wheel, but maybe WSL still needs a Win-based wheel (or vice versa).

**Comment by danlkv** [comment]
My understanding is that WSL *is* linux, but all calls are translated somehow to windows api. Yes, I'm on ptyhon 3.8, pip refuses to install the windows wheel. 

```
» pip install https://files.pythonhosted.org/packages/98/55/5785866af86c873196a23ee0e55cc6d1991e934bcae2ffb20d4a12295bca/cupy_cuda112-8.6.0-cp38-cp38-win_amd64.whl
Defaulting to user installation because normal site-packages is not writeable
ERROR: cupy_cuda112-8.6.0-cp38-cp38-win_amd64.whl is not a supported wheel on this platform.
```

**Comment by leofang** [comment]
Yeah I don't have better thoughts, sorry. Maybe someone from the core devs is knowledgeable in WSL...😅

**Comment by leofang** [comment]
Your environment can correctly run CUDA sample codes, right? ex: https://docs.nvidia.com/cuda/wsl-user-guide/index.html#unique_1014163249

**Comment by leofang** [comment]
Another question: Looks like CUDA 11.2 requires a newer driver:
> 1/28/2021: CUDA Toolkit 11.2 support, nvidia-smi, NVML support and critical performance improvements.
The following software versions are supported with this preview release for WSL 2:
NVIDIA Driver for Windows 10: 465.42
Recommended WIP build: 21292

https://docs.nvidia.com/cuda/wsl-user-guide/index.html#changelog

Your driver is on 465.12.

**Comment by danlkv** [comment]
Yeah looks like the same error occurs when I try to run examples

```
» ./BlackScholes
[./BlackScholes] - Starting...
CUDA error at ../../common/inc/helper_cuda.h:779 code=1(cudaErrorInvalidValue) "cudaGetDeviceCount(&device_count)"
```
I'll try to update the driver and get back with updates

**Comment by danlkv** [comment]
Installed driver version 470, and it works🎉 Thanks!

**Comment by leofang** [comment]
Awesome! Let us know how it goes with CUDA on WSL.

btw Are you using Conda, or just WSL's system Python? I am curious if our conda package also works on WSL or not...

**Comment by danlkv** [comment]
I'm using just bare-bones pip. I'm not a fan of conda or pyenv, I just try to have the latest-version-only environment.

**Comment by leofang** [comment]
This issue is resolved, right @danlkv?

**Comment by danlkv** [comment]
Oh, sure, yes
