### ISSUE TITLE
Per-Thread Default Stream Not Working

### ISSUE THREAD

**Issue by insertinterestingnamehere** [cupy/cupy#5092]
The per-thread default stream environment variable is currently unusable. Running something simple like:
```
import os
os.environ["CUPY_CUDA_PER_THREAD_DEFAULT_STREAM"] = "1"
import cupy
a = cp.array([1.])
```
results in the error:
```
File "<stdin>", line 1, in <module>
  File ".../miniconda3/envs/patched_numba/lib/python3.8/site-packages/cupy/_creation/from_data.py", line 41, in array
    return core.array(obj, dtype, copy, order, subok, ndmin)
  File "cupy/core/core.pyx", line 2016, in cupy.core.core.array
  File "cupy/core/core.pyx", line 2095, in cupy.core.core.array
  File "cupy/core/core.pyx", line 2169, in cupy.core.core._send_object_to_gpu
  File "cupy/core/core.pyx", line 138, in cupy.core.core.ndarray.__init__
  File "cupy/cuda/memory.pyx", line 578, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1250, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1271, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 939, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 959, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 1190, in cupy.cuda.memory.SingleDeviceMemoryPool._try_malloc
  File "cupy/cuda/memory.pyx", line 1187, in cupy.cuda.memory.SingleDeviceMemoryPool._try_malloc
  File "cupy/cuda/memory.pyx", line 910, in cupy.cuda.memory.SingleDeviceMemoryPool._alloc
  File "cupy/cuda/memory.pyx", line 520, in cupy.cuda.memory._malloc
  File "cupy/cuda/memory.pyx", line 521, in cupy.cuda.memory._malloc
  File "cupy/cuda/memory.pyx", line 100, in cupy.cuda.memory.Memory.__init__
  File "cupy_backends/cuda/api/runtime.pyx", line 550, in cupy_backends.cuda.api.runtime.malloc
  File "cupy_backends/cuda/api/runtime.pyx", line 247, in cupy_backends.cuda.api.runtime.check_status
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorUnsupportedPtxVersion: the provided PTX was compiled with an unsupported toolchain.
```

This is on Ubuntu 18.04 with Python 3.8, cupy 8.6.0, and cuda 11.2 obtained via conda-forge.

**Comment by emcastillo** [comment]
Can you try this with v9.0.0rc1?

**Comment by leofang** [comment]
> This is on Ubuntu 18.04 with Python 3.8, cupy 8.6.0, and cuda 11.2 obtained via conda-forge.

I cannot reproduce the error with exactly the same env. Any chance you're doing this in the source directory?

**Comment by insertinterestingnamehere** [comment]
Thanks for the suggestions! I just confirmed that this is fixed in master (that or I'm getting a bad binary?). When I build master from source this works now. Closing.

**Comment by leofang** [comment]
I think it's simply because your test env is somehow scrambled. It works even in v8.6.0 as I said. You may want to create a fresh env and redo the test.

**Comment by kmaehashi** [comment]
> cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorUnsupportedPtxVersion: the provided PTX was compiled with an unsupported toolchain.

We recently observed this error message when running CuPy on CUDA 11.3 with an outdated CUDA driver version. If you encounter this issue again please report with the `cupy.show_config()` output.

**Comment by tendant** [comment]
We have this issue with below Nvidia driver in AWS EKS with GPU node. 

Nvidia Driver Version: 460.73.01    CUDA Version: 11.2

![Screen Shot 2021-06-25 at 8 32 58 AM](https://user-images.githubusercontent.com/37181/123449042-294f4580-d590-11eb-9474-0cf40180db27.png)

According to Nvidia website, this is the most up to date driver for datacenter gpu. (https://www.nvidia.com/Download/Find.aspx) 

![Screen Shot 2021-06-25 at 8 35 50 AM](https://user-images.githubusercontent.com/37181/123449366-759a8580-d590-11eb-9934-157c08c8b286.png)

Is there any work around for this issue? 

Thanks!

**Comment by tendant** [comment]
Output from cupy.show_config():

OS                           : Linux-5.4.117-58.216.amzn2.x86_64-x86_64-with-glibc2.29
Python Version               : 3.8.5
CuPy Version                 : 9.2.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.21.0
SciPy Version                : 1.7.0
Cython Build Version         : 0.29.22
Cython Runtime Version       : None
CUDA Root                    : /usr/local/cuda-11.3
nvcc PATH                    : /usr/local/cuda-11.3/bin/nvcc
CUDA Build Version           : 11020
CUDA Driver Version          : 11020
CUDA Runtime Version         : 11030
cuBLAS Version               : (available)
cuFFT Version                : 10402
cuRAND Version               : 10204
cuSOLVER Version             : (11, 1, 2)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 3)
Thrust Version               : 101000
CUB Build Version            : 101000
Jitify Build Version         : 60e9e72
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : 2804
NCCL Runtime Version         : 20906
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : Tesla K80
Device 0 Compute Capability  : 37
Device 0 PCI Bus ID          : 0000:00:1E.0

**Comment by kmaehashi** [comment]
```
CUDA Root : /usr/local/cuda-11.3
nvcc PATH : /usr/local/cuda-11.3/bin/nvcc
CUDA Build Version : 11020
CUDA Driver Version : 11020
CUDA Runtime Version : 11030
```

It seems that you are using CUDA 11.3 against CUDA driver 11.2, but this is known to cause this error (c.f. https://github.com/cupy/cupy/issues/5095#issuecomment-833003035, #5097) (although I think [NVIDIA docs](https://docs.nvidia.com/deploy/cuda-compatibility/index.html#binary-compatibility) says it is a compatible configuration).
Could you try using CUDA 11.2 + `cupy-cuda112` instead of 11.3?
