### ISSUE TITLE
Get segmentation fault with FFT callback function 

### ISSUE THREAD

**Issue by szsdk** [cupy/cupy#5296]
`pr.py`
```python
import numpy as np
import cupy as cp

code = r'''
__device__ cufftComplex CB_ConvertInput(
    void *dataIn,
    size_t offset,
    void *callerInfo,
    void *sharedPtr) {
            return make_float2(0.0, 0.1);
}

__device__ cufftCallbackLoadC d_loadCallbackPtr = CB_ConvertInput;
'''

in_arr = cp.random.rand(12, dtype=np.float32)

with cp.fft.config.set_cufft_callbacks(cb_load=code):
    out_arr = cp.fft.fft(in_arr)

print(out_arr)
```
Run with
```
CUDA_VISIBLE_DEVICES=0 python pr.py
```
Then I got
```
[1]    410392 segmentation fault (core dumped)  CUDA_VISIBLE_DEVICES=0 python pr.py
```

My system information:
```
OS                           : Linux-5.12.8-arch1-1-x86_64-with-glibc2.33
Python Version               : 3.9.5
CuPy Version                 : 9.1.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.20.0
SciPy Version                : 1.6.3
Cython Build Version         : 0.29.23
Cython Runtime Version       : 0.29.23
CUDA Root                    : /opt/cuda
nvcc PATH                    : /opt/cuda/bin/nvcc
CUDA Build Version           : 11030
CUDA Driver Version          : 11030
CUDA Runtime Version         : 11030
cuBLAS Version               : 11402
cuFFT Version                : 10402
cuRAND Version               : 10204
cuSOLVER Version             : (11, 1, 1)
cuSPARSE Version             : 11500
NVRTC Version                : (11, 3)
Thrust Version               : 101100
CUB Build Version            : 101100
Jitify Build Version         : 60e9e72
cuDNN Build Version          : 8200
cuDNN Version                : 8200
NCCL Build Version           : 20906
NCCL Runtime Version         : 20906
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce GTX 1080
Device 0 Compute Capability  : 61
Device 0 PCI Bus ID          : 0000:17:00.0
Device 1 Name                : NVIDIA Quadro K600
Device 1 Compute Capability  : 30
Device 1 PCI Bus ID          : 0000:65:00.0
```

**Comment by leofang** [comment]
I cannot reproduce this. Your reproducer runs fine on my system with both CUDA 11.2 & 11.3 (and driver 11.3). If you can run `gdb` on the dumped core we could get some hints. Another thing to try is to clear the existing cache (`~/.cupy/callback_cache` or perhaps just everything under `~/.cupy/`).

**Comment by leofang** [comment]
btw what's your OS and how Python and CuPy were installed?

**Comment by szsdk** [comment]
@leofang 
My system is archlinux. The cupy is installed from archlinuxcn/python-cupy.
After deleting `.cupy` folder, I got a warning before the segmentation fault.
```
nvprune warning : No device code that matched architecture, so stripped out all device code
```

**Comment by szsdk** [comment]
```
CUDA_VISIBLE_DEVICES=0 valgrind python pr.py
```
<details><summary>part of valgrind output</summary>
<p>
```
==646703== Use of uninitialised value of size 8
==646703==    at 0x49B77B2: PyObject_Realloc (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49EB528: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49ED788: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49ED673: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x4A6201E: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49ED673: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x4A6201E: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49ED673: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49E9445: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x4A61056: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49E98C9: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x4A61056: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703== 
==646703== Invalid read of size 4
==646703==    at 0x498E282: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x4A77656: PyObject_Dir (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x4A77595: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49BE127: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49A6512: _PyObject_MakeTpCall (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49A1F85: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49ADADA: _PyFunction_Vectorcall (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49A1E66: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x499C218: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x499BC00: _PyEval_EvalCodeWithName (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x4A52D62: PyEval_EvalCode (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x4A59C8B: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==  Address 0x7394020 is 80 bytes inside a block of size 1,112 free'd
==646703==    at 0x484118B: free (vg_replace_malloc.c:755)
==646703==    by 0x4989147: PyObject_Free (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x4988956: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x498C3FF: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49925DF: PyDict_SetItemString (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49BD52A: PyModule_AddObject (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49D3B3C: PyModule_AddIntConstant (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x5450AD02: PyInit__socket (in /usr/lib/python3.9/lib-dynload/_socket.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x4A7E11E: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49AE5A7: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49A30EA: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x499C218: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==  Block was alloc'd at
==646703==    at 0x483E7C5: malloc (vg_replace_malloc.c:380)
==646703==    by 0x4984F03: PyObject_Malloc (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x498884C: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x498C3FF: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49932DB: _PyObject_GenericSetAttrWithDict (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x4992CDC: PyObject_SetAttr (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x4992C52: PyObject_SetAttrString (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x4A51385: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x4A512CD: PyModule_AddFunctions (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x4A5101E: _PyModule_CreateInitialized (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x5450AB54: PyInit__socket (in /usr/lib/python3.9/lib-dynload/_socket.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x4A7E11E: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703== 
==646703== Invalid read of size 4
==646703==    at 0x498D832: PyMem_Free (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49F73EC: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x499ED87: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49ADADA: _PyFunction_Vectorcall (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x499D566: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x499C218: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x499BC00: _PyEval_EvalCodeWithName (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x4A52D62: PyEval_EvalCode (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x4A59C8B: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49AE5A7: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49A30EA: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x499C218: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==  Address 0x75eb020 is 224 bytes inside a block of size 576 free'd
==646703==    at 0x484118B: free (vg_replace_malloc.c:755)
==646703==    by 0x4989147: PyObject_Free (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x4988956: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x498C3FF: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x499F2BA: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x499C218: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x499BC00: _PyEval_EvalCodeWithName (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x4A52D62: PyEval_EvalCode (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x4A59C8B: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49AE5A7: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49A30EA: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x499C218: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==  Block was alloc'd at
==646703==    at 0x483E7C5: malloc (vg_replace_malloc.c:380)
==646703==    by 0x4984F03: PyObject_Malloc (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x498884C: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x498C3FF: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x499F2BA: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x499C218: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x499BC00: _PyEval_EvalCodeWithName (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x4A52D62: PyEval_EvalCode (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x4A59C8B: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49AE5A7: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49A30EA: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x499C218: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703== 
==646703== Conditional jump or move depends on uninitialised value(s)
==646703==    at 0x4A1E693: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49DB768: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x499D7B9: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x499C218: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49ADCFD: _PyFunction_Vectorcall (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49A1E66: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x521B9BD0: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/_kernel.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x521BAFC6: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/_kernel.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x521C6911: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/_kernel.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x521E3249: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/_kernel.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x49A652A: _PyObject_MakeTpCall (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49A260A: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.9.so.1.0)
==646703== 
==646703== Use of uninitialised value of size 8
==646703==    at 0x4A1E6AB: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49DB768: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x499D7B9: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x499C218: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49ADCFD: _PyFunction_Vectorcall (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49A1E66: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x521B9BD0: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/_kernel.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x521BAFC6: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/_kernel.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x521C6911: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/_kernel.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x521E3249: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/_kernel.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x49A652A: _PyObject_MakeTpCall (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49A260A: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.9.so.1.0)
==646703== 
==646703== Warning: noted but unhandled ioctl 0x30000001 with no size/direction hints.
==646703==    This could cause spurious value errors to appear.
==646703==    See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
==646703== Warning: noted but unhandled ioctl 0x27 with no size/direction hints.
==646703==    This could cause spurious value errors to appear.
==646703==    See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
==646703== Warning: noted but unhandled ioctl 0x25 with no size/direction hints.
==646703==    This could cause spurious value errors to appear.
==646703==    See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
==646703== Warning: noted but unhandled ioctl 0x37 with no size/direction hints.
==646703==    This could cause spurious value errors to appear.
==646703==    See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
==646703== Warning: noted but unhandled ioctl 0x17 with no size/direction hints.
==646703==    This could cause spurious value errors to appear.
==646703==    See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
==646703== Warning: set address range perms: large range [0x200000000, 0x300200000) (noaccess)
==646703== Warning: set address range perms: large range [0x761b5000, 0x961b4000) (noaccess)
==646703== Warning: noted but unhandled ioctl 0x19 with no size/direction hints.
==646703==    This could cause spurious value errors to appear.
==646703==    See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
==646703== Warning: set address range perms: large range [0x10006000000, 0x10106000000) (noaccess)
==646703== Warning: noted but unhandled ioctl 0x49 with no size/direction hints.
==646703==    This could cause spurious value errors to appear.
==646703==    See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
==646703== Warning: noted but unhandled ioctl 0x21 with no size/direction hints.
==646703==    This could cause spurious value errors to appear.
==646703==    See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
==646703== Warning: noted but unhandled ioctl 0x1b with no size/direction hints.
==646703==    This could cause spurious value errors to appear.
==646703==    See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
==646703== Warning: noted but unhandled ioctl 0x44 with no size/direction hints.
==646703==    This could cause spurious value errors to appear.
==646703==    See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
==646703== Conditional jump or move depends on uninitialised value(s)
==646703==    at 0x49B22CE: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x4A982C1: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49AE5A7: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x15AE9439: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/core.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x15B0D40D: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/core.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x15B1EE88: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/core.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x521D3411: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/_kernel.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x521E1666: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/_kernel.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x49BE0FD: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x160C1277: ??? (in /usr/lib/python3.9/site-packages/cupy/_util.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x521E8023: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/_kernel.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x521FA96B: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/_kernel.cpython-39-x86_64-linux-gnu.so)
==646703== 
==646703== Invalid read of size 4
==646703==    at 0x49B22C4: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x4A982C1: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49AE5A7: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x15AE9439: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/core.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x15B0D40D: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/core.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x15B1EE88: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/core.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x521D3411: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/_kernel.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x521E1666: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/_kernel.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x49BE0FD: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x160C1277: ??? (in /usr/lib/python3.9/site-packages/cupy/_util.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x521E8023: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/_kernel.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x521FA96B: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/_kernel.cpython-39-x86_64-linux-gnu.so)
==646703==  Address 0x5b80020 is 1,968 bytes inside a block of size 4,333 free'd
==646703==    at 0x484383F: realloc (vg_replace_malloc.c:1192)
==646703==    by 0x49F36A8: _PyBytes_Resize (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x4A65256: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49AB3B8: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x4A44F5B: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x4A64D4D: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49BD713: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49B4086: PyObject_VectorcallMethod (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x4A98281: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49AE5A7: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x15AE9439: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/core.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x15B0D40D: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/core.cpython-39-x86_64-linux-gnu.so)
==646703==  Block was alloc'd at
==646703==    at 0x483E7C5: malloc (vg_replace_malloc.c:380)
==646703==    by 0x499A233: PyBytes_FromStringAndSize (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x4A651FE: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49AB3B8: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x4A44F5B: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x4A64D4D: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49BD713: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49B4086: PyObject_VectorcallMethod (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x4A98281: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49AE5A7: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x15AE9439: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/core.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x15B0D40D: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/core.cpython-39-x86_64-linux-gnu.so)
==646703== 
==646703== Conditional jump or move depends on uninitialised value(s)
==646703==    at 0x49B7479: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49B6DD6: _PyUnicodeWriter_PrepareInternal (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x4A0C895: PyUnicode_Format (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49A2BE9: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x499C218: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49ADCFD: _PyFunction_Vectorcall (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x499D566: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x499C218: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49ADCFD: _PyFunction_Vectorcall (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49BD450: PyVectorcall_Call (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x15AE218E: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/core.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x15B1F9C1: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/core.cpython-39-x86_64-linux-gnu.so)
==646703== 
==646703== Use of uninitialised value of size 8
==646703==    at 0x49B7491: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49B6DD6: _PyUnicodeWriter_PrepareInternal (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x4A0C895: PyUnicode_Format (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49A2BE9: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x499C218: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49ADCFD: _PyFunction_Vectorcall (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x499D566: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x499C218: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49ADCFD: _PyFunction_Vectorcall (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49BD450: PyVectorcall_Call (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x15AE218E: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/core.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x15B1F9C1: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/core.cpython-39-x86_64-linux-gnu.so)
==646703== 
==646703== Conditional jump or move depends on uninitialised value(s)
==646703==    at 0x4988BDC: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x521D32C0: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/_kernel.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x521DFD19: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/_kernel.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x521F6DF2: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/_kernel.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x15AE218E: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/core.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x15B33B17: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/core.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x15AF1009: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/core.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x49AFA7A: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x499D7B9: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49ADADA: _PyFunction_Vectorcall (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x499D566: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x499C218: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703== 
==646703== Use of uninitialised value of size 8
==646703==    at 0x4988BF4: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x521D32C0: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/_kernel.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x521DFD19: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/_kernel.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x521F6DF2: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/_kernel.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x15AE218E: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/core.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x15B33B17: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/core.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x15AF1009: ??? (in /usr/lib/python3.9/site-packages/cupy/_core/core.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x49AFA7A: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x499D7B9: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x49ADADA: _PyFunction_Vectorcall (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x499D566: _PyEval_EvalFrameDefault (in /usr/lib/libpython3.9.so.1.0)
==646703==    by 0x499C218: ??? (in /usr/lib/libpython3.9.so.1.0)
==646703== 
==646703== Conditional jump or move depends on uninitialised value(s)
==646703==    at 0x44243004: ??? (in /usr/lib/libcuda.so.465.31)
==646703==    by 0x43FE5391: ??? (in /usr/lib/libcuda.so.465.31)
==646703==    by 0x440ADFF4: ??? (in /usr/lib/libcuda.so.465.31)
==646703==    by 0x7D67ACE4: DSELaunch::proc(fftDynamicParameters const&, device const&, void*, void const*, unsigned int, Dim, Pitch, Pitch, unsigned long long, unsigned long long, unsigned long long, unsigned long long) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D614FD7: StridedMultiKernel::proc(fftDynamicParameters const&, device const&, void*, void const*, unsigned int, Dim, Pitch, Pitch, unsigned long long, unsigned long long, unsigned long long, unsigned long long) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D6514FE: Callback::proc(fftDynamicParameters const&, device const&, void*, void const*, unsigned int, Dim, Pitch, Pitch, unsigned long long, unsigned long long, unsigned long long, unsigned long long) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D61D02C: Queue::launch(device const&, fftDynamicParameters&, void*, void*, void const*, Pitch, Pitch, Pitch, unsigned int, Dim) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D6FA99C: fftDimensionCT::exec(device const&, fftDynamicParameters&, void*, void*, void const*) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D61A721: fftCooleyTukeyC2C::exec(void*, void*, void const*, fftDynamicParameters const&, device const&) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D5FD2F3: Visitors::Execute::operator()(Operation::Queue&) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D5EEFC1: cufftExecuteDescriptor(fftHandleStruct*, cudaLibXtDesc_t*, cudaLibXtDesc_t*) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D5EF12F: cufftExecute(fftHandleStruct*, void*, void*) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703== 
==646703== Use of uninitialised value of size 8
==646703==    at 0x4424300C: ??? (in /usr/lib/libcuda.so.465.31)
==646703==    by 0x43FE5391: ??? (in /usr/lib/libcuda.so.465.31)
==646703==    by 0x440ADFF4: ??? (in /usr/lib/libcuda.so.465.31)
==646703==    by 0x7D67ACE4: DSELaunch::proc(fftDynamicParameters const&, device const&, void*, void const*, unsigned int, Dim, Pitch, Pitch, unsigned long long, unsigned long long, unsigned long long, unsigned long long) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D614FD7: StridedMultiKernel::proc(fftDynamicParameters const&, device const&, void*, void const*, unsigned int, Dim, Pitch, Pitch, unsigned long long, unsigned long long, unsigned long long, unsigned long long) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D6514FE: Callback::proc(fftDynamicParameters const&, device const&, void*, void const*, unsigned int, Dim, Pitch, Pitch, unsigned long long, unsigned long long, unsigned long long, unsigned long long) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D61D02C: Queue::launch(device const&, fftDynamicParameters&, void*, void*, void const*, Pitch, Pitch, Pitch, unsigned int, Dim) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D6FA99C: fftDimensionCT::exec(device const&, fftDynamicParameters&, void*, void*, void const*) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D61A721: fftCooleyTukeyC2C::exec(void*, void*, void const*, fftDynamicParameters const&, device const&) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D5FD2F3: Visitors::Execute::operator()(Operation::Queue&) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D5EEFC1: cufftExecuteDescriptor(fftHandleStruct*, cudaLibXtDesc_t*, cudaLibXtDesc_t*) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D5EF12F: cufftExecute(fftHandleStruct*, void*, void*) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703== 
==646703== Use of uninitialised value of size 8
==646703==    at 0x44243010: ??? (in /usr/lib/libcuda.so.465.31)
==646703==    by 0x43FE5391: ??? (in /usr/lib/libcuda.so.465.31)
==646703==    by 0x440ADFF4: ??? (in /usr/lib/libcuda.so.465.31)
==646703==    by 0x7D67ACE4: DSELaunch::proc(fftDynamicParameters const&, device const&, void*, void const*, unsigned int, Dim, Pitch, Pitch, unsigned long long, unsigned long long, unsigned long long, unsigned long long) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D614FD7: StridedMultiKernel::proc(fftDynamicParameters const&, device const&, void*, void const*, unsigned int, Dim, Pitch, Pitch, unsigned long long, unsigned long long, unsigned long long, unsigned long long) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D6514FE: Callback::proc(fftDynamicParameters const&, device const&, void*, void const*, unsigned int, Dim, Pitch, Pitch, unsigned long long, unsigned long long, unsigned long long, unsigned long long) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D61D02C: Queue::launch(device const&, fftDynamicParameters&, void*, void*, void const*, Pitch, Pitch, Pitch, unsigned int, Dim) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D6FA99C: fftDimensionCT::exec(device const&, fftDynamicParameters&, void*, void*, void const*) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D61A721: fftCooleyTukeyC2C::exec(void*, void*, void const*, fftDynamicParameters const&, device const&) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D5FD2F3: Visitors::Execute::operator()(Operation::Queue&) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D5EEFC1: cufftExecuteDescriptor(fftHandleStruct*, cudaLibXtDesc_t*, cudaLibXtDesc_t*) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D5EF12F: cufftExecute(fftHandleStruct*, void*, void*) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703== 
==646703== Invalid read of size 8
==646703==    at 0x44243010: ??? (in /usr/lib/libcuda.so.465.31)
==646703==    by 0x43FE5391: ??? (in /usr/lib/libcuda.so.465.31)
==646703==    by 0x440ADFF4: ??? (in /usr/lib/libcuda.so.465.31)
==646703==    by 0x7D67ACE4: DSELaunch::proc(fftDynamicParameters const&, device const&, void*, void const*, unsigned int, Dim, Pitch, Pitch, unsigned long long, unsigned long long, unsigned long long, unsigned long long) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D614FD7: StridedMultiKernel::proc(fftDynamicParameters const&, device const&, void*, void const*, unsigned int, Dim, Pitch, Pitch, unsigned long long, unsigned long long, unsigned long long, unsigned long long) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D6514FE: Callback::proc(fftDynamicParameters const&, device const&, void*, void const*, unsigned int, Dim, Pitch, Pitch, unsigned long long, unsigned long long, unsigned long long, unsigned long long) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D61D02C: Queue::launch(device const&, fftDynamicParameters&, void*, void*, void const*, Pitch, Pitch, Pitch, unsigned int, Dim) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D6FA99C: fftDimensionCT::exec(device const&, fftDynamicParameters&, void*, void*, void const*) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D61A721: fftCooleyTukeyC2C::exec(void*, void*, void const*, fftDynamicParameters const&, device const&) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D5FD2F3: Visitors::Execute::operator()(Operation::Queue&) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D5EEFC1: cufftExecuteDescriptor(fftHandleStruct*, cudaLibXtDesc_t*, cudaLibXtDesc_t*) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D5EF12F: cufftExecute(fftHandleStruct*, void*, void*) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==  Address 0x18 is not stack'd, malloc'd or (recently) free'd
==646703== 
==646703== 
==646703== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==646703==  Access not within mapped region at address 0x18
==646703==    at 0x44243010: ??? (in /usr/lib/libcuda.so.465.31)
==646703==    by 0x43FE5391: ??? (in /usr/lib/libcuda.so.465.31)
==646703==    by 0x440ADFF4: ??? (in /usr/lib/libcuda.so.465.31)
==646703==    by 0x7D67ACE4: DSELaunch::proc(fftDynamicParameters const&, device const&, void*, void const*, unsigned int, Dim, Pitch, Pitch, unsigned long long, unsigned long long, unsigned long long, unsigned long long) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D614FD7: StridedMultiKernel::proc(fftDynamicParameters const&, device const&, void*, void const*, unsigned int, Dim, Pitch, Pitch, unsigned long long, unsigned long long, unsigned long long, unsigned long long) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D6514FE: Callback::proc(fftDynamicParameters const&, device const&, void*, void const*, unsigned int, Dim, Pitch, Pitch, unsigned long long, unsigned long long, unsigned long long, unsigned long long) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D61D02C: Queue::launch(device const&, fftDynamicParameters&, void*, void*, void const*, Pitch, Pitch, Pitch, unsigned int, Dim) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D6FA99C: fftDimensionCT::exec(device const&, fftDynamicParameters&, void*, void*, void const*) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D61A721: fftCooleyTukeyC2C::exec(void*, void*, void const*, fftDynamicParameters const&, device const&) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D5FD2F3: Visitors::Execute::operator()(Operation::Queue&) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D5EEFC1: cufftExecuteDescriptor(fftHandleStruct*, cudaLibXtDesc_t*, cudaLibXtDesc_t*) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==    by 0x7D5EF12F: cufftExecute(fftHandleStruct*, void*, void*) (in /home/sz/.cupy/callback_cache/cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so)
==646703==  If you believe this happened as a result of a stack
==646703==  overflow in your program's main thread (unlikely but
==646703==  possible), you can try to increase the size of the
==646703==  main thread stack using the --main-stacksize= flag.
==646703==  The main thread stack size used in this run was 8388608.
==646703== 
==646703== HEAP SUMMARY:
==646703==     in use at exit: 68,190,220 bytes in 72,927 blocks
==646703==   total heap usage: 147,982 allocs, 75,055 frees, 221,211,609 bytes allocated
==646703== 
==646703== LEAK SUMMARY:
==646703==    definitely lost: 0 bytes in 0 blocks
==646703==    indirectly lost: 0 bytes in 0 blocks
==646703==      possibly lost: 326,214 bytes in 1,175 blocks
==646703==    still reachable: 67,838,838 bytes in 71,747 blocks
==646703==         suppressed: 25,168 bytes in 5 blocks
==646703== Rerun with --leak-check=full to see details of leaked memory
==646703== 
==646703== Use --track-origins=yes to see where uninitialised values come from
==646703== For lists of detected and suppressed errors, rerun with: -s
==646703== ERROR SUMMARY: 9468 errors from 203 contexts (suppressed: 4 from 2)
```

</p>
</details>

**Comment by leofang** [comment]
> My system is archlinux. The cupy is installed from archlinuxcn/python-cupy.
> 
> After deleting `.cupy` folder, I got a warning before the segmentation fault.
> 
> ```
> 
> nvprune warning : No device code that matched architecture, so stripped out all device code
> 
> ```

@szsdk This is interesting 🤔 Looks like cufft's static library does not contain device code for sm61. I will do a few checks when I can access my workstation, and in the meanwhile could you check this: go to `~/.cupy/callback_cache/`, and there should be at least 1 static library named `libcufft_static_xxxxx_sm61.a`. What is the file size of it? I guess it is very small.

**Comment by szsdk** [comment]
@leofang These are files in my folder:
```
.rwxr-xr-x 7.8M sz 31 May 17:03 cupy_callback_48c7d38101a2a47abcd2b647b8c2cc81.cpython-39-x86_64-linux-gnu.so
.rw-r--r--  18M sz 31 May 17:03 libcufft_static_10402_sm61.a
```

**Comment by leofang** [comment]
Thanks, @szsdk. I will send a patch to fix this.

On CUDA 11.3:
```python
import os
import sys
import subprocess
import cupy as cp


sm_list = cp.cuda.nvrtc.getSupportedArchs()
print(sm_list)
for i in sm_list:
    print(f"on sm_{i}...")
    #p = subprocess.run(['echo', str(i)])
    p = subprocess.run(['nvprune', '-arch', f'sm_{i}', '/usr/local/cuda-11.3/lib64/libcufft_static.a', '-o', 'temp.a'], env=os.environ)
    if p.stderr:
        print(p.stderr)
    else:
        print("OK")
```
Output:
```
(35, 37, 50, 52, 53, 60, 61, 62, 70, 72, 75, 80, 86)
on sm_35...
OK
on sm_37...
nvprune warning : No device code that matched architecture, so stripped out all device code
OK
on sm_50...
OK
on sm_52...
nvprune warning : No device code that matched architecture, so stripped out all device code
OK
on sm_53...
nvprune warning : No device code that matched architecture, so stripped out all device code
OK
on sm_60...
OK
on sm_61...
nvprune warning : No device code that matched architecture, so stripped out all device code
OK
on sm_62...
nvprune warning : No device code that matched architecture, so stripped out all device code
OK
on sm_70...
OK
on sm_72...
nvprune warning : No device code that matched architecture, so stripped out all device code
OK
on sm_75...
OK
on sm_80...
OK
on sm_86...
OK
```

**Comment by leofang** [comment]
@szsdk I sent a patch (#5304). But I have another question: Do you get any stdout/stderr outputs other than the nvprune warning and the segfault? If `libcufft_static_10402_sm61.a` does not contain any device code, shouldn't `nvcc` fail at the linking stage? I am a bit concerned that we get a segfault directly instead of an error.

**Comment by leofang** [comment]
> But I have another question: Do you get any stdout/stderr outputs other than the nvprune warning and the segfault? If `libcufft_static_10402_sm61.a` does not contain any device code, shouldn't `nvcc` fail at the linking stage? I am a bit concerned that we get a segfault directly instead of an error.

I ran a local test myself and nvcc did not complain...Very strange.

**Comment by szsdk** [comment]
@leofang The warning and segfault were all I got.

**Comment by szsdk** [comment]
@leofang  I have access to another NVIDIA 1080 machine. I get the same warning (copy 9.10), but not segfault.

**Comment by leofang** [comment]
Hmm this is strange...Is it with or without my patch? Have you checked if the output is correct?

**Comment by szsdk** [comment]
Let me clarify.
This is an another NVIDIA 1080 card. I installed cupy with `pip install cupy`. The version of cupy is 9.1.0, without your patch.
This is my test code.
```python
import numpy as np
import cupy as cp

code = r'''
__device__ cufftComplex CB_ConvertInput(
    void *dataIn,
    size_t offset,
    void *callerInfo,
    void *sharedPtr) {
            return make_float2(1.0, 0.0);
}

__device__ cufftCallbackLoadC d_loadCallbackPtr = CB_ConvertInput;
'''

in_arr = cp.random.rand(12, dtype=np.float32)

with cp.fft.config.set_cufft_callbacks(cb_load=code):
    out_arr = cp.fft.fft(in_arr)

print(cp.__version__)
print(out_arr)
print(cp.fft.fft(cp.ones(12)))
```
This is the output.
```
/home/szsdk/anaconda3/lib/python3.8/site-packages/cupy/fft/_fft.py:149: UserWarning: cuFFT plan cache is disabled on CUDA 11.1 due to a known bug, so performance may be degraded. The bug is fixed on CUDA 11.2+.
  cache = get_plan_cache()
9.1.0
[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j]
[12.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j
  0.+0.j  0.+0.j  0.+0.j]
```
I do not think I get the correct answer. From my understand, the answer should be the last line. I am new to this callback function. Please correct me if I am wrong.

**Comment by szsdk** [comment]
I get the same result with another 980 machine. Same cupy installation.
```python
9.1.0
[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j]
[12.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j
  0.+0.j  0.+0.j  0.+0.j]
```

**Comment by leofang** [comment]
Yes, you're right: for the test input (a flat signal) we should get a single nonzero value at the zero frequency. It's nice that you have access to both 980 and 1080! If we can fix one (#5304) we fix them all. They are the same corner case.

**Comment by leofang** [comment]
@szsdk Could you kindly do me a favor? I need more tests done for your particular environment (Arch Linux + CUDA 11.x + gfx 980 / 1080). Looks like when you install CUDA from system package manager, the CUDA samples are installed in `/opt/cuda/samples/` (says [here](https://wiki.archlinux.org/title/GPGPU#CUDA)). I need you to compile and run the test code. For a runfile CUDA installation, the target sample is in `/usr/local/cuda-11.3/samples/7_CUDALibraries/simpleCUFFT_callback/`, but I don't know if the relative path is the same for Arch Linux or not. I need the full output of each step (go to that test directory):
1. `make`
2. `./simpleCUFFT_callback`

Let me know if you can successfully run it or not.

**Comment by szsdk** [comment]
Sure. This is my output.
```
# make
>>> GCC Version is greater or equal to  5.3.0 <<<
/opt/cuda/bin/nvcc -ccbin g++ -I../../common/inc -m64 -dc -std=c++11 --threads 0 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_86,code=sm_86 -gencode arch=compute_86,code=compute_86 -o simpleCUFFT_callback.o -c simpleCUFFT_callback.cu
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/opt/cuda/bin/nvcc -ccbin g++ -m64 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_86,code=sm_86 -gencode arch=compute_86,code=compute_86 -o simpleCUFFT_callback simpleCUFFT_callback.o -L/usr/lib/x86_64-linux-gnu -L/usr/lib64 -lcufft_static -lculibos
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
mkdir -p ../../bin/x86_64/linux/release
cp simpleCUFFT_callback ../../bin/x86_64/linux/release

# ./simpleCUFFT_callback
[simpleCUFFT_callback] is starting...
GPU Device 0: "Pascal" with compute capability 6.1

Transforming signal cufftExecC2C
Transforming signal back cufftExecC2C
```

**Comment by leofang** [comment]
Thanks, looks like it should just work on Arch Linux.

**Comment by szsdk** [comment]
@leofang  I tested both my 1080 machines. And the new patch (cf78fbf86eec6a8a4baef2d5628bb96130c4879) works on both.
Cheers.
But I cannot compile cupy from source on my 980 machine. It complains that cudnn.h is missing. The dependency on cudnn is optional, isn't it?

**Comment by leofang** [comment]
Thanks, @szsdk. So #5304 should be good to go. 

Yeah cuDNN is optional. Could you post the full log for the failed build? The actual cause might be buried somewhere.

**Comment by szsdk** [comment]
[install.log](https://github.com/cupy/cupy/files/6588249/install.log)
I attached the output of my installation. @leofang

**Comment by leofang** [comment]
@szsdk Could you clear all files and rebuild? `git clean -fdx` I think there are some leftover files from a previous build that are incompatible with your current environment.

**Comment by szsdk** [comment]
@leofang Thanks, everything works now on the 980 workstation.
