### ISSUE TITLE
NcclError for multiprocessing communication

### ISSUE THREAD

**Issue by husisy** [cupy/cupy#5300]
I am trying to run multiple processes on multiple gpus: `proc0` on `gpu0`, `proc1` on `gpu1`, and communicate (send and recv) using `nccl`.

The code snippet for `proc0` is as follow:

```Python
import cupy as cp
import cupy.cuda.nccl
import pickle
rank = 0
id_ = cp.cuda.nccl.get_unique_id() #(tuple,int)
with open('id_.pkl', 'wb') as fid:
    pickle.dump(id_,fid)
comm = cp.cuda.nccl.NcclCommunicator(2, id_, rank) #NcclError: NCCL_ERROR_INVALID_USAGE
# with cp.cuda.device(rank):
#     cp0 = cp.array([1,2,3], dtype=cp.float32)
#     comm.send(cp0.data.ptr, cp0.shape[0], cp.cuda.nccl.NCCL_FLOAT32, 1, cp.cuda.Stream.null.ptr)
```

The code snippet for `proc1` is as follow:

```Python
import cupy as cp
import cupy.cuda.nccl
import pickle
rank = 1
with open('id_.pkl','rb') as fid:
    id_ = pickle.load(fid)
comm = cp.cuda.nccl.NcclCommunicator(2, id_, rank) #NcclError: NCCL_ERROR_INVALID_USAGE
# with cp.cuda.device(rank):
#     cp0 = cp.array([0,0,0], dtype=cp.float32)
#     comm.recv(cp0.data.ptr, cp0.shape[0], cp.cuda.nccl.NCCL_FLOAT32, 0, cp.cuda.Stream.null.ptr)
```

According to the [nvidia/nccl-examples](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/examples.html#example-2-one-device-per-process-or-thread), two processes should have the same `id_`, so I save the `id_` in `proc0` and load it in `proc1`, but get this error when calling `cp.cuda.nccl.NcclCommunicator()`

```bash
----> 7 comm = cp.cuda.nccl.NcclCommunicator(2, id_, rank) #NcclError: NCCL_ERROR_INVALID_USAGE
cupy_backends/cuda/libs/nccl.pyx in cupy_backends.cuda.libs.nccl.NcclCommunicator.__init__()
cupy_backends/cuda/libs/nccl.pyx in cupy_backends.cuda.libs.nccl.check_status()
NcclError: NCCL_ERROR_INVALID_USAGE: invalid usage
```

I have tried these solution

1. run the unittest `tests/cupy_tests/cuda_tests/test_nccl.py/test_send_recv()` which is one process and 2 gpus: pass with no error
2. different version combination `cupy-v9.1, nccl-v2.9.9`, `cupy-v9.0, nccl-v2.9.8`, `cupy-v9.0, nccl-v2.9.6`: fail with same `NcclError`

`cupy.show_config()` print out the following information

```bash
# cp.show_config() #on cupy-v9.0, nccl-v2.9.8
OS                           : Linux-4.15.0-112-generic-x86_64-with-glibc2.10
CuPy Version                 : 9.0.0
NumPy Version                : 1.19.2
SciPy Version                : 1.6.2
Cython Build Version         : 0.29.23
Cython Runtime Version       : 0.29.23
CUDA Root                    : /home/zhangc/miniconda3/envs/cuda112
CUDA Build Version           : 11020
CUDA Driver Version          : 11020
CUDA Runtime Version         : 11020
cuBLAS Version               : 11401
cuFFT Version                : 10401
cuRAND Version               : 10203
cuSOLVER Version             : (11, 1, 0)
cuSPARSE Version             : 11401
NVRTC Version                : (11, 2)
Thrust Version               : 101000
CUB Build Version            : 101000
Jitify Build Version         : <unknown>
cuDNN Build Version          : 8100
cuDNN Version                : 8100
NCCL Build Version           : 20906
NCCL Runtime Version         : 20908
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : Tesla V100-DGXS-32GB
Device 0 Compute Capability  : 70
Device 0 PCI Bus ID          : 0000:07:00.0
Device 1 Name                : Tesla V100-DGXS-32GB
Device 1 Compute Capability  : 70
Device 1 PCI Bus ID          : 0000:08:00.0
Device 2 Name                : Tesla V100-DGXS-32GB
Device 2 Compute Capability  : 70
Device 2 PCI Bus ID          : 0000:0E:00.0
Device 3 Name                : Tesla V100-DGXS-32GB
Device 3 Compute Capability  : 70
Device 3 PCI Bus ID          : 0000:0F:00.0
```

my python environment is built with the following conda command

```bash
conda create -y -n cuda112
conda install -y -n cuda112 -c conda-forge cudatoolkit=11.2 cython ipython pytest matplotlib h5py pandas pylint pillow protobuf scipy requests tqdm opt_einsum cupy nccl=2.9
conda activate cuda112
```

**Comment by leofang** [comment]
I think when you create the communicator, it should be within the `cp.cuda.Device(rank)` block; that is, on different devices for each rank. Could you give it a try?

**Comment by husisy** [comment]
Thanks, it works. Below is the complete code:

```Python
# proc0
import cupy as cp
import cupy.cuda.nccl
import pickle
rank = 0
with cp.cuda.Device(rank):
    id_ = cp.cuda.nccl.get_unique_id() #(tuple,int)
    with open('id_.pkl', 'wb') as fid:
        pickle.dump(id_,fid)
    comm = cp.cuda.nccl.NcclCommunicator(2, id_, rank)
    cp0 = cp.array([1,2,3], dtype=cp.float32)
    comm.send(cp0.data.ptr, cp0.shape[0], cp.cuda.nccl.NCCL_FLOAT32, 1, cp.cuda.Stream.null.ptr)
```

```Python
# proc1
import cupy as cp
import cupy.cuda.nccl
import pickle
rank = 1
with cp.cuda.Device(rank):
    with open('id_.pkl','rb') as fid:
        id_ = pickle.load(fid)
    comm = cp.cuda.nccl.NcclCommunicator(2, id_, rank)
    cp0 = cp.array([0,0,0], dtype=cp.float32)
    comm.recv(cp0.data.ptr, cp0.shape[0], cp.cuda.nccl.NCCL_FLOAT32, 0, cp.cuda.Stream.null.ptr)
```

**Comment by leofang** [comment]
Glad to know!
