### ISSUE TITLE
Problems clearing cuda memory pool after out of memory exception

### ISSUE THREAD

**Issue by pptman** [cupy/cupy#6756]
### Description

If I receive an out of memory exception from cupy, then I am unable to clear the memory pool using the free_all_blocks() method.  The code below demonstrates this issue by performing an fft on 3d arrays of increasing size until the out of memory exception occurs (at N=512 on my 4GB GTX1650 ).  Even if the size of the problem is reduced, the memory pool is still not cleared.  Note that the fft plan_cache size is set to zero but as it is probably the fft that is causing the out of memory error might this be a plan or working arrays that are left around?

### To Reproduce

```py
import numpy as np
import cupy as cp

def test(N):
    try:
        datain = cp.ones((N, 512, 512))
        dataout = cp.fft.rfft(datain, axis=0).get()
        del datain
    except Exception as e:
        print(f'exception received {e}')
        if 'datain' in locals(): del datain
    print(f'test size = {N}')
    print(f'\tcupy memory used before clearing: {cp.get_default_memory_pool().used_bytes() / 1e9} GB')
    print(f'\tcupy memory total before clearing: {cp.get_default_memory_pool().total_bytes() / 1e9} GB')
    cp.get_default_memory_pool().free_all_blocks()
    print(f'\tcupy memory used after clearing: {cp.get_default_memory_pool().used_bytes() / 1e9} GB')
    print(f'\tcupy memory total after clearing: {cp.get_default_memory_pool().total_bytes() / 1e9} GB')

cp.fft.config.get_plan_cache().set_size(0)

for n in [16, 32, 64, 128, 256, 512, 1024, 32]:
    print(f'\n\tcupy memory used before running: {cp.get_default_memory_pool().used_bytes() / 1e9} GB')
    print(f'\tcupy memory total before running: {cp.get_default_memory_pool().total_bytes() / 1e9} GB')
    test(n)
```

### Installation

Wheel (`pip install cupy-***`)

### Environment

```
OS                           : Windows-10-10.0.19042-SP0
Python Version               : 3.9.5
CuPy Version                 : 10.4.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.22.1
SciPy Version                : 1.8.0
Cython Build Version         : 0.29.28
Cython Runtime Version       : None
CUDA Root                    : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3
nvcc PATH                    : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin\nvcc.EXE
CUDA Build Version           : 11030
CUDA Driver Version          : 11030
CUDA Runtime Version         : 11030
cuBLAS Version               : (available)
cuFFT Version                : 10402
cuRAND Version               : 10204
cuSOLVER Version             : (11, 1, 2)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 3)
Thrust Version               : 101100
CUB Build Version            : 101100
Jitify Build Version         : 4a37de0
cuDNN Build Version          : (not loaded; try `import cupy.cuda.cudnn` first)
cuDNN Version                : (not loaded; try `import cupy.cuda.cudnn` first)
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce GTX 1650
Device 0 Compute Capability  : 75
Device 0 PCI Bus ID          : 0000:01:00.0
```

**Comment by kmaehashi** [comment]
`locals()` creates a dict containing references to all local variables and stores it into the stack frame object (which users don't have control of when to destroy). The problem disappeared for me if I rewrite the reproducer with:

```py
datain = None
try:
    ...
except Exception as e:
    ...
finally:
    del datain
```

**Comment by pptman** [comment]
Thanks for the hints.  Both suggestions work, but actually my original application I want to re-raise the exception and then this doesn't work again, even though, or maybe because, the `finally` statement executes before the exception is re-raised.

```
import numpy as np
import cupy as cp

def test(N):
    datain = None
    try:
        datain = cp.ones((N, 512, 512))
        dataout = cp.fft.rfft(datain, axis=0).get()
    except Exception as e:
        print(f'exception received {e}')
        raise
    finally:
        datain = None
        print(f'    cupy memory used before clearing: {cp.get_default_memory_pool().used_bytes() / 1e9} GB')
        print(f'    cupy memory total before clearing: {cp.get_default_memory_pool().total_bytes() / 1e9} GB')
        cp.get_default_memory_pool().free_all_blocks()
        print(f'    cupy memory used after clearing: {cp.get_default_memory_pool().used_bytes() / 1e9} GB')
        print(f'    cupy memory total after clearing: {cp.get_default_memory_pool().total_bytes() / 1e9} GB')

cp.fft.config.get_plan_cache().set_size(0)

for n in [16, 32, 64, 128, 256, 512, 1024, 32]:
    print(f'test size = {n}')
    print(f'    cupy memory used before running: {cp.get_default_memory_pool().used_bytes() / 1e9} GB')
    print(f'    cupy memory total before running: {cp.get_default_memory_pool().total_bytes() / 1e9} GB')
    try:
        test(n)
    except Exception as e:
        print(f'Exception re-raised: {e}')
```
(EDIT(seberg): fix code that had invalid chars.)

The memory is eventually cleared when `free_all_blocks()` is called in the final smaller `n=32` run.  Remove the `raise` line and the memory is cleared immediately by the finally section as the exception occurs.

Incidentally, if I implement the same code using `pytorch` I can still clear the cuda memory even though I am re-raising the exception.

**Comment by seberg** [comment]
Closing issue, I tried to reproduce the last example, and it frees all memory immediately. Plausibly something in Python or CuPy was improved in the meantime.
