### ISSUE TITLE
FFT test fails when parallelized

### ISSUE THREAD

**Issue by gwtnb** [cupy/cupy#733]
When running test in parallel using pytest-xdist, FFT test fails.

```
cupy/testing/helper.py:502: in test_func
    impl(self, *args, **kw)
cupy/testing/helper.py:105: in test_func
    accept_error=accept_error)
cupy/testing/helper.py:51: in _check_cupy_numpy_error
    self.fail('Only cupy raises error\n\n' + cupy_tb)
E   AssertionError: Only cupy raises error
E   
E   Traceback (most recent call last):
E     File "/home/user/work/chainer/cupy/cupy/testing/helper.py", line 26, in _call_func
E       result = impl(self, *args, **kw)
E     File "/home/user/work/chainer/cupy/tests/cupy_tests/fft_tests/test_fft.py", line 24, in test_fft
E       out = xp.fft.fft(a, n=self.n, norm=self.norm)
E     File "/home/user/work/chainer/cupy/cupy/fft/fft.py", line 27, in fft
E       return cufft.fft(a, (n,), (axis,), norm, cupy.cuda.cufft.CUFFT_FORWARD)
E     File "/home/user/work/chainer/cupy/cupy/cufft.py", line 139, in fft
E       a = _convert_dtype(a, value_type)
E     File "/home/user/work/chainer/cupy/cupy/cufft.py", line 14, in _convert_dtype
E       return a.astype(np.complex128)
E     File "cupy/core/core.pyx", line 276, in cupy.core.core.ndarray.astype
E       cpdef ndarray astype(
E     File "cupy/core/core.pyx", line 349, in cupy.core.core.ndarray.astype
E       elementwise_copy(self, newarray)
E     File "cupy/core/core.pyx", line 1877, in cupy.core.core.elementwise_copy
E       return _elementwise_copy(*args, **kwargs)
E     File "cupy/core/elementwise.pxi", line 821, in cupy.core.core.ufunc.__call__
E       kern.linear_launch(indexer.size, inout_args)
E     File "cupy/cuda/function.pyx", line 158, in cupy.cuda.function.Function.linear_launch
E       _launch(self.ptr,
E     File "cupy/cuda/function.pyx", line 127, in cupy.cuda.function._launch
E       driver.launchKernel(
E     File "cupy/cuda/driver.pyx", line 184, in cupy.cuda.driver.launchKernel
E       check_status(status)
E     File "cupy/cuda/driver.pyx", line 72, in cupy.cuda.driver.check_status
E       raise CUDADriverError(status)
E   cupy.cuda.driver.CUDADriverError: CUDA_ERROR_INVALID_CONTEXT: invalid device context
------------------------------------------------------------------------------------------- Captured stdout call -------------------------------------------------------------------------------------------
dtype is <class 'numpy.float64'>
```

When the FFT test is eliminated,

```sh
rm -r tests/cupy_tests/fft_tests
```

it runs without error.

**Comment by gwtnb** [comment]
I noticed that it passes when the number of processes is less than four.

**Comment by gwtnb** [comment]
I used the following command:

```sh
pytest -m 'not slow' -n 4
```

**Comment by not522** [comment]
In my enviroｎment, the parallelized test is failed but the reported error is not reproduced.
I think the parallelized test is broken due to side effects of TestStream.test_del in cuda_tests/test_stream.py.
https://github.com/cupy/cupy/blob/f2b59d6e1da8fa726064155678e332b7816bf120/tests/cupy_tests/cuda_tests/test_stream.py#L22-L31
When the test function is eliminated, the test is passed.

**Comment by not522** [comment]
I think this problem was fixed by #917.
Is it OK with your environment?

**Comment by gwtnb** [comment]
> Is it OK with your environment?

Yes. Thank you for investigation.
