### ISSUE TITLE
Lazy loading not working in wheels

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#8108]
When trying #7620, I found that lazy loading is not working when installed via wheels.

```
$ pip install cupy-cuda11x --pre -U -f https://pip.cupy.dev/pre
$ python -c 'import cupy'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/cupy/__init__.py", line 17, in <module>
    from cupy import _core  # NOQA
  File "/usr/local/lib/python3.9/site-packages/cupy/_core/__init__.py", line 3, in <module>
    from cupy._core import core  # NOQA
ImportError: libcublas.so.11: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/cupy/__init__.py", line 19, in <module>
    raise ImportError(f'''
ImportError: 
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

Original error:
  ImportError: libcublas.so.11: cannot open shared object file: No such file or directory
================================================================
```

It looks all CUDA toolkit libraries are linked in all Cython extensions, even for modules that do not use CUDA symbols at all, e.g. [`flags.pyx`](https://github.com/cupy/cupy/blob/17372145ed4abe2261a55f0224951efa47544d64/cupy/_core/flags.pyx):

```
# ldd cupy/_core/flags.cpython-39-x86_64-linux-gnu.so 
	linux-vdso.so.1 (0x00007ffc46db7000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f480bf8a000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f480bf85000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f480bf80000)
	libcublas.so.11 => not found
	libcufft.so.10 => not found
	libcurand.so.10 => not found
	libcusparse.so.11 => not found
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f480b9e6000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f480be9f000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f480be7f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f480b805000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f480bf97000)
```

The problem does not happen if installed locally (`pip install -e . -v`) on my environment (Ubuntu 22.04). I guess different linker options are necessary for CentOS 7 which is used to build wheels?

**Comment by leofang** [comment]
Maybe we need to pass "-Wl,--as-needed" at compile time? IIRC not all gcc on all distros would do that by default.

**Comment by kmaehashi** [comment]
Thank you Leo, that did the trick!
https://github.com/cupy/cupy-release-tools/pull/373
