### ISSUE TITLE
CUDA-capable device detection takes over 10 seconds

### ISSUE THREAD

**Issue by adrinjalali** [cupy/cupy#8152]
### Description

I have a laptop with two GPUs, one integrated and one dedicated. However, I've disabled NVIDIA drivers in my sessions to save power, in archlinux.

However, NVIDIA driver packages are installed.

It takes over 10 seconds to detect the NVIDIA card is not available.

### To Reproduce

This is a minimal reproducible on my system:

```py
$ /bin/time python -c "import cupy; cupy.ones(10)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/adrin/miniforge3/envs/sklearn/lib/python3.10/site-packages/cupy/_creation/basic.py", line 181, in ones
    a = cupy.ndarray(shape, dtype, order=order)
  File "cupy/_core/core.pyx", line 132, in cupy._core.core.ndarray.__new__
  File "cupy/_core/core.pyx", line 220, in cupy._core.core._ndarray_base._init
  File "cupy/cuda/memory.pyx", line 738, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1424, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1444, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/device.pyx", line 40, in cupy.cuda.device.get_device_id
  File "cupy_backends/cuda/api/runtime.pyx", line 202, in cupy_backends.cuda.api.runtime.getDevice
  File "cupy_backends/cuda/api/runtime.pyx", line 146, in cupy_backends.cuda.api.runtime.check_status
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorNoDevice: no CUDA-capable device is detected
Command exited with non-zero status 1
11.19user 6.75system 0:20.47elapsed 87%CPU (0avgtext+0avgdata 103668maxresident)k
0inputs+0outputs (0major+264586minor)pagefaults 0swaps
```

### Installation

Conda-Forge (`conda install ...`)

### Environment

```py
$ python -c "import cupy; cupy.show_config()"
Traceback (most recent call last):
  File "cupy_backends/cuda/_softlink.pyx", line 25, in cupy_backends.cuda._softlink.SoftLink.__init__
  File "/home/adrin/miniforge3/envs/sklearn/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.12: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/adrin/miniforge3/envs/sklearn/lib/python3.10/site-packages/cupy/__init__.py", line 912, in show_config
    _sys.stdout.write(str(_cupyx.get_runtime_info(full=_full)))
  File "/home/adrin/miniforge3/envs/sklearn/lib/python3.10/site-packages/cupyx/_runtime.py", line 319, in get_runtime_info
    return _RuntimeInfo(full=full)
  File "/home/adrin/miniforge3/envs/sklearn/lib/python3.10/site-packages/cupyx/_runtime.py", line 123, in __init__
    self.cuda_local_runtime_version = _eval_or_error(
  File "/home/adrin/miniforge3/envs/sklearn/lib/python3.10/site-packages/cupyx/_runtime.py", line 21, in _eval_or_error
    return func()
  File "/home/adrin/miniforge3/envs/sklearn/lib/python3.10/site-packages/cupy/cuda/__init__.py", line 113, in get_local_runtime_version
    return runtime._getLocalRuntimeVersion()
  File "cupy_backends/cuda/api/runtime.pyx", line 187, in cupy_backends.cuda.api.runtime._getLocalRuntimeVersion
  File "cupy_backends/cuda/api/runtime.pyx", line 189, in cupy_backends.cuda.api.runtime._getLocalRuntimeVersion
  File "cupy_backends/cuda/api/_runtime_softlink.pxi", line 20, in cupy_backends.cuda.api.runtime.initialize
  File "cupy_backends/cuda/api/_runtime_softlink.pxi", line 25, in cupy_backends.cuda.api.runtime._initialize
  File "cupy_backends/cuda/api/_runtime_softlink.pxi", line 53, in cupy_backends.cuda.api.runtime._get_softlink
  File "cupy_backends/cuda/_softlink.pyx", line 32, in cupy_backends.cuda._softlink.SoftLink.__init__
RuntimeError: CuPy failed to load libcudart.so.12: OSError: libcudart.so.12: cannot open shared object file: No such file or directory
```

### Additional Information

I'll try to give all the info I think is relevant:

Hardware info:

```
$ lspci
00:00.0 Host bridge: Intel Corporation 8th Gen Core Processor Host Bridge/DRAM Registers (rev 07)
00:01.0 PCI bridge: Intel Corporation 6th-10th Gen Core Processor PCIe Controller (x16) (rev 07)
00:02.0 VGA compatible controller: Intel Corporation CoffeeLake-H GT2 [UHD Graphics 630]
00:04.0 Signal processing controller: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Thermal Subsystem (rev 07)
00:08.0 System peripheral: Intel Corporation Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th/8th Gen Core Processor Gaussian Mixture Model
00:12.0 Signal processing controller: Intel Corporation Cannon Lake PCH Thermal Controller (rev 10)
00:14.0 USB controller: Intel Corporation Cannon Lake PCH USB 3.1 xHCI Host Controller (rev 10)
00:14.2 RAM memory: Intel Corporation Cannon Lake PCH Shared SRAM (rev 10)
00:15.0 Serial bus controller: Intel Corporation Cannon Lake PCH Serial IO I2C Controller #0 (rev 10)
00:16.0 Communication controller: Intel Corporation Cannon Lake PCH HECI Controller (rev 10)
00:1b.0 PCI bridge: Intel Corporation Cannon Lake PCH PCI Express Root Port #17 (rev f0)
00:1b.4 PCI bridge: Intel Corporation Cannon Lake PCH PCI Express Root Port #21 (rev f0)
00:1c.0 PCI bridge: Intel Corporation Cannon Lake PCH PCI Express Root Port #1 (rev f0)
00:1d.0 PCI bridge: Intel Corporation Cannon Lake PCH PCI Express Root Port #9 (rev f0)
00:1d.6 PCI bridge: Intel Corporation Cannon Lake PCH PCI Express Root Port #15 (rev f0)
00:1e.0 Communication controller: Intel Corporation Cannon Lake PCH Serial IO UART Host Controller (rev 10)
00:1f.0 ISA bridge: Intel Corporation Cannon Lake LPC Controller (rev 10)
00:1f.3 Audio device: Intel Corporation Cannon Lake PCH cAVS (rev 10)
00:1f.4 SMBus: Intel Corporation Cannon Lake PCH SMBus Controller (rev 10)
00:1f.5 Serial bus controller: Intel Corporation Cannon Lake PCH SPI Controller (rev 10)
00:1f.6 Ethernet controller: Intel Corporation Ethernet Connection (7) I219-V (rev 10)
01:00.0 VGA compatible controller: NVIDIA Corporation TU117M [GeForce GTX 1650 Mobile / Max-Q] (rev a1)
01:00.1 Audio device: NVIDIA Corporation Device 10fa (rev a1)
02:00.0 Non-Volatile memory controller: Sandisk Corp SanDisk Extreme Pro / WD Black SN750 / PC SN730 / Red SN700 NVMe SSD
04:00.0 PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 4C 2018] (rev 06)
05:00.0 PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 4C 2018] (rev 06)
05:01.0 PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 4C 2018] (rev 06)
05:02.0 PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 4C 2018] (rev 06)
05:04.0 PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 4C 2018] (rev 06)
06:00.0 System peripheral: Intel Corporation JHL7540 Thunderbolt 3 NHI [Titan Ridge 4C 2018] (rev 06)
2c:00.0 USB controller: Intel Corporation JHL7540 Thunderbolt 3 USB Controller [Titan Ridge 4C 2018] (rev 06)
52:00.0 Network controller: Intel Corporation Wi-Fi 6 AX200 (rev 1a)
53:00.0 SD Host controller: Genesys Logic, Inc GL9755 SD Host Controller
```

Installed system packages:

```
$ pacman -Ss | grep -i "nvidia\|cuda" | grep -i installed
extra/nvidia 545.29.06-14 [installed: 545.29.06-12]
extra/nvidia-settings 545.29.06-1 [installed]
extra/nvidia-utils 545.29.06-1 [installed]
extra/opencl-nvidia 545.29.06-1 [installed]
multilib/lib32-nvidia-utils 545.29.06-1 [installed]
```

Conda environment:

<details>

```
mamba list
List of packages in environment: "/home/adrin/miniforge3/envs/sklearn"

  Name                           Version       Build                      Channel    
───────────────────────────────────────────────────────────────────────────────────────
  _libgcc_mutex                  0.1           conda_forge                conda-forge
  _openmp_mutex                  4.5           2_kmp_llvm                 conda-forge
  alabaster                      0.7.13        pyhd8ed1ab_0               conda-forge
  alsa-lib                       1.2.10        hd590300_0                 conda-forge
  annotated-types                0.6.0         pyhd8ed1ab_0               conda-forge
  aom                            3.7.1         h59595ed_0                 conda-forge
  appdirs                        1.4.4         pyh9f0ad1d_0               conda-forge
  archspec                       0.2.2         pyhd8ed1ab_0               conda-forge
  asttokens                      2.4.1         pyhd8ed1ab_0               conda-forge
  attr                           2.5.1         h166bdaf_1                 conda-forge
  babel                          2.13.1        pyhd8ed1ab_0               conda-forge
  binutils                       2.40          hdd6e379_0                 conda-forge
  binutils_impl_linux-64         2.40          hf600244_0                 conda-forge
  binutils_linux-64              2.40          hbdbef99_2                 conda-forge
  black                          23.3.0        py310hff52083_1            conda-forge
  blosc                          1.21.5        h0f2a231_0                 conda-forge
  boltons                        23.1.1        pyhd8ed1ab_0               conda-forge
  brotli                         1.1.0         hd590300_1                 conda-forge
  brotli-bin                     1.1.0         hd590300_1                 conda-forge
  brotli-python                  1.1.0         py310hc6cd4ac_1            conda-forge
  brunsli                        0.1           h9c3ff4c_0                 conda-forge
  bzip2                          1.0.8         hd590300_5                 conda-forge
  c-ares                         1.25.0        hd590300_0                 conda-forge
  c-blosc2                       2.11.3        hb4ffafa_0                 conda-forge
  c-compiler                     1.7.0         hd590300_0                 conda-forge
  ca-certificates                2023.11.17    hbcca054_0                 conda-forge
  cachecontrol                   0.13.1        pyhd8ed1ab_0               conda-forge
  cachecontrol-with-filecache    0.13.1        pyhd8ed1ab_0               conda-forge
  cachy                          0.3.0         pyhd8ed1ab_1               conda-forge
  cairo                          1.18.0        h3faef2a_0                 conda-forge
  certifi                        2023.11.17    pyhd8ed1ab_0               conda-forge
  cffi                           1.16.0        py310h2fee648_0            conda-forge
  cfgv                           3.3.1         pyhd8ed1ab_0               conda-forge
  charls                         2.4.2         h59595ed_0                 conda-forge
  charset-normalizer             3.3.2         pyhd8ed1ab_0               conda-forge
  click                          8.1.7         unix_pyh707e725_0          conda-forge
  click-default-group            1.2.4         pyhd8ed1ab_0               conda-forge
  clikit                         0.6.2         pyhd8ed1ab_2               conda-forge
  colorama                       0.4.6         pyhd8ed1ab_0               conda-forge
  comm                           0.1.4         pyhd8ed1ab_0               conda-forge
  compilers                      1.7.0         ha770c72_0                 conda-forge
  conda                          23.11.0       py310hff52083_1            conda-forge
  conda-libmamba-solver          23.12.0       pyhd8ed1ab_0               conda-forge
  conda-lock                     2.4.2         pyhd8ed1ab_0               conda-forge
  conda-package-handling         2.2.0         pyh38be061_0               conda-forge
  conda-package-streaming        0.9.0         pyhd8ed1ab_0               conda-forge
  contourpy                      1.2.0         py310hd41b1e2_0            conda-forge
  crashtest                      0.4.1         pyhd8ed1ab_0               conda-forge
  cryptography                   41.0.7        py310hb8475ec_1            conda-forge
  cuda-nvrtc                     12.3.107      hd3aeb46_0                 conda-forge
  cuda-version                   12.3          h32bc705_2                 conda-forge
  cupy                           13.0.0        py310h7aad9d2_2            conda-forge
  cupy-core                      13.0.0        py310had4011e_2            conda-forge
  cxx-compiler                   1.7.0         h00ab1b0_0                 conda-forge
  cycler                         0.12.1        pyhd8ed1ab_0               conda-forge
  cython                         3.0.8         py310hc6cd4ac_0            conda-forge
  dataclasses                    0.8           pyhc8e2a94_3               conda-forge
  dav1d                          1.2.1         hd590300_0                 conda-forge
  dbus                           1.13.6        h5008d03_3                 conda-forge
  debugpy                        1.8.0         py310hc6cd4ac_1            conda-forge
  decorator                      5.1.1         pyhd8ed1ab_0               conda-forge
  distlib                        0.3.7         pyhd8ed1ab_0               conda-forge
  distro                         1.9.0         pyhd8ed1ab_0               conda-forge
  docutils                       0.20.1        py310hff52083_2            conda-forge
  ensureconda                    1.4.3         pyhd8ed1ab_0               conda-forge
  exceptiongroup                 1.2.0         pyhd8ed1ab_0               conda-forge
  execnet                        2.0.2         pyhd8ed1ab_0               conda-forge
  executing                      2.0.1         pyhd8ed1ab_0               conda-forge
  expat                          2.5.0         hcb278e6_1                 conda-forge
  fastrlock                      0.8.2         py310hc6cd4ac_2            conda-forge
  filelock                       3.13.1        pyhd8ed1ab_0               conda-forge
  flake8                         6.1.0         pyhd8ed1ab_0               conda-forge
  fmt                            10.1.1        h00ab1b0_1                 conda-forge
  font-ttf-dejavu-sans-mono      2.37          hab24e00_0                 conda-forge
  font-ttf-inconsolata           3.000         h77eed37_0                 conda-forge
  font-ttf-source-code-pro       2.038         h77eed37_0                 conda-forge
  font-ttf-ubuntu                0.83          h77eed37_1                 conda-forge
  fontconfig                     2.14.2        h14ed4e7_0                 conda-forge
  fonts-conda-ecosystem          1             0                          conda-forge
  fonts-conda-forge              1             0                          conda-forge
  fonttools                      4.46.0        py310h2372a71_0            conda-forge
  fortran-compiler               1.7.0         heb67821_0                 conda-forge
  freetype                       2.12.1        h267a509_2                 conda-forge
  fsspec                         2023.12.2     pyhca7485f_0               conda-forge
  gcc                            12.3.0        h8d2909c_2                 conda-forge
  gcc_impl_linux-64              12.3.0        he2b93b0_3                 conda-forge
  gcc_linux-64                   12.3.0        h76fc315_2                 conda-forge
  gettext                        0.21.1        h27087fc_0                 conda-forge
  gfortran                       12.3.0        h499e0f7_2                 conda-forge
  gfortran_impl_linux-64         12.3.0        hfcedea8_3                 conda-forge
  gfortran_linux-64              12.3.0        h7fe76b4_2                 conda-forge
  giflib                         5.2.1         h0b41bf4_3                 conda-forge
  gitdb                          4.0.11        pyhd8ed1ab_0               conda-forge
  gitpython                      3.1.40        pyhd8ed1ab_0               conda-forge
  glib                           2.78.2        hfc55251_0                 conda-forge
  glib-tools                     2.78.2        hfc55251_0                 conda-forge
  gmp                            6.3.0         h59595ed_0                 conda-forge
  gmpy2                          2.1.2         py310h3ec546c_1            conda-forge
  graphite2                      1.3.13        h58526e2_1001              conda-forge
  gst-plugins-base               1.22.7        h8e1006c_0                 conda-forge
  gstreamer                      1.22.7        h98fc4e7_0                 conda-forge
  gxx                            12.3.0        h8d2909c_2                 conda-forge
  gxx_impl_linux-64              12.3.0        he2b93b0_3                 conda-forge
  gxx_linux-64                   12.3.0        h8a814eb_2                 conda-forge
  harfbuzz                       8.3.0         h3d44ed6_0                 conda-forge
  html5lib                       1.1           pyh9f0ad1d_0               conda-forge
  icu                            73.2          h59595ed_0                 conda-forge
  identify                       2.5.32        pyhd8ed1ab_0               conda-forge
  idna                           3.6           pyhd8ed1ab_0               conda-forge
  imagecodecs                    2023.9.18     py310h496a806_2            conda-forge
  imageio                        2.31.5        pyh8c1a49c_0               conda-forge
  imagesize                      1.4.1         pyhd8ed1ab_0               conda-forge
  importlib-metadata             7.0.0         pyha770c72_0               conda-forge
  importlib_metadata             7.0.0         hd8ed1ab_0                 conda-forge
  iniconfig                      2.0.0         pyhd8ed1ab_0               conda-forge
  ipykernel                      6.26.0        pyhf8b6a83_0               conda-forge
  ipython                        8.18.1        pyh707e725_3               conda-forge
  isort                          5.12.0        pyhd8ed1ab_1               conda-forge
  jaraco.classes                 3.3.0         pyhd8ed1ab_0               conda-forge
  jedi                           0.19.1        pyhd8ed1ab_0               conda-forge
  jeepney                        0.8.0         pyhd8ed1ab_0               conda-forge
  jinja2                         3.1.2         pyhd8ed1ab_1               conda-forge
  joblib                         1.3.2         pyhd8ed1ab_0               conda-forge
  jsonpatch                      1.33          pyhd8ed1ab_0               conda-forge
  jsonpointer                    2.4           py310hff52083_3            conda-forge
  jupyter_client                 8.6.0         pyhd8ed1ab_0               conda-forge
  jupyter_core                   5.5.0         py310hff52083_0            conda-forge
  jxrlib                         1.1           h7f98852_2                 conda-forge
  kernel-headers_linux-64        2.6.32        he073ed8_16                conda-forge
  keyring                        24.3.0        py310hff52083_0            conda-forge
  keyutils                       1.6.1         h166bdaf_0                 conda-forge
  kiwisolver                     1.4.5         py310hd41b1e2_1            conda-forge
  krb5                           1.21.2        h659d440_0                 conda-forge
  lame                           3.100         h166bdaf_1003              conda-forge
  lazy_loader                    0.3           pyhd8ed1ab_0               conda-forge
  lcms2                          2.16          hb7c19ff_0                 conda-forge
  ld_impl_linux-64               2.40          h41732ed_0                 conda-forge
  lerc                           4.0.0         h27087fc_0                 conda-forge
  libabseil                      20230802.1    cxx17_h59595ed_0           conda-forge
  libaec                         1.1.2         h59595ed_1                 conda-forge
  libarchive                     3.7.2         h039dbb9_0                 conda-forge
  libavif16                      1.0.3         hed45d22_0                 conda-forge
  libblas                        3.9.0         20_linux64_openblas        conda-forge
  libbrotlicommon                1.1.0         hd590300_1                 conda-forge
  libbrotlidec                   1.1.0         hd590300_1                 conda-forge
  libbrotlienc                   1.1.0         hd590300_1                 conda-forge
  libcap                         2.69          h0f662aa_0                 conda-forge
  libcblas                       3.9.0         20_linux64_openblas        conda-forge
  libclang                       15.0.7        default_hb11cfb5_4         conda-forge
  libclang13                     15.0.7        default_ha2b6cf4_4         conda-forge
  libcublas                      12.3.4.1      hd3aeb46_0                 conda-forge
  libcufft                       11.0.12.1     hd3aeb46_0                 conda-forge
  libcups                        2.3.3         h4637d8d_4                 conda-forge
  libcurand                      10.3.4.107    hd3aeb46_0                 conda-forge
  libcurl                        8.5.0         hca28451_0                 conda-forge
  libcusolver                    11.5.4.101    hd3aeb46_0                 conda-forge
  libcusparse                    12.2.0.103    hd3aeb46_0                 conda-forge
  libdeflate                     1.19          hd590300_0                 conda-forge
  libedit                        3.1.20191231  he28a2e2_2                 conda-forge
  libev                          4.33          hd590300_2                 conda-forge
  libevent                       2.1.12        hf998b51_1                 conda-forge
  libexpat                       2.5.0         hcb278e6_1                 conda-forge
  libffi                         3.4.2         h7f98852_5                 conda-forge
  libflac                        1.4.3         h59595ed_0                 conda-forge
  libgcc-devel_linux-64          12.3.0        h8bca6fd_103               conda-forge
  libgcc-ng                      13.2.0        h807b86a_3                 conda-forge
  libgcrypt                      1.10.3        hd590300_0                 conda-forge
  libgfortran-ng                 13.2.0        h69a702a_3                 conda-forge
  libgfortran5                   13.2.0        ha4646dd_3                 conda-forge
  libglib                        2.78.2        h783c2da_0                 conda-forge
  libgomp                        13.2.0        h807b86a_3                 conda-forge
  libgpg-error                   1.47          h71f35ed_0                 conda-forge
  libhwloc                       2.9.3         default_h554bfaf_1009      conda-forge
  libiconv                       1.17          h166bdaf_0                 conda-forge
  libjpeg-turbo                  3.0.0         hd590300_1                 conda-forge
  liblapack                      3.9.0         20_linux64_openblas        conda-forge
  libllvm15                      15.0.7        h5cf9203_3                 conda-forge
  libmamba                       1.5.6         had39da4_0                 conda-forge
  libmambapy                     1.5.6         py310h39ff949_0            conda-forge
  libnghttp2                     1.58.0        h47da74e_1                 conda-forge
  libnsl                         2.0.1         hd590300_0                 conda-forge
  libnvjitlink                   12.3.101      hd3aeb46_0                 conda-forge
  libogg                         1.3.4         h7f98852_1                 conda-forge
  libopenblas                    0.3.25        pthreads_h413a1c8_0        conda-forge
  libopus                        1.3.1         h7f98852_1                 conda-forge
  libpng                         1.6.39        h753d276_0                 conda-forge
  libpq                          16.1          hfc447b1_2                 conda-forge
  libprotobuf                    4.24.4        hf27288f_0                 conda-forge
  libsanitizer                   12.3.0        h0f45ef3_3                 conda-forge
  libsndfile                     1.2.2         hc60ed4a_1                 conda-forge
  libsodium                      1.0.18        h36c2ea0_1                 conda-forge
  libsolv                        0.7.27        hfc55251_0                 conda-forge
  libsqlite                      3.44.2        h2797004_0                 conda-forge
  libssh2                        1.11.0        h0841786_0                 conda-forge
  libstdcxx-devel_linux-64       12.3.0        h8bca6fd_103               conda-forge
  libstdcxx-ng                   13.2.0        h7e041cc_3                 conda-forge
  libsystemd0                    254           h3516f8a_0                 conda-forge
  libtiff                        4.6.0         ha9c0a0a_2                 conda-forge
  libtorch                       2.1.0         cpu_mkl_hadc400e_103       conda-forge
  libuuid                        2.38.1        h0b41bf4_0                 conda-forge
  libuv                          1.46.0        hd590300_0                 conda-forge
  libvorbis                      1.3.7         h9c3ff4c_0                 conda-forge
  libwebp-base                   1.3.2         hd590300_0                 conda-forge
  libxcb                         1.15          h0b41bf4_0                 conda-forge
  libxkbcommon                   1.6.0         h5d7e998_0                 conda-forge
  libxml2                        2.11.6        h232c23b_0                 conda-forge
  libzlib                        1.2.13        hd590300_5                 conda-forge
  libzopfli                      1.0.3         h9c3ff4c_0                 conda-forge
  lightgbm                       4.3.0         py310hc6cd4ac_0            conda-forge
  llvm-openmp                    17.0.6        h4dfa4b3_0                 conda-forge
  lz4-c                          1.9.4         hcb278e6_0                 conda-forge
  lzo                            2.10          h516909a_1000              conda-forge
  mamba                          1.5.6         py310h51d5547_0            conda-forge
  markupsafe                     2.1.3         py310h2372a71_1            conda-forge
  matplotlib                     3.8.2         py310hff52083_0            conda-forge
  matplotlib-base                3.8.2         py310h62c0568_0            conda-forge
  matplotlib-inline              0.1.6         pyhd8ed1ab_0               conda-forge
  mccabe                         0.7.0         pyhd8ed1ab_0               conda-forge
  menuinst                       2.0.2         py310hff52083_0            conda-forge
  mkl                            2023.2.0      h84fe81f_50496             conda-forge
  more-itertools                 10.1.0        pyhd8ed1ab_0               conda-forge
  mpc                            1.3.1         hfe3b2da_0                 conda-forge
  mpfr                           4.2.1         h9458935_0                 conda-forge
  mpg123                         1.32.3        h59595ed_0                 conda-forge
  mpmath                         1.3.0         pyhd8ed1ab_0               conda-forge
  msgpack-python                 1.0.7         py310hd41b1e2_0            conda-forge
  munkres                        1.1.4         pyh9f0ad1d_0               conda-forge
  mypy_extensions                1.0.0         pyha770c72_0               conda-forge
  mysql-common                   8.0.33        hf1915f5_6                 conda-forge
  mysql-libs                     8.0.33        hca2cd23_6                 conda-forge
  ncurses                        6.4           h59595ed_2                 conda-forge
  nest-asyncio                   1.5.8         pyhd8ed1ab_0               conda-forge
  networkx                       3.2.1         pyhd8ed1ab_0               conda-forge
  nodeenv                        1.8.0         pyhd8ed1ab_0               conda-forge
  nspr                           4.35          h27087fc_0                 conda-forge
  nss                            3.95          h1d7d5a4_0                 conda-forge
  numpy                          1.26.3        py310hb13e2d6_0            conda-forge
  numpydoc                       1.5.0         pyhd8ed1ab_0               conda-forge
  openjpeg                       2.5.0         h488ebb8_3                 conda-forge
  openssl                        3.2.0         hd590300_1                 conda-forge
  packaging                      23.2          pyhd8ed1ab_0               conda-forge
  pandas                         2.2.0         py310hcc13569_0            conda-forge
  parso                          0.8.3         pyhd8ed1ab_0               conda-forge
  pastel                         0.2.1         pyhd8ed1ab_0               conda-forge
  pathspec                       0.11.2        pyhd8ed1ab_0               conda-forge
  patsy                          0.5.4         pyhd8ed1ab_0               conda-forge
  pcre2                          10.42         hcad00b1_0                 conda-forge
  pexpect                        4.8.0         pyh9f0ad1d_2               conda-forge
  pickleshare                    0.7.5         py_1003                    conda-forge
  pillow                         10.1.0        py310h01dd4db_0            conda-forge
  pip                            23.3.1        pyhd8ed1ab_0               conda-forge
  pip-tools                      7.3.0         pyhd8ed1ab_0               conda-forge
  pixman                         0.42.2        h59595ed_0                 conda-forge
  pkginfo                        1.9.6         pyhd8ed1ab_0               conda-forge
  platformdirs                   4.1.0         pyhd8ed1ab_0               conda-forge
  plotly                         5.18.0        pyhd8ed1ab_0               conda-forge
  pluggy                         1.3.0         pyhd8ed1ab_0               conda-forge
  ply                            3.11          py_1                       conda-forge
  pooch                          1.8.0         pyhd8ed1ab_0               conda-forge
  pre-commit                     3.5.0         pyha770c72_0               conda-forge
  prompt-toolkit                 3.0.41        pyha770c72_0               conda-forge
  psutil                         5.9.5         py310h2372a71_1            conda-forge
  pthread-stubs                  0.4           h36c2ea0_1001              conda-forge
  ptyprocess                     0.7.0         pyhd3deb0d_0               conda-forge
  pulseaudio-client              16.1          hb77b528_5                 conda-forge
  pure_eval                      0.2.2         pyhd8ed1ab_0               conda-forge
  pybind11-abi                   4             hd8ed1ab_3                 conda-forge
  pycodestyle                    2.11.1        pyhd8ed1ab_0               conda-forge
  pycosat                        0.6.6         py310h2372a71_0            conda-forge
  pycparser                      2.21          pyhd8ed1ab_0               conda-forge
  pydantic                       2.5.2         pyhd8ed1ab_0               conda-forge
  pydantic-core                  2.14.5        py310hcb5633a_0            conda-forge
  pyflakes                       3.1.0         pyhd8ed1ab_0               conda-forge
  pygments                       2.17.2        pyhd8ed1ab_0               conda-forge
  pylev                          1.4.0         pyhd8ed1ab_0               conda-forge
  pyparsing                      3.1.1         pyhd8ed1ab_0               conda-forge
  pyproject_hooks                1.0.0         pyhd8ed1ab_0               conda-forge
  pyqt                           5.15.9        py310h04931ad_5            conda-forge
  pyqt5-sip                      12.12.2       py310hc6cd4ac_5            conda-forge
  pysocks                        1.7.1         pyha2e5f31_6               conda-forge
  pytest                         7.4.3         pyhd8ed1ab_0               conda-forge
  pytest-xdist                   3.5.0         pyhd8ed1ab_0               conda-forge
  python                         3.10.13       hd12c33a_0_cpython         conda-forge
  python-build                   1.0.3         pyhd8ed1ab_0               conda-forge
  python-dateutil                2.8.2         pyhd8ed1ab_0               conda-forge
  python-tzdata                  2023.3        pyhd8ed1ab_0               conda-forge
  python_abi                     3.10          4_cp310                    conda-forge
  pytorch                        2.1.0         cpu_mkl_py310h3ea73d3_103  conda-forge
  pytz                           2023.3.post1  pyhd8ed1ab_0               conda-forge
  pywavelets                     1.4.1         py310h1f7b6fc_1            conda-forge
  pyyaml                         6.0.1         py310h2372a71_1            conda-forge
  pyzmq                          25.1.2        py310h795f18f_0            conda-forge
  qt-main                        5.15.8        h82b777d_17                conda-forge
  rav1e                          0.6.6         he8a937b_2                 conda-forge
  readline                       8.2           h8228510_1                 conda-forge
  reproc                         14.2.4.post0  hd590300_1                 conda-forge
  reproc-cpp                     14.2.4.post0  h59595ed_1                 conda-forge
  requests                       2.31.0        pyhd8ed1ab_0               conda-forge
  ruamel.yaml                    0.18.5        py310h2372a71_0            conda-forge
  ruamel.yaml.clib               0.2.7         py310h2372a71_2            conda-forge
  scikit-image                   0.22.0        py310hcc13569_2            conda-forge
  scipy                          1.12.0        py310hb13e2d6_2            conda-forge
  seaborn                        0.13.0        hd8ed1ab_0                 conda-forge
  seaborn-base                   0.13.0        pyhd8ed1ab_0               conda-forge
  secretstorage                  3.3.3         py310hff52083_2            conda-forge
  setuptools                     68.2.2        pyhd8ed1ab_0               conda-forge
  sip                            6.7.12        py310hc6cd4ac_0            conda-forge
  six                            1.16.0        pyh6c4a22f_0               conda-forge
  sleef                          3.5.1         h9b69904_2                 conda-forge
  smmap                          5.0.0         pyhd8ed1ab_0               conda-forge
  snappy                         1.1.10        h9fff704_0                 conda-forge
  snowballstemmer                2.2.0         pyhd8ed1ab_0               conda-forge
  sphinx                         7.2.6         pyhd8ed1ab_0               conda-forge
  sphinx-gallery                 0.15.0        pyhd8ed1ab_0               conda-forge
  sphinx-prompt                  1.4.0         pyhd8ed1ab_0               conda-forge
  sphinxcontrib-applehelp        1.0.7         pyhd8ed1ab_0               conda-forge
  sphinxcontrib-devhelp          1.0.5         pyhd8ed1ab_0               conda-forge
  sphinxcontrib-htmlhelp         2.0.4         pyhd8ed1ab_0               conda-forge
  sphinxcontrib-jsmath           1.0.1         py_0                       conda-forge
  sphinxcontrib-qthelp           1.0.6         pyhd8ed1ab_0               conda-forge
  sphinxcontrib-serializinghtml  1.1.9         pyhd8ed1ab_0               conda-forge
  sphinxext-opengraph            0.9.0         pyhd8ed1ab_0               conda-forge
  stack_data                     0.6.2         pyhd8ed1ab_0               conda-forge
  statsmodels                    0.14.0        py310h1f7b6fc_2            conda-forge
  svt-av1                        1.7.0         h59595ed_0                 conda-forge
  sympy                          1.12          pypyh9d50eac_103           conda-forge
  sysroot_linux-64               2.12          he073ed8_16                conda-forge
  tbb                            2021.11.0     h00ab1b0_1                 conda-forge
  tenacity                       8.2.3         pyhd8ed1ab_0               conda-forge
  tifffile                       2023.9.26     pyhd8ed1ab_0               conda-forge
  tk                             8.6.13        noxft_h4845f30_101         conda-forge
  toml                           0.10.2        pyhd8ed1ab_0               conda-forge
  tomli                          2.0.1         pyhd8ed1ab_0               conda-forge
  tomlkit                        0.12.3        pyha770c72_0               conda-forge
  toolz                          0.12.0        pyhd8ed1ab_0               conda-forge
  tornado                        6.3.3         py310h2372a71_1            conda-forge
  tqdm                           4.66.1        pyhd8ed1ab_0               conda-forge
  traitlets                      5.14.0        pyhd8ed1ab_0               conda-forge
  truststore                     0.8.0         pyhd8ed1ab_0               conda-forge
  typed-ast                      1.5.5         py310h2372a71_1            conda-forge
  typing-extensions              4.8.0         hd8ed1ab_0                 conda-forge
  typing_extensions              4.8.0         pyha770c72_0               conda-forge
  tzdata                         2023c         h71feb2d_0                 conda-forge
  ukkonen                        1.0.1         py310hd41b1e2_4            conda-forge
  unicodedata2                   15.1.0        py310h2372a71_0            conda-forge
  urllib3                        1.26.18       pyhd8ed1ab_0               conda-forge
  virtualenv                     20.25.0       pyhd8ed1ab_0               conda-forge
  wcwidth                        0.2.12        pyhd8ed1ab_0               conda-forge
  webencodings                   0.5.1         pyhd8ed1ab_2               conda-forge
  wheel                          0.42.0        pyhd8ed1ab_0               conda-forge
  xcb-util                       0.4.0         hd590300_1                 conda-forge
  xcb-util-image                 0.4.0         h8ee46fc_1                 conda-forge
  xcb-util-keysyms               0.4.0         h8ee46fc_1                 conda-forge
  xcb-util-renderutil            0.3.9         hd590300_1                 conda-forge
  xcb-util-wm                    0.4.1         h8ee46fc_1                 conda-forge
  xkeyboard-config               2.40          hd590300_0                 conda-forge
  xorg-kbproto                   1.0.7         h7f98852_1002              conda-forge
  xorg-libice                    1.1.1         hd590300_0                 conda-forge
  xorg-libsm                     1.2.4         h7391055_0                 conda-forge
  xorg-libx11                    1.8.7         h8ee46fc_0                 conda-forge
  xorg-libxau                    1.0.11        hd590300_0                 conda-forge
  xorg-libxdmcp                  1.1.3         h7f98852_0                 conda-forge
  xorg-libxext                   1.3.4         h0b41bf4_2                 conda-forge
  xorg-libxrender                0.9.11        hd590300_0                 conda-forge
  xorg-renderproto               0.11.1        h7f98852_1002              conda-forge
  xorg-xextproto                 7.3.0         h0b41bf4_1003              conda-forge
  xorg-xf86vidmodeproto          2.3.1         h7f98852_1002              conda-forge
  xorg-xproto                    7.0.31        h7f98852_1007              conda-forge
  xz                             5.2.6         h166bdaf_0                 conda-forge
  yaml                           0.2.5         h7f98852_2                 conda-forge
  yaml-cpp                       0.8.0         h59595ed_0                 conda-forge
  zeromq                         4.3.5         h59595ed_0                 conda-forge
  zfp                            1.0.0         h59595ed_4                 conda-forge
  zipp                           3.17.0        pyhd8ed1ab_0               conda-forge
  zlib                           1.2.13        hd590300_5                 conda-forge
  zlib-ng                        2.0.7         h0b41bf4_0                 conda-forge
  zstandard                      0.22.0        py310h1275a96_0            conda-forge
  zstd                           1.5.5         hfc55251_0                 conda-forge
```
</details>

**Comment by leofang** [comment]
CuPy v13 can be imported in a CPU only environment (without driver installed or CUDA Toolkit present), but it cannot actually run without a valid driver + GPU. Anything you see here is not what CuPy can help. May I ask what your are trying to achieve?

**Comment by leofang** [comment]
Note: the failure of `cupy.show_config()` seems to be worth addressing.

**Comment by adrinjalali** [comment]
This is in the context of our test suite in `scikit-learn`, and there we skip when packages are not installed. But because of the situation on my system, I can simply do `mamba install cupy` and it works, so the tests try to create `cupy` data arrays and it fails. If we could have some way to do `skip_if_cupy_fails_on_gpu`, then we can easily skip those tests. But by going through the docs, I couldn't find a way to do that w/o a `try...except` around `cupy.ones` call, which takes over 10 seconds.

**Comment by leofang** [comment]
I see. You shouldn't be trying to run any actual GPU operation without confirming a GPU exists. I think you'll need a proxy to guard it, something like this
```shell
$ # make all GPUS invisible to the driver, same as what you do now
$ CUDA_VISIBLE_DEVICES= python -c "import cupy; print(cupy.cuda.runtime.getDeviceCount())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "cupy_backends/cuda/api/runtime.pyx", line 390, in cupy_backends.cuda.api.runtime.getDeviceCount
  File "cupy_backends/cuda/api/runtime.pyx", line 393, in cupy_backends.cuda.api.runtime.getDeviceCount
  File "cupy_backends/cuda/api/runtime.pyx", line 146, in cupy_backends.cuda.api.runtime.check_status
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorNoDevice: no CUDA-capable device is detected
```
and
```shell
$ # make GPU 0 visible to the driver
$ CUDA_VISIBLE_DEVICES=0 python -c "import cupy; print(cupy.cuda.runtime.getDeviceCount())"
1
```
There might be better ways to achieve this, but in any case we need to rely on the CUDA driver to give us the information.

**Comment by leofang** [comment]
As I said, there is really nothing CuPy can do as this query goes to the CUDA user mode driver (through CUDA runtime). Though I would be curious how you did this
> However, I've disabled NVIDIA drivers in my sessions to save power, in archlinux.

It might be relevant.

I keep the "bug" tag only for the team to triage the `show_config()` issue later.

**Comment by adrinjalali** [comment]
> this query goes to the CUDA user mode driver (through CUDA runtime).

Any repo / place where I could report this? I can't find a relevant repo.

> Though I would be curious how you did this

Using https://github.com/Askannz/optimus-manager

**Comment by leofang** [comment]
> I keep the "bug" tag only for the team to triage the `show_config()` issue later.

Tracked in #8158. Let me remove the bug label here.

**Comment by leofang** [comment]
>>>  Though I would be curious how you did this
>>> 
>>> > However, I've disabled NVIDIA drivers in my sessions to save power, in archlinux.
>>> 
>>> It might be relevant. I can imagine how the driver behavior might be different. (On my side, the driver responds instantly with setting `CUDA_VISIBLE_DEVICES`.)
>>> 
>> Using https://github.com/Askannz/optimus-manager
>>
> Obviously you'll need to report to `optimus-manager` folks, as this is not an official way that NVIDIA supports.

To add to this part of conversation, please note that the optimus-mangaer project seems unmaintained for quite some time, see the maintainer's post (https://github.com/Askannz/optimus-manager/issues/543) and search the issues there with "nvidia" in the issue title.

**Comment by adrinjalali** [comment]
Yeah fair enough. I haven't reconfigured my laptop in a couple of years (love that about arch 😁 )

Closing this issue since the other issue now exists. And my issue is solved by removing all nvidia driver packages and now at least time to fail for the script is instant and not 10s. Thank y'all.
