### ISSUE TITLE
Empty array cuases `intersect1d` to crash Cupy

### ISSUE THREAD

**Issue by TheYoke** [cupy/cupy#8937]
### Description

If the second argument of `intersect1d` is empty, this will cause `CUDARuntimeError: cudaErrorIllegalAddress: an illegal memory access was encountered` error and any subsequent use of Cupy (e.g. `cp.array([0])`) will also cause the same error.

### To Reproduce

```py
import cupy as cp
cp.intersect1d(cp.array([0]), cp.array([]))
```

### Installation

Conda-Forge (`conda install ...`)

### Environment

```
OS                           : Linux-6.8.0-41-generic-x86_64-with-glibc2.39
Python Version               : 3.12.2
CuPy Version                 : 13.3.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 2.2.2
SciPy Version                : None
Cython Build Version         : 0.29.37
Cython Runtime Version       : None
CUDA Root                    : None
nvcc PATH                    : None
CUDA Build Version           : 12060
CUDA Driver Version          : 12020
CUDA Runtime Version         : 12060 (linked to CuPy) / RuntimeError('CuPy failed to load libcudart.so.12: OSError: libcudart.so.12: cannot open shared object file: No such file or directory') (locally installed)
CUDA Extra Include Dirs      : ['/home/theyoke/miniconda3/targets/x86_64-linux/include', '/home/theyoke/miniconda3/include']
cuBLAS Version               : 120803
cuFFT Version                : 11303
cuRAND Version               : 10309
cuSOLVER Version             : (11, 7, 2)
cuSPARSE Version             : 12507
NVRTC Version                : (12, 8)
Thrust Version               : 200500
CUB Build Version            : 200600
Jitify Build Version         : <unknown>
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce RTX 3060
Device 0 Compute Capability  : 86
Device 0 PCI Bus ID          : 0000:0B:00.0
```

**Comment by kmaehashi** [comment]
Thanks, confirmed on our end. PRs welcome.

**Comment by zazabap** [comment]
@kmaehashi If this bug is not fixed yet, could I submit a PR to resolve the issue? I hope to contribute to CuPy.

**Comment by kmaehashi** [comment]
@zazabap No ones working on it, please go ahead :pray:

**Comment by zazabap** [comment]
@kmaehashi I found the bug is mainly due to line 175 in truth.py, the `_search._exists_kernel` will return an address to the mask object and the later line 
`return arr1[mask]` will just return the illegal memory access. This only happens when the arr2 is an empty array. Therefore, I could simply add one line to protect the edge case. 
```
if arr2.size == 0 : 
    return arr2
```

In the other hand, if not protected such way, we have to modify the /cupy/cupy/_sorting/search.py line 362-373 `_core.ElementwiseKernel`.  

```
_exists_kernel = _core.ElementwiseKernel(
    'S x, raw T bins, int64 n_bins, bool invert',  # Input parameters
    'bool out',  # Output type
    '''
    const bool assume_increasing = true;
    const bool side_is_right = false;
    long long y;

    if (n_bins == 0) {  // Quick fix: Avoid illegal memory access
        out = false;
        return;
    }
    '''
    + _searchsorted_code + '''  
    out = (y == n_bins ? false : bins[y] == x);
    if (invert) out = !out;
    ''', 
    name='cupy_exists_kernel', 
    preamble=_preamble+_hip_preamble
)
```

This fix also simply add a bin check in c++ format. I am not exactly sure which one you would prefer. Currently I add the python solution for the PR, because I consider function call to _kernel and _core may use more time.

**Comment by zazabap** [comment]
#8997

**Comment by Harishjitu** [comment]
Since the last PR was closed a while ago, I attempted to fix this issue.
The fix adds an early return with proper dtype handling using `result_type()` to match NumPy behavior.
