### ISSUE TITLE
Failed to initialize NCCL communicator with CUDA11.8 + NCCL2.15.1

### ISSUE THREAD

**Issue by DicardoX** [cupy/cupy#9090]
### Description

Hi, I'm using `cupy-cuda11x==13.4.1` in a Docker container with CUDA11.8, NCCL2.15.1, Python3.9, debian10 software setups (on a node with 2 H800 GPUs). When I execute the following testing code (see `test_nccl_comm.py` in **To Reproduce**), a NCCL invalid usage error occurs:

```bash
[0] NCCL INFO cudaDriverVersion 12020
[0] NCCL INFO NCCL_SOCKET_FAMILY set by environment to AF_INET6
[0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to =bond0
[0] NCCL INFO Bootstrap : Using bond0:fdbd:dccd:cdf1:206::40<0>
[0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
NCCL version 2.16.5+cuda11.8
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/workdir/test_nccl_comm.py", line 14, in check_nccl_communicator
    comm = cp.cuda.nccl.NcclCommunicator(num_gpus, nccl_id, rank)
  File "cupy_backends/cuda/libs/nccl.pyx", line 283, in cupy_backends.cuda.libs.nccl.NcclCommunicator.__init__
  File "cupy_backends/cuda/libs/nccl.pyx", line 129, in cupy_backends.cuda.libs.nccl.check_status
cupy_backends.cuda.libs.nccl.NcclError: NCCL_ERROR_INVALID_USAGE: invalid usage
[0] NCCL INFO NCCL_IB_DISABLE set by environment to 0.
[0] NCCL INFO Failed to open libibverbs.so[.1]
[0] NCCL INFO NCCL_SOCKET_FAMILY set by environment to AF_INET6
[0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to =bond0
[0] NCCL INFO NET/Socket : Using [0]IPV6_ADDR<0>

[0] net.cc:290 NCCL WARN Error: network IB not found.
[0] NCCL INFO init.cc:308 -> 5
[0] NCCL INFO init.cc:1099 -> 5
[0] NCCL INFO init.cc:1173 -> 5
0] NCCL INFO init.cc:1209 -> 5
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/workdir/test_nccl_comm.py", line 14, in check_nccl_communicator
    comm = cp.cuda.nccl.NcclCommunicator(num_gpus, nccl_id, rank)
  File "cupy_backends/cuda/libs/nccl.pyx", line 283, in cupy_backends.cuda.libs.nccl.NcclCommunicator.__init__
  File "cupy_backends/cuda/libs/nccl.pyx", line 129, in cupy_backends.cuda.libs.nccl.check_status
cupy_backends.cuda.libs.nccl.NcclError: NCCL_ERROR_INVALID_USAGE: invalid usage
[1] NCCL INFO cudaDriverVersion 12020
[1] NCCL INFO NCCL_SOCKET_FAMILY set by environment to AF_INET6
[1] NCCL INFO NCCL_SOCKET_IFNAME set by environment to =bond0
[1] NCCL INFO Bootstrap : Using bond0:fdbd:dccd:cdf1:206::40<0>
[1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
[1] NCCL INFO NCCL_IB_DISABLE set by environment to 0.
[1] NCCL INFO Failed to open libibverbs.so[.1]
[1] NCCL INFO NCCL_SOCKET_FAMILY set by environment to AF_INET6
[1] NCCL INFO NCCL_SOCKET_IFNAME set by environment to =bond0
[1] NCCL INFO NET/Socket : Using [0]bond0:IPV6_ADDR<0>

[1] net.cc:290 NCCL WARN Error: network IB not found.
[1] NCCL INFO init.cc:308 -> 5
[1] NCCL INFO init.cc:1099 -> 5
[1] NCCL INFO init.cc:1173 -> 5
[1] NCCL INFO init.cc:1209 -> 5
[0] NCCL INFO NCCL_SOCKET_FAMILY set by environment to AF_INET6
[0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to =bond0
[0] NCCL INFO Bootstrap : Using bond0:fdbd:dccd:cdf1:206::40<0>
[0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
```

Is there any software version mismatch? Any suggestions will be appreciated, thx!

### To Reproduce

```py
# Usage: 
#   NCCL_DEBUG=INFO python3 test_nccl_comm.py

import cupy as cp
from cupy.cuda import nccl
import os
import multiprocessing as mp


def check_nccl_communicator(num_gpus, nccl_id, rank):
    # Init NCCL communicators
    with cp.cuda.Device(rank):
        comm = cp.cuda.nccl.NcclCommunicator(num_gpus, nccl_id, rank)
    # Sync
    cp.cuda.Device(rank).synchronize()
    print("NCCL communicators established successfully")


if __name__ == "__main__":
    # Visible devices
    os.environ["CUDA_VISIBLE_DEVICES"] = "0,1"    
    # Use 2 GPUs (1-node) for testing
    num_gpus = 2
    devices = list(range(num_gpus))
    nccl_id = cp.cuda.nccl.get_unique_id()

    mp.set_start_method('spawn')   # Avoid inter-proc contention
    
    procs = []
    for i in range(num_gpus):
        proc = mp.Process(
            target=check_nccl_communicator,
            args=(num_gpus, nccl_id, i),
        )
        proc.start()
        procs.append(proc)
    
    for proc in procs:
        proc.join()
```

### Installation

Wheel (`pip install cupy-***`)

### Environment

```
OS                           : Linux-5.15.120.bsk.6-amd64-x86_64-with-glibc2.28
Python Version               : 3.9.0
CuPy Version                 : 13.4.1
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.23.5
SciPy Version                : 1.12.0
Cython Build Version         : 3.0.12
Cython Runtime Version       : 3.0.12
CUDA Root                    : /usr/local/cuda
nvcc PATH                    : /usr/local/cuda/bin/nvcc
CUDA Build Version           : 11080
CUDA Driver Version          : 12020
CUDA Runtime Version         : 11080 (linked to CuPy) / 11080 (locally installed)
CUDA Extra Include Dirs      : []
cuBLAS Version               : 111103
cuFFT Version                : 10900
cuRAND Version               : 10300
cuSOLVER Version             : (11, 4, 1)
cuSPARSE Version             : 11705
NVRTC Version                : (11, 8)
Thrust Version               : 200800
CUB Build Version            : 200800
Jitify Build Version         : <unknown>
cuDNN Build Version          : 8801
cuDNN Version                : 8600
NCCL Build Version           : 21605
NCCL Runtime Version         : 21605
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA H800
Device 0 Compute Capability  : 90
Device 0 PCI Bus ID          : 0000:0A:00.0
Device 1 Name                : NVIDIA H800
Device 1 Compute Capability  : 90
Device 1 PCI Bus ID          : 0000:18:00.0
Device 2 Name                : NVIDIA H800
Device 2 Compute Capability  : 90
Device 2 PCI Bus ID          : 0000:B8:00.0
Device 3 Name                : NVIDIA H800
Device 3 Compute Capability  : 90
Device 3 PCI Bus ID          : 0000:C1:00.0
```

**Comment by kmaehashi** [comment]
Hmm, the problem is not reproducing on my end.

```
pg00:1822703:1822703 [1] NCCL INFO comm 0x55f205c38300 rank 1 nranks 2 cudaDev 1 busId 89000 commId 0x1328ee0a0e0cb7aa - Init COMPLETE
pg00:1822702:1822702 [0] NCCL INFO comm 0x55e43a2ced70 rank 0 nranks 2 cudaDev 0 busId b1000 commId 0x1328ee0a0e0cb7aa - Init COMPLETE
NCCL communicators established successfully
NCCL communicators established successfully
```

```
>>> cupy.show_config(_full=True)
OS                           : Linux-5.15.0-135-generic-x86_64-with-glibc2.35
Python Version               : 3.9.21
CuPy Version                 : 13.4.1
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 2.0.2
SciPy Version                : None
Cython Build Version         : 3.0.12
Cython Runtime Version       : None
CUDA Root                    : /usr/local/cuda-11.8.0
nvcc PATH                    : ccache nvcc
CUDA Build Version           : 11080
CUDA Driver Version          : 12080
CUDA Runtime Version         : 11080 (linked to CuPy) / 11080 (locally installed)
CUDA Extra Include Dirs      : []
cuBLAS Version               : 111103
cuFFT Version                : 10900
cuRAND Version               : 10300
cuSOLVER Version             : (11, 4, 1)
cuSPARSE Version             : 11705
NVRTC Version                : (11, 8)
Thrust Version               : 200800
CUB Build Version            : 200800
Jitify Build Version         : <unknown>
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : 21605
NCCL Runtime Version         : 21605
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA L40S
Device 0 Compute Capability  : 89
Device 0 PCI Bus ID          : 0000:B1:00.0
```

**Comment by DicardoX** [comment]
This issue has been solved by: `unset NCCL_NET` (`NCCL_NET=IB` previously) to enable automated network interface fallback.
