### ISSUE TITLE
Docker: failed to load libnvrtc.so.13: OSError: libnvrtc.so.13 - missing library in v13.6.0

### ISSUE THREAD

**Issue by four43** [cupy/cupy#9318]
### Description

When running the brand new docker image tagged v13.6.0, when running cupy I get the following error:

`CuPy failed to load libnvrtc.so.13: OSError: libnvrtc.so.13: cannot open shared object file: No such file or directory`

### To Reproduce

I had Claude Sonnet build a quick little "hello world" script:
```py
import cupy as cp
import numpy as np
import time

def main():
    print("CuPy Hello World - GPU Computing Example")
    print("=" * 50)

    # Check if CUDA is available
    print(f"CUDA available: {cp.cuda.is_available()}")
    print(f"Number of GPU devices: {cp.cuda.runtime.getDeviceCount()}")
    print(f"Current device: {cp.cuda.device.get_device_id()}")
    print()

    # Create arrays on GPU and CPU for comparison
    size = 1000000
    print(f"Array size: {size:,} elements")

    # CPU computation with NumPy
    print("\n--- CPU Computation (NumPy) ---")
    start_time = time.time()

    # Create arrays on CPU
    a_cpu = np.random.random(size).astype(np.float32)
    b_cpu = np.random.random(size).astype(np.float32)

    # Perform computation on CPU
    result_cpu = a_cpu * b_cpu + np.sin(a_cpu)

    cpu_time = time.time() - start_time
    print(f"CPU computation time: {cpu_time:.4f} seconds")
    print(f"CPU result sample: {result_cpu[:5]}")

    # GPU computation with CuPy
    print("\n--- GPU Computation (CuPy) ---")
    start_time = time.time()

    # Create arrays on GPU
    a_gpu = cp.random.random(size, dtype=cp.float32)
    b_gpu = cp.random.random(size, dtype=cp.float32)

    # Perform computation on GPU
    result_gpu = a_gpu * b_gpu + cp.sin(a_gpu)

    # Copy result back to CPU for display
    result_gpu_cpu = cp.asnumpy(result_gpu)

    gpu_time = time.time() - start_time
    print(f"GPU computation time: {gpu_time:.4f} seconds")
    print(f"GPU result sample: {result_gpu_cpu[:5]}")

    # Performance comparison
    print(f"\nSpeedup: {cpu_time/gpu_time:.2f}x")

    # Demonstrate GPU memory management
    print(f"\n--- GPU Memory Info ---")
    mempool = cp.get_default_memory_pool()
    print(f"Used GPU memory: {mempool.used_bytes() / 1024**2:.2f} MB")
    print(f"Total GPU memory: {mempool.total_bytes() / 1024**2:.2f} MB")

    # Matrix multiplication example
    print(f"\n--- Matrix Multiplication Example ---")
    matrix_size = 1000

    # CPU matrix multiplication
    start_time = time.time()
    A_cpu = np.random.random((matrix_size, matrix_size)).astype(np.float32)
    B_cpu = np.random.random((matrix_size, matrix_size)).astype(np.float32)
    C_cpu = np.dot(A_cpu, B_cpu)
    cpu_matmul_time = time.time() - start_time

    # GPU matrix multiplication
    start_time = time.time()
    A_gpu = cp.random.random((matrix_size, matrix_size), dtype=cp.float32)
    B_gpu = cp.random.random((matrix_size, matrix_size), dtype=cp.float32)
    C_gpu = cp.dot(A_gpu, B_gpu)
    # Synchronize to ensure computation is complete
    cp.cuda.Stream.null.synchronize()
    gpu_matmul_time = time.time() - start_time

    print(f"CPU matrix multiplication ({matrix_size}x{matrix_size}): {cpu_matmul_time:.4f} seconds")
    print(f"GPU matrix multiplication ({matrix_size}x{matrix_size}): {gpu_matmul_time:.4f} seconds")
    print(f"Matrix multiplication speedup: {cpu_matmul_time/gpu_matmul_time:.2f}x")

    # Clean up GPU memory
    mempool.free_all_blocks()
    print("\nGPU memory cleaned up successfully!")

if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"Error: {e}")
        print("Make sure you have:")
        print("1. NVIDIA GPU with CUDA support")
        print("2. CUDA toolkit installed")
        print("3. CuPy installed")
```

Output:

```shell
CuPy Hello World - GPU Computing Example
==================================================
CUDA available: True
Number of GPU devices: 1
Current device: 0

Array size: 1,000,000 elements

--- CPU Computation (NumPy) ---
CPU computation time: 0.0105 seconds
CPU result sample: [1.1827266  1.1893706  0.30332127 0.61960924 0.7348019 ]

--- GPU Computation (CuPy) ---
Error: CUDA_ERROR_NO_BINARY_FOR_GPU: no kernel image is available for execution on the device
Make sure you have:
1. NVIDIA GPU with CUDA support
2. CUDA toolkit installed
3. CuPy installed
```
Manually run `pip install cupy-cuda13x`

After resolving the warnings about multiple versions installed,

Rerunning, we get:
```
CuPy Hello World - GPU Computing Example
==================================================
CUDA available: True
Number of GPU devices: 1
Current device: 0

Array size: 1,000,000 elements

--- CPU Computation (NumPy) ---
CPU computation time: 0.0106 seconds
CPU result sample: [0.17307349 0.01458205 0.01575086 0.7100002  1.523972  ]

--- GPU Computation (CuPy) ---
Error: CuPy failed to load libnvrtc.so.13: OSError: libnvrtc.so.13: cannot open shared object file: No such file or directo
ry
Make sure you have:
1. NVIDIA GPU with CUDA support
2. CUDA toolkit installed
3. CuPy installed
```

### Installation

Wheel (`pip install cupy-***`)

### Environment

```
root@423be01cdfa3:/data# python3 -c 'import cupy; cupy.show_config(_full=True)'
OS                           : Linux-6.9.10+bpo-amd64-x86_64-with-glibc2.35
Python Version               : 3.10.12
CuPy Version                 : 13.6.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 2.2.6
SciPy Version                : 1.15.3
Cython Build Version         : 3.0.12
Cython Runtime Version       : 3.1.3
CUDA Root                    : /usr/local/cuda
nvcc PATH                    : /usr/local/cuda/bin/nvcc
CUDA Build Version           : 12090
CUDA Driver Version          : 13000
CUDA Runtime Version         : 12090 (linked to CuPy) / 12020 (locally installed)
CUDA Extra Include Dirs      : []
cuBLAS Version               : 120201
cuFFT Version                : 11008
cuRAND Version               : 10303
cuSOLVER Version             : (11, 5, 2)
cuSPARSE Version             : 12101
NVRTC Version                : (12, 2)
Thrust Version               : 200800
CUB Build Version            : 200800
Jitify Build Version         : <unknown>
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce RTX 5070 Ti
Device 0 Compute Capability  : 120
Device 0 PCI Bus ID          : 0000:01:00.0
```

```
$ nvidia-smi
Mon Aug 18 12:37:35 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.65.06              Driver Version: 580.65.06      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 5070 Ti     On  |   00000000:01:00.0  On |                  N/A |
| 33%   33C    P0             34W /  300W |    1291MiB /  16303MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

### Additional Information

I'm unsure about the backwards compatibility of this library, but would it make sense to publish docker images for Cuda 11x, Cuda12x, Cuda 13x separately? 

Thanks for the new release!

**Comment by four43** [comment]
Ah, this is just because it's using the CUDA 12 base image. I was able to get it working with the following Dockerfile:

```dockerfile
FROM nvidia/cuda:13.0.0-devel-ubuntu24.04

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
    python3-dev \
    python3-pip \
    python3-wheel \
    python3-setuptools && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*

RUN pip3 install --break-system-packages --no-cache-dir 'cupy-cuda13x[all]'
```

**Comment by leofang** [comment]
I don't think this is a bug. The [current Dockerfile](https://github.com/cupy/cupy/blob/v13/docker/python3/Dockerfile) is intended to work out of box with CUDA 12 (though arguably we should bump the base from 12.2 to 12.9). CuPy code should just work after dropping into the container without any extra installation or setup needed. Manually installing an incompatible wheel as described:
> Manually run `pip install cupy-cuda13x`

is not a supported use case.
